export const UAE_EMIRATES = {
  '‘Ajmān': ['‘Ajmān', 'Sharīyah', 'Maşfūţ', 'Şufayrī'],
  'Abū Z̧aby': ['Abu Dhabi', 'Al ‘Ayn', 'Madīnat Zāyid'],
  'Al Fujayrah': [
    'Al Fujayrah',
    'Zubārah',
    'Ţayyibah',
    'Biţnah',
    'Mu‘tariḑah',
    'Theeb',
    'Wa‘bayn',
    'Al Qurayyah',
    'Al Manāmah',
    '‘Abādilah',
    'Al Ḩalāh',
    'Ghurfah',
    'Ḩayl',
    'Sā’if',
    'Badīyah',
    'Far‘ah',
    'Mukhtaraqah',
    'Yalah',
    'Rughaylāt',
    'Ḩafarah',
    'Ḩārat Zuţūţ',
    'Al ‘Uyaynah',
    'Rūl Ḑadnā',
    'Tawian',
    'Shawīyah',
    'Dibā',
    'Sinnah',
    'Dūb',
    'Sram',
    'Thoban',
    'Al Gissemari',
    'Khulaybīyah',
    'Z̧anḩah',
    'Saqamqam',
    'Ḑāhir',
    'Jareef',
    'Riyāmah',
    'Al Kubūs',
    '‘Ashashah',
    'Ḑadnā',
    '‘Aqqah',
    'Ras Dibba',
    'Murbaḑ',
    'Şafad',
    'Ţarīqat Ja‘d',
  ],
  'Ash Shāriqah': [
    'Sharjah',
    'Khawr Fakkān',
    'Kalbā',
    'Naḩwah',
    'Ḩaşat al Bidīyah',
    'Muḑayfī',
    'Rafā‘',
    'Lūlayyah',
    'Wādī Shī',
    'Ash Shu‘ayb',
    'Ḩiyāwah',
    'Ar Rufayşah',
    'Shīs',
    'Al Jazīrah',
    'Al Ḩamrīyah',
    'Adh Dhayd',
    'Al ‘Awdah',
    'Qidfa‘',
    'Ghayl',
    'Khawr Kalbā',
    '‘Uqayr',
    'Ḩarrah',
    'Şūr',
    'Murbaḩ',
    'Ḩayāt',
    'Girath',
    'Nuhayy',
  ],
  Dubayy: [
    'Dubai',
    'Qarayţaysah',
    'Margham',
    'Qimah',
    '‘Ūd al Bayḑā’',
    'Ferij al Muhadham',
    'Hunaywah',
    'Al Faq‘',
    '‘Urqūb Juwayza',
    'Ḩayl',
    'Ḩattā',
    'Al Lusaylī',
    'Warīsān',
  ],
  'Ra’s al Khaymah': [
    'Ra’s al Khaymah',
    'Al Jazīrah al Ḩamrā’',
    '‘Asamah',
    'Al ‘Ayn al Ghumūr',
    'Waḩlah',
    'Ḑab‘ah',
    'Mawrid',
  ],
  'Umm al Qaywayn': ['Umm al Qaywayn'],
};
