export const AFGHANISTAN_PROVINCES_CITIES = {
  Badakhshan: [
    'Ashkāsham',
    'Fayzabad',
    'Jurm',
    'Khandūd',
    'Rāghistān',
    'Wākhān',
  ],
  Badghis: ['Ghormach', 'Qala i Naw'],
  Baghlan: ['Baghlān', 'Ḩukūmatī Dahanah-ye Ghōrī', 'Nahrīn', 'Pul-e Khumrī'],
  Balkh: [
    'Balkh',
    'Dowlatābād',
    'Khulm',
    'Lab-Sar',
    'Mazār-e Sharīf',
    'Qarchī Gak',
  ],
  Bamyan: ['Bāmyān', 'Panjāb'],
  Daykundi: ['Nīlī'],
  Farah: ['Farah'],
  Faryab: ['Andkhoy', 'Maymana'],
  Ghazni: ['Ghazni'],
  Ghōr: ['Fayrōz Kōh', 'Shahrak'],
  Helmand: [
    '‘Alāqahdārī Dīshū',
    'Gereshk',
    'Lashkar Gāh',
    'Markaz-e Ḩukūmat-e Darwēshān',
    'Sangīn',
  ],
  Herat: [
    'Chahār Burj',
    'Ghōriyān',
    'Herāt',
    'Kafir Qala',
    'Karukh',
    'Kuhsān',
    'Kushk',
    'Qarah Bāgh',
    'Shīnḏanḏ',
    'Tīr Pul',
    'Zindah Jān',
  ],
  Jowzjan: ['Āqchah', 'Darzāb', 'Qarqīn', 'Shibirghān'],
  Kabul: ['Kabul', 'Mīr Bachah Kōṯ', 'Paghmān'],
  Kandahar: ['Kandahār'],
  Kapisa: ['Sidqābād'],
  Khost: ['Khōst'],
  Kunar: ['Asadabad', 'Āsmār'],
  'Kunduz Province': [
    'Dasht-e Archī',
    'Imām Şāḩib',
    'Khanabad',
    'Kunduz',
    'Qarāwul',
  ],
  Laghman: ['Mehtar Lām'],
  Logar: ['Baraki Barak', 'Ḩukūmatī Azrah', 'Pul-e ‘Alam'],
  Nangarhar: ['Bāsawul', 'Jalālābād', 'Markaz-e Woluswalī-ye Āchīn'],
  Nimruz: ['Khāsh', 'Mīrābād', 'Rūdbār', 'Zaranj'],
  Nuristan: ['Pārūn'],
  Paktia: ['Gardez'],
  Paktika: ['Saṟōbī', 'Zaṟah Sharan', 'Zarghūn Shahr'],
  Panjshir: ['Bāzārak'],
  Parwan: ['Charikar', 'Jabal os Saraj'],
  Samangan: ['Aībak'],
  'Sar-e Pol': [
    'Chīras',
    'Larkird',
    'Qal‘ah-ye Shahr',
    'Sang-e Chārak',
    'Sar-e Pul',
    'Tagāw-Bāy',
    'Tukzār',
  ],
  Takhar: ['Ārt Khwājah', 'Taloqan'],
  Urozgan: ['Tarinkot', 'Uruzgān'],
  Zabul: ['Qalāt'],
};
