export const ALBANIA_COUNTIES_CITIES = {
  'Berat District': [
    'Banaj',
    'Bashkia Berat',
    'Bashkia Kuçovë',
    'Bashkia Poliçan',
    'Bashkia Skrapar',
    'Berat',
    'Çorovodë',
    'Kuçovë',
    'Poliçan',
    'Rrethi i Beratit',
    'Rrethi i Kuçovës',
    'Rrethi i Skraparit',
    'Ura Vajgurore',
  ],
  'Dibër County': [
    'Bashkia Bulqizë',
    'Bashkia Klos',
    'Bashkia Mat',
    'Bulqizë',
    'Burrel',
    'Klos',
    'Peshkopi',
    'Rrethi i Bulqizës',
    'Rrethi i Dibrës',
    'Rrethi i Matit',
    'Ulëz',
  ],
  'Durrës District': [
    'Bashkia Durrës',
    'Bashkia Krujë',
    'Bashkia Shijak',
    'Durrës',
    'Durrës District',
    'Fushë-Krujë',
    'Krujë',
    'Rrethi i Krujës',
    'Shijak',
    'Sukth',
  ],
  'Fier County': [
    'Ballsh',
    'Bashkia Divjakë',
    'Bashkia Fier',
    'Bashkia Mallakastër',
    'Bashkia Patos',
    'Divjakë',
    'Fier',
    'Fier-Çifçi',
    'Lushnjë',
    'Patos',
    'Patos Fshat',
    'Roskovec',
    'Rrethi i Mallakastrës',
  ],
  'Gjirokastër District': [
    'Bashkia Dropull',
    'Bashkia Kelcyrë',
    'Bashkia Libohovë',
    'Bashkia Memaliaj',
    'Bashkia Përmet',
    'Bashkia Tepelenë',
    'Gjinkar',
    'Gjirokastër',
    'Këlcyrë',
    'Lazarat',
    'Libohovë',
    'Memaliaj',
    'Përmet',
    'Tepelenë',
  ],
  'Korçë County': [
    'Bashkia Devoll',
    'Bashkia Kolonjë',
    'Bashkia Maliq',
    'Bashkia Pustec',
    'Bilisht',
    'Ersekë',
    'Korçë',
    'Leskovik',
    'Libonik',
    'Maliq',
    'Mborje',
    'Pogradec',
    'Rrethi i Devollit',
    'Rrethi i Kolonjës',
    'Velçan',
    'Voskopojë',
  ],
  'Kukës District': [
    'Bajram Curri',
    'Krumë',
    'Kukës',
    'Rrethi i Hasit',
    'Rrethi i Kukësit',
  ],
  'Lezhë County': [
    'Bashkia Kurbin',
    'Bashkia Lezhë',
    'Bashkia Mirditë',
    'Kurbnesh',
    'Laç',
    'Lezhë',
    'Mamurras',
    'Milot',
    'Rrëshen',
    'Rrethi i Kurbinit',
    'Rubik',
    'Shëngjin',
  ],
  'Shkodër District': [
    'Bashkia Malësi e Madhe',
    'Bashkia Pukë',
    'Bashkia Vau i Dejës',
    'Fushë-Arrëz',
    'Koplik',
    'Pukë',
    'Rrethi i Malësia e Madhe',
    'Rrethi i Shkodrës',
    'Shkodër',
    'Vau i Dejës',
    'Vukatanë',
  ],
  'Tirana District': [
    'Bashkia Kavajë',
    'Bashkia Vorë',
    'Kamëz',
    'Kavajë',
    'Krrabë',
    'Rrethi i Kavajës',
    'Rrethi i Tiranës',
    'Rrogozhinë',
    'Sinaballaj',
    'Tirana',
    'Vorë',
  ],
  'Vlorë County': [
    'Bashkia Finiq',
    'Bashkia Himarë',
    'Bashkia Konispol',
    'Bashkia Selenicë',
    'Bashkia Vlorë',
    'Delvinë',
    'Himarë',
    'Konispol',
    'Ksamil',
    'Orikum',
    'Rrethi i Delvinës',
    'Sarandë',
    'Selenicë',
    'Vlorë',
  ],
};
