export const ANGOLA_STATE_CITY = {
  'Bengo Province': [
    'Ambriz',
    'Bula Atumba',
    'Caxito',
    'Dande',
    'Muxima',
    'Nambuangongo',
    'Pango Aluquém',
    'Úcua',
  ],
  'Benguela Province': [
    'Baía Farta',
    'Balombo',
    'Benguela',
    'Bocoio',
    'Caimbambo',
    'Catumbela',
    'Chongoroi',
    'Cubal',
    'Ganda',
    'Lobito',
    'Sumbe',
  ],
  'Bié Province': ['Camacupa', 'Catabola', 'Chissamba', 'Cuito'],
  'Cabinda Province': ['Cabinda'],
  'Cuando Cubango Province': ['Menongue'],
  'Cuanza Norte Province': ['Camabatela', 'N’dalatando'],
  'Cuanza Sul': ['Quibala', 'Sumbe', 'Uacu Cungo'],
  'Cunene Province': ['Ondjiva'],
  'Huambo Province': ['Caála', 'Chela', 'Huambo', 'Longonjo'],
  'Huíla Province': [
    'Caconda',
    'Caluquembe',
    'Chibia',
    'Chicomba',
    'Chipindo',
    'Cuvango',
    'Gambos',
    'Humpata',
    'Jamba',
    'Lubango',
    'Matala',
    'Quilengues',
    'Quipungo',
  ],
  'Luanda Province': [
    'Belas',
    'Cacuaco',
    'Cazenga',
    'Icolo e Bengo',
    'Luanda',
    'Talatona',
    'Viana',
  ],
  'Lunda Norte Province': ['Lucapa'],
  'Lunda Sul Province': ['Cazaji', 'Saurimo'],
  'Malanje Province': ['Malanje'],
  'Moxico Province': ['Léua', 'Luau', 'Luena', 'Lumeje'],
  'Uíge Province': ['Uíge'],
  'Zaire Province': ['Mbanza Congo', "N'zeto", 'Soio'],
};
