export const AZERBAIJAN_REGIONS_CITIES = {
  'Absheron District': [
    'Ceyranbatan',
    'Digah',
    'Gyuzdek',
    'Khirdalan',
    'Qobu',
    'Saray',
  ],
  'Agdam District': ['Ağdam'],
  'Agdash District': ['Ağdaş'],
  'Aghjabadi District': ['Agdzhabedy', 'Avşar'],
  'Agstafa District': ['Aghstafa', 'Saloğlu', 'Vurğun'],
  'Agsu District': ['Aghsu'],
  'Astara District': ['Astara', 'Kizhaba'],
  Baku: [
    'Amirdzhan',
    'Badamdar',
    'Bakıxanov',
    'Baku',
    'Balakhani',
    'Bilajari',
    'Bilajer',
    'Binagadi',
    'Biny Selo',
    'Buzovna',
    'Hövsan',
    'Khodzhi-Gasan',
    'Korgöz',
    'Lökbatan',
    'Mardakan',
    'Maştağa',
    'Nardaran',
    'Nizami Rayonu',
    'Pirallahı',
    'Puta',
    'Qala',
    'Qaraçuxur',
    'Qobustan',
    'Ramana',
    'Sabunçu',
    'Sanqaçal',
    'Türkan',
    'Yeni Suraxanı',
    'Zabrat',
    'Zyrya',
  ],
  'Balakan District': ['Belokany', 'Qabaqçöl'],
  'Barda District': ['Barda', 'Samuxlu'],
  'Beylagan District': [
    'Beylagan',
    'Birinci Aşıqlı',
    'Dünyamalılar',
    'Orjonikidze',
    'Yuxarı Aran',
  ],
  'Bilasuvar District': ['Pushkino'],
  'Dashkasan District': ['Verkhniy Dashkesan', 'Yukhary-Dashkesan'],
  'Fizuli District': ['Fizuli', 'Horadiz'],
  Ganja: ['Ganja'],
  Gədəbəy: [
    'Arıqdam',
    'Arıqıran',
    'Böyük Qaramurad',
    'Kyadabek',
    'Novosaratovka',
  ],
  'Gobustan District': ['Qobustan'],
  'Goranboy District': ['Goranboy', 'Qızılhacılı'],
  Goychay: ['Geoktschai'],
  'Goygol District': ['Yelenendorf'],
  'Hajigabul District': ['Hacıqabul', 'Mughan'],
  'Imishli District': ['Imishli'],
  'Ismailli District': ['Basqal', 'İsmayıllı'],
  'Jabrayil District': ['Jebrail'],
  'Jalilabad District': ['Jalilabad', 'Prishibinskoye'],
  'Kalbajar District': ['Kerbakhiar', 'Vank'],
  'Khachmaz District': ['Xaçmaz', 'Xudat'],
  'Khizi District': ['Altıağac', 'Khyzy', 'Kilyazi', 'Şuraabad'],
  'Khojali District': ['Askyaran', 'Xocalı'],
  'Kurdamir District': ['Kyurdarmir'],
  'Lachin District': ['Laçın'],
  'Lankaran District': ['Haftoni', 'Lankaran'],
  'Lerik District': ['Lerik'],
  Martuni: ['Hadrut', 'Novyy Karanlug', 'Qırmızı Bazar'],
  'Masally District': ['Boradigah', 'Masally'],
  Mingachevir: ['Mingelchaur'],
  'Nakhchivan Autonomous Republic': [
    'Cahri',
    'Çalxanqala',
    'Culfa',
    'Deste',
    'Heydarabad',
    'Julfa Rayon',
    'Nakhchivan',
    'Oğlanqala',
    'Ordubad',
    'Ordubad Rayon',
    'Qıvraq',
    'Şahbuz',
    'Sedarak',
    'Shahbuz Rayon',
    'Sharur City',
    'Sumbatan-diza',
    'Tazakend',
    'Yaycı',
  ],
  'Neftchala District': [
    'Neftçala',
    'Severo-Vostotchnyi Bank',
    'Sovetabad',
    'Xıllı',
  ],
  'Oghuz District': ['Oğuz'],
  'Qabala District': ['Qutqashen'],
  'Qakh District': ['Çinarlı', 'Qax', 'Qax İngiloy', 'Qaxbaş'],
  'Qazakh District': ['Qazax'],
  'Quba District': ['Hacıhüseynli', 'Quba'],
  'Qubadli District': ['Qubadlı'],
  'Qusar District': ['Qusar', 'Samur'],
  'Saatly District': ['Əhmədbəyli', 'Saatlı'],
  'Sabirabad District': ['Sabirabad'],
  'Salyan District': ['Qaraçala', 'Salyan'],
  'Samukh District': ['Qarayeri', 'Qırmızı Samux', 'Samux'],
  'Shabran District': ['Divichibazar'],
  Shaki: ['Sheki'],
  'Shaki District': ['Baş Göynük'],
  'Shamakhi District': ['Shamakhi'],
  'Shamkir District': ['Dolyar', 'Dzagam', 'Qasım İsmayılov', 'Shamkhor'],
  Shirvan: ['Şirvan'],
  'Shusha District': ['Shushi'],
  'Siazan District': ['Gilgilçay', 'Kyzyl-Burun'],
  Sumqayit: ['Corat', 'Hacı Zeynalabdin', 'Sumqayıt'],
  'Tartar District': ['Martakert', 'Terter'],
  'Tovuz District': [
    'Çatax',
    'Çobansığnaq',
    'Dondar Quşçu',
    'Qaraxanlı',
    'Tovuz',
    'Yanıqlı',
  ],
  'Ujar District': ['Ujar'],
  'Yardymli District': ['Yardımlı'],
  Yevlakh: ['Yevlakh'],
  'Yevlakh District': ['Aran', 'Qaramanlı'],
  'Zangilan District': ['Mincivan', 'Zangilan'],
  'Zaqatala District': ['Aliabad', 'Faldarlı', 'Mamrux', 'Qandax', 'Zaqatala'],
  'Zardab District': ['Zardob'],
};
