// export const BARBADOS_PARISHES_TOWNS = {
//   'Christ Church': [
//     'Oistins',
//     'Bridgetown',
//     'Dover',
//     'Miami Beach',
//     'Enterprise',
//   ],
//   'Saint Andrew': [
//     'Bathsheba',
//     'Cave Hill',
//     "St. Andrew's",
//     'Mount Brevitor',
//     'Belleplaine',
//   ],
//   'Saint George': [
//     'Speightstown',
//     'Saint George',
//     'Valley',
//     'Pine Hill',
//     'Red Hill',
//   ],
//   'Saint James': [
//     'Holetown',
//     'Westmoreland',
//     'Fitts Village',
//     'Sandy Lane',
//     'Trents',
//   ],
//   'Saint John': [
//     'Colleton',
//     'Harrison',
//     "Saint John's",
//     'Mount Pleasant',
//     'Walkers',
//   ],
//   'Saint Joseph': [
//     'Grove',
//     'Saint Joseph',
//     'St. Joseph',
//     'Apes Hill',
//     'Coconut Hill',
//   ],
//   'Saint Lucy': [
//     'Six Roads',
//     'Saint Lucy',
//     'Greenidge',
//     'Mullins',
//     'Sandy Lane',
//   ],
//   'Saint Michael': [
//     'Bridgetown',
//     'The City',
//     'Black Rock',
//     'Belleville',
//     "Harrison's",
//   ],
//   'Saint Peter': [
//     'Speightstown',
//     'Saint Peter',
//     'Bambarra',
//     'Mullins Bay',
//     'St. Peter',
//   ],
//   'Saint Thomas': [
//     'Redland',
//     'Saint Thomas',
//     'Paragon',
//     'Pine Hill',
//     'Bush Hall',
//   ],
// };
export const BARBADOS_PARISHES_TOWNS = {
  'Christ Church': ['Oistins'],
  'Saint Andrew': ['Greenland'],
  'Saint James': ['Holetown'],
  'Saint Joseph': ['Bathsheba'],
  'Saint Michael': ['Bridgetown'],
  'Saint Peter': ['Speightstown'],
  'Saint Philip': ['Crane'],
};
