export const BANGLADESH_DIVISIONS_DISTRICTS_CITIES = {
  'Barisal District': [
    'Barguna',
    'Barisal',
    'Bhāndāria',
    'Bhola',
    'Burhānuddin',
    'Gaurnadi',
    'Jhalokati',
    'Lālmohan',
    'Mathba',
    'Mehendiganj',
    'Nālchiti',
    'Patuakhali',
    'Pirojpur',
  ],
  'Chittagong Division': [
    'Bandarban',
    'Bibir Hat',
    'Brahmanbaria',
    'Chandpur',
    'Chhāgalnāiya',
    'Chittagong',
    'Comilla',
    "Cox's Bazar",
    'Cox’s Bāzār',
    'Feni',
    'Hājīganj',
    'Khagrachhari',
    'Lākshām',
    'Lakshmipur',
    'Manikchari',
    'Nabīnagar',
    'Noakhali',
    'Patiya',
    'Rāipur',
    'Rāmganj',
    'Rangamati',
    'Raojān',
    'Sandwīp',
    'Sātkania',
    'Teknāf',
  ],
  'Dhaka District': [
    'Azimpur',
    'Bājitpur',
    'Bhairab Bāzār',
    'Char Bhadrāsan',
    'Char Golora',
    'Dhaka',
    'Dohār',
    'Faridpur',
    'Gazipur',
    'Gopalganj',
    'Joymontop',
    'Khanbaniara',
    'Kishoregonj',
    'Kishorganj',
    'Madaripur',
    'Manikganj',
    'Mirzāpur',
    'Munshiganj',
    'Nāgarpur',
    'Narayanganj',
    'Narsingdi',
    'Pālang',
    'Paltan',
    'Rajbari',
    'Ramnagar',
    'Sakhipur',
    'Sayani',
    'Shariatpur',
    'Sonārgaon',
    'Tangail',
    'Tungi',
    'Tungipāra',
  ],
  'Khulna District': [
    'Bagerhat',
    'Bhātpāra Abhaynagar',
    'Bherāmāra',
    'Chuadanga',
    'Jessore',
    'Jhenaidah',
    'Jhingergācha',
    'Kālia',
    'Kālīganj',
    'Kesabpur',
    'Khulna',
    'Kushtia',
    'Magura',
    'Meherpur',
    'Morrelgonj',
    'Narail',
    'Nowlamary',
    'Phultala',
    'Sarankhola',
    'Satkhira',
    'Ujalpur',
    'Uttar Char Fasson',
  ],
  'Mymensingh District': [
    'Gafargaon',
    'Jamalpur',
    'Muktāgācha',
    'Mymensingh',
    'Netrakona',
    'Sarishābāri',
    'Sherpur',
  ],
  'Rajshahi District': [
    'Bera',
    'Bogra',
    'Chapai Nababganj',
    'Ishurdi',
    'Joypur Hāt',
    'Joypurhat',
    'Mahasthangarh',
    'Naogaon',
    'Natore',
    'Nawābganj',
    'Pabna',
    'Pār Naogaon',
    'Puthia',
    'Rajshahi',
    'Saidpur',
    'Shāhzādpur',
    'Shibganj',
    'Sirajganj',
  ],
  'Rangpur District': [
    'Badarganj',
    'Chilmāri',
    'Dinajpur',
    'Gaibandha',
    'Kurigram',
    'Lalmonirhat',
    'Lalmonirhat District',
    'Nageswari',
    'Nilphamari Zila',
    'Panchagarh',
    'Parbatipur',
    'Pīrgaaj',
    'Rangpur',
    'Thakurgaon',
  ],
  'Sylhet District': [
    'Baniachang',
    'Chhātak',
    'Habiganj',
    'Jahedpur',
    'Maulavi Bāzār',
    'Maulvibazar',
    'Sunamganj',
    'Sylhet',
  ],
};
