export const BURKINA_FASO_STATE_CITY = {
  'Boucle du Mouhoun Region': [
    'Barani',
    'Boromo',
    'Dédougou',
    'Nouna',
    'Province de la Kossi',
    'Province des Balé',
    'Province des Banwa',
    'Province du Mouhoun',
    'Province du Nayala',
    'Province du Sourou',
    'Salanso',
    'Toma',
    'Tougan',
  ],
  'Cascades Region': [
    'Banfora',
    'Province de la Comoé',
    'Province de la Léraba',
    'Sindou',
  ],
  Centre: ['Kadiogo Province', 'Ouagadougou'],
  'Centre-Est Region': [
    'Garango',
    'Koupéla',
    'Kouritenga Province',
    'Ouargaye',
    'Province du Boulgou',
    'Province du Koulpélogo',
    'Tenkodogo',
  ],
  'Centre-Nord Region': [
    'Boulsa',
    'Kaya',
    'Kongoussi',
    'Province du Bam',
    'Province du Namentenga',
    'Province du Sanmatenga',
  ],
  'Centre-Ouest Region': [
    'Goulouré',
    'Kokologo',
    'Koudougou',
    'Léo',
    'Pitmoaga',
    'Province de la Sissili',
    'Province du Boulkiemdé',
    'Province du Sanguié',
    'Province du Ziro',
    'Réo',
    'Sapouy',
  ],
  'Centre-Sud Region': [
    'Bazega Province',
    'Kombissiri',
    'Manga',
    'Nahouri Province',
    'Pô',
    'Zoundweogo Province',
  ],
  'Est Region': [
    'Bogandé',
    'Diapaga',
    "Fada N'gourma",
    'Gayéri',
    'Gnagna Province',
    'Pama',
    'Province de la Komandjoari',
    'Province de la Kompienga',
    'Province de la Tapoa',
    'Province du Gourma',
  ],
  'Hauts-Bassins Region': [
    'Bobo-Dioulasso',
    'Houndé',
    'Province du Houet',
    'Province du Kénédougou',
    'Province du Tuy',
  ],
  'Nord Region, Burkina Faso': [
    'Gourcy',
    'Ouahigouya',
    'Province du Loroum',
    'Province du Passoré',
    'Province du Yatenga',
    'Province du Zondoma',
    'Titao',
    'Yako',
  ],
  'Plateau-Central Region': [
    'Boussé',
    'Oubritenga',
    'Province du Ganzourgou',
    'Province du Kourwéogo',
    'Ziniaré',
    'Zorgo',
  ],
  'Sahel Region': [
    'Djibo',
    'Dori',
    'Gorom-Gorom',
    'Province de l’Oudalan',
    'Province du Séno',
    'Province du Soum',
    'Province du Yagha',
  ],
  'Sud-Ouest Region': [
    'Batié',
    'Dano',
    'Diébougou',
    'Province de la Bougouriba',
    'Province du Ioba',
    'Province du Noumbièl',
    'Province du Poni',
  ],
};
