export const BURUNDI_PROVINCE_COMMUNE = {
  'Bubanza Province': ['Bubanza'],
  'Bujumbura Mairie Province': ['Bujumbura'],
  'Bururi Province': ['Bururi'],
  'Cankuzo Province': ['Cankuzo'],
  'Cibitoke Province': ['Cibitoke'],
  'Gitega Province': ['Gitega'],
  'Karuzi Province': ['Karuzi'],
  'Kayanza Province': ['Kayanza'],
  'Kirundo Province': ['Kirundo'],
  'Makamba Province': ['Makamba'],
  'Muramvya Province': ['Muramvya'],
  'Muyinga Province': ['Muyinga'],
  'Mwaro Province': ['Mwaro'],
  'Ngozi Province': ['Ngozi'],
  'Rumonge Province': ['Rumonge'],
  'Rutana Province': ['Rutana'],
  'Ruyigi Province': ['Ruyigi'],
};
//   {
//   Bujumbura: ['Bujumbura', 'Isare', 'Kabezi', 'Muha'],
//   'Bujumbura Mairie': ['Bujumbura', 'Isale', 'Kamenge', 'Ngagara'],
//   Bubanza: ['Bubanza', 'Bukeye', 'Mpanda', 'Songa'],
//   Bururi: ['Bururi', 'Bugarama', 'Buyengero', 'Gitega'],
//   Cankuzo: ['Cankuzo', 'Gisagara', 'Mishitsi', 'Ruyigi'],
//   Cibitoke: ['Cibitoke', 'Buganda', 'Mabayi', 'Rugombo'],
//   Gitega: ['Gitega', 'Buraza', 'Mbuye', 'Mutaho'],
//   Karuzi: ['Karuzi', 'Gihinga', 'Gitaramuka', 'Muyinga'],
//   Kayanza: ['Kayanza', 'Gahombo', 'Kabarore', 'Muzinda'],
//   Kirundo: ['Kirundo', 'Busoni', 'Vumbi', 'Gitobe'],
//   Makamba: ['Makamba', 'Kibago', 'Kivoga', 'Nyabisindu'],
//   Muramvya: ['Muramvya', 'Bwa', 'Mbuye', 'Nyabikere'],
//   Muyinga: ['Muyinga', 'Gashoho', 'Kantama', 'Nyangungu'],
//   Ngozi: ['Ngozi', 'Kiremba', 'Tanzanie', 'Nyamitanga'],
//   Rutana: ['Rutana', 'Buhimba', 'Giharo', 'Nyaingwe'],
//   Ruyigi: ['Ruyigi', 'Buhoma', 'Gatabo', 'Mugina'],
// };
