export const BENIN_STATE_CITY = {
  'Alibori Department': ['Banikoara', 'Kandi', 'Malanville'],
  'Atakora Department': ['Guilmaro', 'Natitingou', 'Tanguieta'],
  'Atlantique Department': [
    'Abomey-Calavi',
    'Allada',
    'Hévié',
    'Hinvi',
    'Ouidah',
  ],
  'Borgou Department': [
    'Bembèrèkè',
    'Bétérou',
    'Nikki',
    'Parakou',
    'Tchaourou',
  ],
  'Collines Department': ['Comé', 'Dassa-Zoumé', 'Savalou', 'Savé'],
  'Donga Department': ['Bassila', 'Commune of Djougou', 'Djougou'],
  'Kouffo Department': ['Djakotomey', 'Dogbo'],
  'Littoral Department': ['Cotonou'],
  'Mono Department': ['Commune of Athieme', 'Lokossa'],
  'Ouémé Department': ['Porto-Novo'],
  'Plateau Department': ['Kétou', 'Pobé', 'Sakété'],
  'Zou Department': ['Abomey', 'Bohicon', 'Commune of Agbangnizoun', 'Cové'],
};
