export const BOLIVIA_DEPARTMENTS_CITIES = {
  'Beni Department': [
    'Guayaramerín',
    'Provincia Cercado',
    'Provincia General José Ballivián',
    'Provincia Iténez',
    'Provincia Mamoré',
    'Provincia Marbán',
    'Provincia Moxos',
    'Provincia Vaca Diez',
    'Provincia Yacuma',
    'Reyes',
    'Riberalta',
    'Rurrenabaque',
    'San Borja',
    'San Ramón',
    'Santa Ana de Yacuma',
    'Santa Rosa',
    'Trinidad',
  ],
  'Chuquisaca Department': [
    'Camargo',
    'Monteagudo',
    'Padilla',
    'Provincia Azurduy',
    'Provincia Belisario Boeto',
    'Provincia Hernando Siles',
    'Provincia Luis Calvo',
    'Provincia Nor Cinti',
    'Provincia Oropeza',
    'Provincia Sud Cinti',
    'Provincia Tomina',
    'Provincia Yamparáez',
    'Provincia Zudáñez',
    'Sucre',
    'Tarabuco',
  ],
  'Cochabamba Department': [
    'Aiquile',
    'Arani',
    'Bolivar',
    'Capinota',
    'Chimoré',
    'Cliza',
    'Cochabamba',
    'Colchani',
    'Colomi',
    'Independencia',
    'Irpa Irpa',
    'Mizque',
    'Provincia Arani',
    'Provincia Arque',
    'Provincia Ayopaya',
    'Provincia Campero',
    'Provincia Capinota',
    'Provincia Carrasco',
    'Provincia Cercado',
    'Provincia Chaparé',
    'Provincia Esteban Arce',
    'Provincia Germán Jordán',
    'Provincia Mizque',
    'Provincia Punata',
    'Provincia Quillacollo',
    'Provincia Tapacarí',
    'Punata',
    'Quillacollo',
    'Sacaba',
    'Sipe Sipe',
    'Tarata',
    'Tiquipaya',
    'Tiraque Province',
    'Totora',
  ],
  'La Paz Department': [
    'Achacachi',
    'Amarete',
    'Batallas',
    'Caranavi',
    'Chulumani',
    'Colquiri',
    'Coripata',
    'Coroico',
    'Curahuara de Carangas',
    'Eucaliptus',
    'Guanay',
    'Huarina',
    'Huatajata',
    'José Manuel Pando',
    'La Paz',
    'Lahuachaca',
    'Mapiri',
    'Patacamaya',
    'Provincia Aroma',
    'Provincia Bautista Saavedra',
    'Provincia Camacho',
    'Provincia Franz Tamayo',
    'Provincia Gualberto Villarroel',
    'Provincia Ingavi',
    'Provincia Inquisivi',
    'Provincia Iturralde',
    'Provincia Larecaja',
    'Provincia Loayza',
    'Provincia Los Andes',
    'Provincia Manco Kapac',
    'Provincia Muñecas',
    'Provincia Murillo',
    'Provincia Nor Yungas',
    'Provincia Omasuyos',
    'Provincia Pacajes',
    'Provincia Sud Yungas',
    'Quime',
    'San Pablo',
    'San Pedro',
    'Sorata',
    'Tiahuanaco',
    'Viloco',
    'Yumani',
  ],
  'Oruro Department': [
    'Challapata',
    'Huanuni',
    'Litoral de Atacama',
    'Machacamarca',
    'Nor Carangas Province',
    'Oruro',
    'Poopó',
    'Provincia Avaroa',
    'Provincia Carangas',
    'Provincia Cercado',
    'Provincia Ladislao Cabrera',
    'Provincia Pantaleón Dalence',
    'Provincia Poopó',
    'Provincia Sabaya',
    'Provincia Sajama',
    'Provincia San Pedro de Totora',
    'Provincia Saucari',
    'Provincia Tomás Barron',
    'Puerto de Mejillones',
    'Sebastian Pagador Province',
    'Sud Carangas Province',
    'Totoral',
  ],
  'Pando Department': [
    'Cobija',
    'Provincia Abuná',
    'Provincia General Federico Román',
    'Provincia Madre de Dios',
    'Provincia Manuripi',
    'Provincia Nicolás Suárez',
  ],
  'Potosí Department': [
    'Atocha',
    'Betanzos',
    'Colchani',
    'Colquechaca',
    'Enrique Baldivieso',
    'Llallagua',
    'Potosí',
    'Provincia Alonzo de Ibáñez',
    'Provincia Charcas',
    'Provincia Chayanta',
    'Provincia Daniel Campos',
    'Provincia General Bilbao',
    'Provincia Linares',
    'Provincia Modesto Omiste',
    'Provincia Nor Chichas',
    'Provincia Nor Lípez',
    'Provincia Quijarro',
    'Provincia Rafael Bustillo',
    'Provincia Saavedra',
    'Provincia Sud Chichas',
    'Provincia Sud Lípez',
    'Provincia Tomás Frías',
    'Santa Bárbara',
    'Tupiza',
    'Uyuni',
    'Villazón',
  ],
  'Santa Cruz Department': [
    'Abapó',
    'Ascención de Guarayos',
    'Ascensión',
    'Boyuibe',
    'Buena Vista',
    'Camiri',
    'Charagua',
    'Comarapa',
    'Concepción',
    'Cotoca',
    'German Busch',
    'Guarayos',
    'Jorochito',
    'La Bélgica',
    'Limoncito',
    'Los Negros',
    'Mairana',
    'Mineros',
    'Montero',
    'Okinawa Número Uno',
    'Pailón',
    'Paurito',
    'Portachuelo',
    'Provincia Andrés Ibáñez',
    'Provincia Ángel Sandoval',
    'Provincia Chiquitos',
    'Provincia Cordillera',
    'Provincia Florida',
    'Provincia Ichilo',
    'Provincia Manuel María Caballero',
    'Provincia Ñuflo de Chávez',
    'Provincia Santiesteban',
    'Provincia Sara',
    'Provincia Vallegrande',
    'Provincia Velasco',
    'Provincia Warnes',
    'Puerto Quijarro',
    'Puesto de Pailas',
    'Roboré',
    'Samaipata',
    'San Carlos',
    'San Ignacio de Velasco',
    'San Juan del Surutú',
    'San Julian',
    'San Matías',
    'San Pedro',
    'Santa Cruz de la Sierra',
    'Santa Rita',
    'Santa Rosa del Sara',
    'Santiago del Torno',
    'Urubichá',
    'Vallegrande',
    'Villa Yapacaní',
    'Warnes',
  ],
  'Tarija Department': [
    'Bermejo',
    'Entre Ríos',
    'Provincia Arce',
    'Provincia Avilez',
    'Provincia Cercado',
    'Provincia Gran Chaco',
    'Provincia Méndez',
    'Provincia O’Connor',
    'Tarija',
    'Villamontes',
    'Yacuiba',
  ],
};
