export const BRAZIL_STATE_CITY = {
  Acre: ['Rio Branco', 'Cruzeiro do Sul', 'Senador Guiomard', 'Tarauacá'],
  Alagoas: ['Maceió', 'Arapiraca', 'Palmeira dos Índios', 'Penedo'],
  Amapá: ['Macapá', 'Santana', 'Laranjal do Jari', 'Oiapoque'],
  Amazonas: ['Manaus', 'Tabatinga', 'Tefé', 'Itacoatiara'],
  Bahia: ['Salvador', 'Feira de Santana', 'Vitória da Conquista', 'Camaçari'],
  Ceará: ['Fortaleza', 'Caucaia', 'Juazeiro do Norte', 'Sobral'],
  'Distrito Federal': ['Brasília', 'Gama', 'Taguatinga', 'Ceilândia'],
  'Espírito Santo': ['Vitória', 'Vila Velha', 'Serra', 'Cariacica'],
  Goiás: ['Goiânia', 'Aparecida de Goiânia', 'Anápolis', 'Catalão'],
  Maranhão: ['São Luís', 'Imperatriz', 'Caxias', 'Timon'],
  'Mato Grosso': ['Cuiabá', 'Várzea Grande', 'Rondonópolis', 'Sinop'],
  'Mato Grosso do Sul': ['Campo Grande', 'Dourados', 'Três Lagoas', 'Corumbá'],
  'Minas Gerais': ['Belo Horizonte', 'Uberlândia', 'Contagem', 'Juiz de Fora'],
  Pará: ['Belém', 'Ananindeua', 'Santarém', 'Marabá'],
  Paraíba: ['João Pessoa', 'Campina Grande', 'Patos', 'Santa Rita'],
  Paraná: ['Curitiba', 'Londrina', 'Maringá', 'Ponta Grossa'],
  Pernambuco: ['Recife', 'Olinda', 'Jaboatão dos Guararapes', 'Caruaru'],
  Piauí: ['Teresina', 'Parnaíba', 'Picos', 'Floriano'],
  'Rio de Janeiro': [
    'Rio de Janeiro',
    'Niterói',
    'Nova Iguaçu',
    'Duque de Caxias',
  ],
  'Rio Grande do Norte': ['Natal', 'Mossoró', 'Parnamirim', 'Caicó'],
  'Rio Grande do Sul': [
    'Porto Alegre',
    'Caxias do Sul',
    'Pelotas',
    'Santa Maria',
  ],
  Rondônia: ['Porto Velho', 'Ji-Paraná', 'Rolim de Moura', 'Vilhena'],
  Roraima: ['Boa Vista', 'Rorainópolis', 'Caracaraí', 'Cantá'],
  'Santa Catarina': ['Florianópolis', 'Joinville', 'Blumenau', 'Chapecó'],
  'São Paulo': ['São Paulo', 'Campinas', 'Santos', 'São Bernardo do Campo'],
  'São Vicente': ['São Vicente', 'Cubatão', 'Guarujá', 'Praia Grande'],
  Sergipe: ['Aracaju', 'Nossa Senhora do Socorro', 'Lagarto', 'Itabaiana'],
  Tocantins: ['Palmas', 'Araguaína', 'Gurupi', 'Porto Nacional'],
};
