export const BAHAMAS_ISLANDS_SETTLEMENTS = {
  Bimini: ['Alice Town'],
  'Cat Island': ['Arthur’s Town'],
  'Central Abaco': ['Marsh Harbour'],
  'Crooked Island': ['Colonel Hill'],
  'East Grand Bahama': ['High Rock'],
  Exuma: ['George Town'],
  Freeport: ['Freeport', 'Lucaya'],
  'Harbour Island': ['Dunmore Town'],
  Inagua: ['Matthew Town'],
  'Long Island': ['Clarence Town'],
  'Mayaguana District': ['Abraham’s Bay'],
  'New Providence': ['Nassau'],
  'North Abaco': ['Cooper’s Town'],
  'North Andros': ['Andros Town', 'San Andros'],
  'Ragged Island': ['Duncan Town'],
  'Rum Cay District': ['Port Nelson'],
  'San Salvador Island': ['Cockburn Town'],
  'Spanish Wells': ['Spanish Wells'],
  'West Grand Bahama': ['West End'],
};
