// export const BHUTAN_DZONGKHAGS_TOWNS = {
//   Thimphu: ['Thimphu', 'Mothithang', 'Kawang', 'Nabji'],
//   Paro: ['Paro', 'Wangduephodrang', 'Haa', 'Phuentsholing'],
//   Punakha: ['Punakha', 'Lhuntse', 'Wangduephodrang', 'Sangbay'],
//   Chukha: ['Chukha', 'Phuentsholing', 'Gedu', 'Sampheling'],
//   Trashigang: ['Trashigang', 'Wamrong', 'Mongar', 'Kanglung'],
//   Trashiyangtse: ['Trashiyangtse', 'Chazam', 'Bumthang', 'Serthi'],
//   Bumthang: ['Jakar', 'Chumey', 'Tang', 'Ura'],
//   Zhemgang: ['Zhemgang', 'Panbang', 'Buli', 'Jangbi'],
//   Haa: ['Haa', 'Sombaykha', 'Sakteng', 'Daga'],
//   'Samdrup Jongkhar': [
//     'Samdrup Jongkhar',
//     'Nganglam',
//     'Jomotsangkha',
//     'Pangbang',
//   ],
//   Samtee: ['Samtee', 'Daga', 'Samtse', 'Rangthang'],
//   'Wangdue Phodrang': ['Wangdue Phodrang', 'Rukubji', 'Punakha', 'Gangtey'],
//   Lhuntse: ['Lhuntse', 'Khuruthang', 'Nangkor', 'Wangdue Phodrang'],
// };
export const BHUTAN_DZONGKHAGS_TOWNS = {
  'Bumthang District': ['Jakar'],
  'Chukha District': ['Daphu', 'Phuntsholing', 'Tsimasham'],
  'Dagana District': ['Daga', 'Wangdue Phodrang'],
  'Gasa District': ['Gasa'],
  'Haa District': ['Ha'],
  'Lhuntse District': ['Lhuentse'],
  'Mongar District': ['Mongar'],
  'Paro District': ['Paro'],
  'Pemagatshel District': ['Pemagatshel'],
  'Punakha District': ['Pajo', 'Punākha'],
  'Samdrup Jongkhar District': ['Samdrup Jongkhar'],
  'Samtse District': ['Samtse'],
  'Sarpang District': ['Sarpang'],
  'Thimphu District': ['Thimphu'],
  'Trashigang District': ['Trashigang'],
  'Tsirang District': ['Trongsa', 'Tsirang'],
  'Wangdue Phodrang District': ['Trashi Yangtse'],
  'Zhemgang District': ['Panbang', 'Shemgang'],
};
