export const BOTSWANA_STATE_CITY = {
  'Central District': [
    'Gobojango',
    'Gweta',
    'Kalamare',
    'Letlhakane',
    'Letsheng',
    'Maapi',
    'Machaneng',
    'Mahalapye',
    'Makobeng',
    'Makwata',
    'Mathakola',
    'Mathambgwane',
    'Mathathane',
    'Maunatlala',
    'Mogapi',
    'Moijabana',
    'Mookane',
    'Mopipi',
    'Mosetse',
    'Nata',
    'Orapa',
    'Palapye',
    'Pilikwe',
    'Rakops',
    'Ramokgonami',
    'Ratholo',
    'Sefophe',
    'Serowe',
    'Sua',
    'Tamasane',
    'Tobane',
    'Tonota',
  ],
  'Ghanzi District': ['Dekar', 'Ghanzi'],
  'Kgalagadi District': [
    'Hukuntsi',
    'Kang',
    'Lehututu',
    'Manyana',
    'Tshabong',
    'Werda',
  ],
  'Kgatleng District': ['Bokaa', 'Mmathubudukwane', 'Mochudi', 'Pilane'],
  'Kweneng District': [
    'Botlhapatlou',
    'Dutlwe',
    'Gabane',
    'Gaphatshwe',
    'Khudumelapye',
    'Lenchwe Le Tau',
    'Letlhakeng',
    'Metsemotlhaba',
    'Mmopone',
    'Mogoditshane',
    'Molepolole',
    'Nkoyaphiri',
    'Thamaga',
  ],
  'North-East District': ['Dukwe', 'Makaleng', 'Masunga', 'Sebina'],
  'North-West District': [
    'Maun',
    'Nokaneng',
    'Pandamatenga',
    'Sehithwa',
    'Shakawe',
  ],
  'South-East District': ['Gaborone', 'Janeng', 'Kopong', 'Otse', 'Ramotswa'],
  'Southern District': ['Kanye', 'Khakhea', 'Mosopa', 'Sekoma'],
};
