export const DEMOCRATIC_REPUBLIC_OF_CONGO_STATE_CITIES = {
  'Bas-Uélé': ['Aketi', 'Bondo', 'Buta'],
  Équateur: ['Gemena', 'Lisala', 'Lukolela', 'Mbandaka'],
  'Haut-Katanga': [
    'Haut Katanga',
    'Kambove',
    'Kipushi',
    'Likasi',
    'Lubumbashi',
  ],
  'Haut-Lomami': ['Bukama', 'Kamina'],
  'Haut-Uélé': ['Isiro', 'Wamba', 'Watsa'],
  Ituri: ['Bunia'],
  Kasaï: ['Ilebo', 'Luebo', 'Mweka', 'Tshikapa'],
  'Kasaï Oriental': ['Gandajika', 'Kabinda', 'Mbuji-Mayi'],
  Kinshasa: ['Kinshasa', 'Masina'],
  'Kongo Central': [
    'Boma',
    'Kasangulu',
    'Matadi',
    'Mbanza-Ngungu',
    'Moanda',
    'Tshela',
  ],
  Kwango: ['Kasongo-Lunda'],
  Kwilu: ['Bandundu', 'Bulungu', 'Kikwit', 'Mangai'],
  Lomami: ['Lubao', 'Mwene-Ditu'],
  'Mai-Ndombe': ['Bolobo', 'Inongo', 'Mushie', 'Nioki'],
  Maniema: ['Kampene', 'Kasongo', 'Kindu'],
  Mongala: ['Bumba'],
  'Nord-Kivu': ['Beni', 'Butembo', 'Goma', 'Sake'],
  'Nord-Ubangi': ['Bosobolo', 'Businga', 'Gbadolite'],
  Sankuru: ['Lodja', 'Lusambo'],
  'Sud-Kivu': ['Bukavu', 'Kabare', 'Uvira'],
  'Sud-Ubangi': ['Bongandanga', 'Libenge'],
  Tanganyika: ['Kabalo', 'Kalemie', 'Kongolo'],
  Tshopo: ['Basoko', 'Kisangani', 'Yangambi'],
  Tshuapa: ['Boende'],
};
