export const CENTRAL_AFRICAN_REPUBLIC_PROVINCES_CITIES = {
  'Bamingui-Bangoran Prefecture': ['Bamingui', 'Ndélé'],
  Bangui: ['Bangui'],
  'Basse-Kotto Prefecture': ['Alindao', 'Kembé', 'Mobaye'],
  'Haut-Mbomou Prefecture': ['Obo', 'Zemio'],
  'Haute-Kotto Prefecture': ['Bria', 'Ouadda'],
  'Kémo Prefecture': ['Sibut'],
  'Lobaye Prefecture': ['Boda', 'Boganangone', 'Mbaiki', 'Mongoumba'],
  'Mambéré-Kadéï': ['Berberati', 'Carnot', 'Gamboula'],
  'Mbomou Prefecture': ['Bangassou', 'Gambo', 'Ouango', 'Rafai'],
  'Nana-Grébizi Economic Prefecture': ['Kaga Bandoro', 'Kaga-Bandoro'],
  'Nana-Mambéré Prefecture': ['Baoro', 'Bouar'],
  "Ombella-M'Poko Prefecture": ['Bimbo', 'Boali', 'Damara'],
  'Ouaka Prefecture': ['Bambari', 'Grimari', 'Ippy', 'Kouango'],
  'Ouham Prefecture': ['Batangafo', 'Bossangoa', 'Bouca', 'Kabo'],
  'Ouham-Pendé Prefecture': ['Bocaranga', 'Bozoum', 'Paoua'],
  'Sangha-Mbaéré': ['Nola'],
  'Vakaga Prefecture': ['Birao', 'Ouanda-Djallé'],
};
