export const COTE_DIVOIRE_REGIONS_CITIES = {
  Abidjan: ['Abidjan', 'Abobo', 'Anyama', 'Bingerville'],
  'Bas-Sassandra District': [
    'Gbôklé',
    'Nawa',
    'San-Pédro',
    'Sassandra',
    'Tabou',
  ],
  'Comoé District': [
    'Abengourou',
    'Aboisso',
    'Adiaké',
    'Agnibilékrou',
    'Ayamé',
    'Bonoua',
    'Grand-Bassam',
    'Indénié-Djuablin',
    'Sud-Comoé',
  ],
  'Denguélé District': ['Folon', 'Kabadougou', 'Odienné'],
  'Dix-Huit Montagnes': [
    'Bangolo',
    'Biankouma',
    'Cavally',
    'Danané',
    'Duekoué',
    'Guémon',
    'Guiglo',
    'Man',
    'Tonkpi',
    'Toulépleu Gueré',
  ],
  'Gôh-Djiboua District': [
    'Divo',
    'Gagnoa',
    'Gôh',
    'Guibéroua',
    'Lakota',
    'Lôh-Djiboua',
    'Oumé',
  ],
  'Lacs Region': [
    'Arrah',
    'Bélier',
    'Bocanda',
    'Bongouanou',
    'Daoukro',
    'Dimbokro',
    'Iffou',
    'Moronou',
    "N'Zi",
    'Toumodi',
    'Yamoussoukro',
  ],
  'Lagunes region': [
    'Adzopé',
    'Affery',
    'Agboville',
    'Agnéby-Tiassa',
    'Akoupé',
    'Dabou',
    'Grand-Lahou',
    'Grands-Ponts',
    'Tiassalé',
  ],
  'Sassandra-Marahoué District': [
    'Bouaflé',
    'Daloa',
    'Haut-Sassandra',
    'Issia',
    'Marahoué',
    'Vavoua',
    'Zuénoula',
  ],
  'Vallée du Bandama Region': [
    'Béoumi',
    'Botro',
    'Bouaké',
    'Dabakala',
    'Gbêkê',
    'Hambol',
    'Katiola',
    'Sakassou',
  ],
  'Woroba District': [
    'Bafing',
    'Béré',
    'Mankono',
    'Séguéla',
    'Touba',
    'Worodougou',
  ],
  'Zanzan Region': [
    'Bondoukou',
    'Bouna',
    'Bounkani',
    'Gontougo',
    'Sinfra',
    'Tanda',
  ],
};
