export const CAMEROON_STATE_CITY = {
  Adamawa: [
    'Bankim',
    'Banyo',
    'Bélel',
    'Djohong',
    'Kontcha',
    'Mayo-Banyo',
    'Meïganga',
    'Ngaoundéré',
    'Somié',
    'Tibati',
    'Tignère',
    'Vina',
  ],
  Centre: [
    'Akono',
    'Akonolinga',
    'Bafia',
    'Eséka',
    'Essé',
    'Évodoula',
    'Mbalmayo',
    'Mbam-Et-Inoubou',
    'Mbandjok',
    'Mbankomo',
    'Mefou-et-Akono',
    'Mfoundi',
    'Minta',
    'Nanga Eboko',
    'Ndikiniméki',
    'Ngomedzap',
    'Ngoro',
    'Nkoteng',
    'Ntui',
    'Obala',
    'Okoa',
    'Okola',
    'Ombésa',
    'Saa',
    'Yaoundé',
    'Yoko',
  ],
  East: [
    'Abong Mbang',
    'Batouri',
    'Bélabo',
    'Bertoua',
    'Bétaré Oya',
    'Dimako',
    'Doumé',
    'Garoua Boulaï',
    'Mbang',
    'Ndelele',
    'Yokadouma',
  ],
  'Far North': [
    'Bogo',
    'Kaélé',
    'Kousséri',
    'Koza',
    'Makary',
    'Maroua',
    'Mayo-Sava',
    'Mayo-Tsanaga',
    'Mindif',
    'Mokolo',
    'Mora',
    'Yagoua',
  ],
  Littoral: [
    'Bonabéri',
    'Diang',
    'Dibombari',
    'Dizangué',
    'Douala',
    'Edéa',
    'Loum',
    'Manjo',
    'Mbanga',
    'Melong',
    'Mouanko',
    'Ndom',
    'Ngambé',
    'Nkongsamba',
    'Penja',
    'Yabassi',
  ],
  North: [
    'Faro Department',
    'Garoua',
    'Guider',
    'Lagdo',
    'Mayo-Louti',
    'Mayo-Rey',
    'Pitoa',
    'Poli',
    'Rey Bouba',
    'Tcholliré',
  ],
  Northwest: [
    'Babanki',
    'Bali',
    'Bamenda',
    'Batibo',
    'Belo',
    'Boyo',
    'Fundong',
    'Jakiri',
    'Kumbo',
    'Mbengwi',
    'Mme-Bafumen',
    'Njinikom',
    'Wum',
  ],
  South: [
    'Akom II',
    'Ambam',
    'Ébolowa',
    'Kribi',
    'Lolodorf',
    'Mvangué',
    'Mvila',
    'Sangmélima',
  ],
  Southwest: [
    'Bamusso',
    'Bekondo',
    'Buea',
    'Fako Division',
    'Fontem',
    'Kumba',
    'Lebialem',
    'Limbe',
    'Mamfe',
    'Mundemba',
    'Mutengene',
    'Muyuka',
    'Nguti',
    'Tiko',
  ],
  West: [
    'Bafang',
    'Bafoussam',
    'Bamendjou',
    'Bana',
    'Bandjoun',
    'Bangangté',
    'Bansoa',
    'Bazou',
    'Dschang',
    'Foumban',
    'Foumbot',
    'Hauts-Plateaux',
    'Koung-Khi',
    'Mbouda',
    'Ngou',
    'Noun',
    'Tonga',
  ],
};
