export const COLOMBIA_DEPARTMENTS = {
  Amazonas: ['Leticia'],
  Antioquia: [
    'Medellín',
    'Bello',
    'Itagüí',
    'Envigado',
    'Turbo',
    'Rionegro',
    'Apartadó',
    'Sabanalarga',
    'Sabaneta',
    'Copacabana',
    'La Estrella',
  ],
  'Arauca ': ['Arauca '],
  'Atlántico ': ['Barranquilla', 'Soledad', 'Malambo'],
  Bogotá: ['Bogotá'],
  Bolívar: ['Cartagena', 'Magangué', 'Turbaco'],
  Boyacá: ['Tunja', 'Duitama', 'Sogamoso'],
  Caldas: ['Manizales'],
  Caquetá: ['Florencia'],
  Casanare: ['Yopal'],
  Cauca: ['Timbío', 'Popayán', 'Santander de Quilichao'],
  Cesar: ['Valledupar', 'Aguachica', 'La Jagua de Ibirico'],
  Chocó: ['Quibdó'],
  Córdoba: ['Montería'],
  Cundinamarca: [
    'Soacha',
    'Zipaquirá',
    'Fusagasugá',
    'Girardot',
    'Mosquera',
    'Facatativá',
    'Madrid',
    'Chía',
    'Funza',
    'Cajicá',
  ],
  Guainía: ['Inírida'],
  Guaviare: ['San José del Guaviare'],
  Huila: ['Palermo', 'Neiva', 'Pitalito'],
  'La Guajira': ['Uripa', 'Ríohacha', 'Maicao', 'Uribia'],
  Magdalena: ['Santa Marta', 'Ciénaga'],
  Meta: ['Villavicencio'],
  Nariño: ['Pasto', 'Tumaco', 'Ipiales'],
  'Norte de Santander': ['PasCúcutato'],
  Putumayo: ['Mocoa'],
  Quindío: ['Armenia'],
  Risaralda: ['Pereira', 'Dosquebradas', 'La Virginia'],
  'San Andrés y Providencia': ['San Andrés'],
  Santander: [
    'Bucaramanga',
    'Floridablanca',
    'Barrancabermeja',
    'Girón',
    'Piedecuesta    ',
  ],
  Sucre: ['Sincelejo'],
  Tolima: ['Ibagué'],
  'Valle del Cauca': [
    'Cali',
    'Buenaventura',
    'Palmira',
    'Zarzal',
    'Tuluá',
    'Cartago',
    'Guadalajara de Buga',
  ],
  Vaupés: ['Mitú'],
  Vichada: ['Puerto Carreño'],
};
