export const CAPE_VERDE_ISLANDS = {
  'Boa Vista': ['Sal Rei'],
  Brava: ['Nova Sintra'],
  'Maio Municipality': ['Vila do Maio'],
  Mosteiros: ['Igreja'],
  Paul: ['Pombas'],
  'Porto Novo': ['Porto Novo'],
  Praia: ['Praia'],
  'Ribeira Brava Municipality': ['Ribeira Brava'],
  'Ribeira Grande': ['Ponta do Sol', 'Ribeira Grande'],
  'Ribeira Grande de Santiago': ['Cidade Velha'],
  Sal: ['Espargos', 'Santa Maria'],
  'Santa Catarina': ['Assomada'],
  'Santa Catarina do Fogo': ['Cova Figueira'],
  'Santa Cruz': ['Pedra Badejo', 'Santa Cruz'],
  'São Domingos': ['São Domingos'],
  'São Filipe': ['São Filipe'],
  'São Lourenço dos Órgãos': ['João Teves'],
  'São Miguel': ['Calheta'],
  'São Vicente': ['Mindelo'],
  Tarrafal: ['Tarrafal'],
  'Tarrafal de São Nicolau': ['Tarrafal de São Nicolau'],
};
