export const CYPRUS_DISTRICTS_CITIES = {
  'Famagusta District (Mağusa)': [
    'Acherítou',
    'Áchna',
    'Ammochostos Municipality',
    'Avgórou',
    'Ayia Napa',
    'Derýneia',
    'Famagusta',
    'Frénaros',
    'Lefkónoiko',
    'Leonárisso',
    'Liopétri',
    'Paralímni',
    'Protaras',
    'Rizokárpaso',
    'Tríkomo',
  ],
  'Kyrenia District (Keryneia)': [
    'Kyrenia',
    'Kyrenia Municipality',
    'Lápithos',
  ],
  'Larnaca District (Larnaka)': [
    'Aradíppou',
    'Athíenou',
    'Dhromolaxia',
    'Kíti',
    'Kofínou',
    'Kolossi',
    'Kórnos',
    'Larnaca',
    'Livádia',
    'Meneou',
    'Mosfilotí',
    'Pérgamos',
    'Perivólia',
    'Psevdás',
    'Pýla',
    'Tersefánou',
    'Troúlloi',
    'Voróklini',
    'Xylofágou',
    'Xylotymbou',
  ],
  'Limassol District (Leymasun)': [
    'Ágios Tomás',
    'Ágios Týchon',
    'Erími',
    'Germasógeia',
    'Kyperoúnta',
    'Lemesós',
    'Limassol',
    'Mouttagiáka',
    'Páchna',
    'Páno Polemídia',
    'Parekklisha',
    'Peléndri',
    'Pissoúri',
    'Pyrgos',
    'Sotíra',
    'Soúni-Zanakiá',
    'Ýpsonas',
  ],
  'Nicosia District (Lefkoşa)': [
    'Akáki',
    'Alámpra',
    'Aredioú',
    'Astromerítis',
    'Dáli',
    'Ergátes',
    'Géri',
    'Kakopetriá',
    'Káto Defterá',
    'Káto Pýrgos',
    'Klírou',
    'Kokkinotrimithiá',
    'Léfka',
    'Lýmpia',
    'Lythrodóntas',
    'Mámmari',
    'Méniko',
    'Mórfou',
    'Nicosia',
    'Nicosia Municipality',
    'Páno Defterá',
    'Péra',
    'Peristeróna',
    'Psimolofou',
    'Tséri',
  ],
  'Paphos District (Pafos)': [
    'Argáka',
    'Chlórakas',
    'Emba',
    'Geroskipou',
    'Geroskípou (quarter)',
    'Geroskípou Municipality',
    'Kissonerga',
    'Koloni',
    'Konia',
    'Mesógi',
    'Paphos',
    'Pégeia',
    'Pólis',
    'Tála',
    'Tsáda',
  ],
};
