export const DOMINICAN_REPUBLIC_PROVINCES_CITIES = {
  'Azua Province': [
    'Azua',
    'El Guayabal',
    'Estebanía',
    'Las Charcas',
    'Padre Las Casas',
    'Palmar de Ocoa',
    'Peralta',
    'Pueblo Viejo',
    'Sabana Yegua',
    'Tábara Arriba',
    'Villarpando',
    'Yayas de Viajama',
  ],
  'Baoruco Province': [
    'El Palmar',
    'Galván',
    'La Uvilla',
    'Los Ríos',
    'Neiba',
    'Tamayo',
    'Villa Jaragua',
  ],
  'Barahona Province': [
    'Cabral',
    'Cachón',
    'Canoa',
    'El Peñón',
    'Enriquillo',
    'Fundación',
    'Jaquimeyes',
    'La Ciénaga',
    'Las Salinas',
    'Paraíso',
    'Pescadería',
    'Polo',
    'Santa Cruz de Barahona',
    'Vicente Noble',
  ],
  'Dajabón Province': [
    'Dajabón',
    'El Pino',
    'Loma de Cabrera',
    'Partido',
    'Restauración',
  ],
  'Distrito Nacional': [
    'Bella Vista',
    'Ciudad Nueva',
    'Cristo Rey',
    'Ensanche Luperón',
    'La Agustina',
    'La Julia',
    'San Carlos',
    'Santo Domingo',
    'Villa Consuelo',
    'Villa Francisca',
  ],
  'Duarte Province': [
    'Agua Santa del Yuna',
    'Arenoso',
    'Castillo',
    'Hostos',
    'Las Guáranas',
    'Pimentel',
    'San Francisco de Macorís',
    'Villa Riva',
  ],
  'El Seibo Province': ['Miches', 'Pedro Sánchez', 'Santa Cruz de El Seibo'],
  'Espaillat Province': [
    'Cayetano Germosén',
    'Gaspar Hernández',
    'Jamao al Norte',
    'Joba Arriba',
    'Juan López Abajo',
    'Moca',
    'San Víctor Arriba',
    'Veragua Arriba',
  ],
  'Hato Mayor Province': [
    'El Valle',
    'Guayabo Dulce',
    'Hato Mayor del Rey',
    'Sabana de la Mar',
  ],
  'Hermanas Mirabal Province': [
    'Salcedo',
    'Salsipuedes',
    'Tenares',
    'Villa Tapia',
  ],
  Independencia: [
    'Cristóbal',
    'Duvergé',
    'Guayabal',
    'Jimaní',
    'La Descubierta',
    'Mella',
    'Postrer Río',
  ],
  'La Altagracia Province': [
    'Boca de Yuma',
    'Higüey',
    'Otra Banda',
    'Punta Cana',
    'Salvaleón de Higüey',
    'San Rafael del Yuma',
  ],
  'La Romana Province': ['Guaymate', 'La Romana'],
  'La Vega Province': [
    'Concepción de La Vega',
    'Constanza',
    'Jarabacoa',
    'Jima Abajo',
    'Rincón',
    'Río Verde Arriba',
    'Tireo Arriba',
  ],
  'María Trinidad Sánchez Province': [
    'Arroyo Salado',
    'Cabrera',
    'El Factor',
    'La Entrada',
    'Nagua',
    'Río San Juan',
  ],
  'Monseñor Nouel Province': [
    'Bonao',
    'Juan Adrián',
    'Maimón',
    'Piedra Blanca',
    'Sabana del Puerto',
  ],
  'Monte Cristi Province': [
    'Cana Chapetón',
    'Castañuelas',
    'Guayubín',
    'Hatillo Palma',
    'Las Matas de Santa Cruz',
    'Monte Cristi',
    'Pepillo Salcedo',
    'San Fernando de Monte Cristi',
    'Villa Elisa',
    'Villa Vásquez',
  ],
  'Monte Plata Province': [
    'Bayaguana',
    'Don Juan',
    'Esperalvillo',
    'Gonzalo',
    'Los Botados',
    'Majagual',
    'Monte Plata',
    'Sabana Grande de Boyá',
    'Yamasá',
  ],
  'Pedernales Province': ['Juancho', 'Oviedo', 'Pedernales'],
  'Peravia Province': [
    'Baní',
    'Matanzas',
    'Nizao',
    'Paya',
    'Pizarrete',
    'Sabana Buey',
  ],
  'Puerto Plata Province': [
    'Altamira',
    'Cabarete',
    'Estero Hondo',
    'Guananico',
    'Imbert',
    'Los Hidalgos',
    'Luperón',
    'Monte Llano',
    'Puerto Plata',
    'Río Grande',
    'Sosúa',
    'Villa Isabela',
  ],
  'Samaná Province': ['Las Terrenas', 'Samaná', 'Sánchez'],
  'San Cristóbal Province': [
    'Bajos de Haina',
    'Cambita Garabitos',
    'El Cacao',
    'El Carril',
    'Sabana Grande de Palenque',
    'San Cristóbal',
    'San Gregorio de Nigua',
    'Villa Altagracia',
    'Yaguate',
  ],
  'San José de Ocoa Province': ['San José de Ocoa'],
  'San Juan Province': [
    'Bohechío',
    'Cercado Abajo',
    'El Cercado',
    'Juan de Herrera',
    'Las Matas de Farfán',
    'Matayaya',
    'Pedro Corto',
    'San Juan de la Maguana',
    'Vallejuelo',
  ],
  'San Pedro de Macorís': [
    'El Puerto',
    'Los Llanos',
    'Quisqueya',
    'Ramón Santana',
    'San Pedro de Macorís',
  ],
  'Sánchez Ramírez Province': ['Cevicos', 'Cotuí', 'Fantino'],
  'Santiago Province': [
    'Baitoa',
    'Bisonó',
    'Juncalito Abajo',
    'La Canela',
    'Licey al Medio',
    'Palmar Arriba',
    'Pedro García',
    'Sabana Iglesia',
    'San José de Las Matas',
    'Santiago de los Caballeros',
    'Santo Tomás de Jánico',
    'Tamboril',
    'Villa Bisonó',
    'Villa González',
  ],
  'Santiago Rodríguez Province': [
    'Monción',
    'Sabaneta',
    'San Ignacio de Sabaneta',
  ],
  'Santo Domingo Province': [
    'Boca Chica',
    'Santo Domingo Este',
    'Santo Domingo Oeste',
  ],
  'Valverde Province': [
    'Amina',
    'Esperanza',
    'Guatapanal',
    'Jaibón',
    'Jicomé',
    'La Caya',
    'Laguna Salada',
    'Maizal',
    'Mao',
  ],
};
// {
//   'Distrito Nacional': [
//     'Santo Domingo',
//     'Gazcue',
//     'Ciudad Colonial',
//     'Ensanche Naco',
//     'Los Prados',
//   ],
//   Azua: [
//     'Azua de Compostela',
//     'Sabana Yegua',
//     'Estebanía',
//     'Los Jovillos',
//     'Palmar de Ocoa',
//   ],
//   Baoruco: ['Neiba', 'La Ciénaga', 'Tamayo', 'El Peñón', 'Las Salinas'],
//   Barahona: [
//     'Barahona',
//     'Santa Cruz de Barahona',
//     'Cabral',
//     'Paraíso',
//     'El Peñón',
//   ],
//   Dajabón: [
//     'Dajabón',
//     'Loma de Cabrera',
//     'Juan Sánchez Ramírez',
//     'El Limón',
//     'La Peguera',
//   ],
//   Duarte: [
//     'San Francisco de Macorís',
//     'Villa Riva',
//     'Pimentel',
//     'Castillo',
//     'Cayetano Germosén',
//   ],
//   'Elías Piña': [
//     'Comendador',
//     'Hondo Valle',
//     'El Llano',
//     'Bánica',
//     'Pedro Santana',
//   ],
//   'El Seibo': ['El Seibo', 'Santa Cruz de El Seibo', 'Miches', 'Polo', 'Yuma'],
//   Espaillat: ['Moca', 'Gaspar Hernández', 'Jamao al Norte', 'Cotuí', 'Moca'],
//   'Hato Mayor': [
//     'Hato Mayor del Rey',
//     'El Valle',
//     'Sabana de la Mar',
//     'La Vega',
//     'Yamasá',
//   ],
//   'La Altagracia': ['Higuey', 'La Altagracia', 'Bávaro', 'Verón', 'Miches'],
//   'La Romana': [
//     'La Romana',
//     'Villa Hermosa',
//     'San Rafael del Yuma',
//     'Catuano',
//     'Guaymate',
//   ],
//   'La Vega': [
//     'La Vega',
//     'Constanza',
//     'Jarabacoa',
//     'Río Verde',
//     'San José de Ocoa',
//   ],
//   'Monseñor Nouel': ['Bonao', 'Maimón', 'Sabana del Puerto', 'Cotui', 'Bonao'],
//   'Monte Cristi': [
//     'Monte Cristi',
//     'Guayubin',
//     'Castañuelas',
//     'Dajabón',
//     'Villa Vásquez',
//   ],
//   'Monte Plata': [
//     'Monte Plata',
//     'Bajos de Haina',
//     'Sabana Grande de Boyá',
//     'Yamasá',
//     'El Naranjo',
//   ],
//   Pedernales: ['Pedernales', 'Jimaní', 'Masa', 'Mao', 'Los Cacaos'],
//   Peravia: ['Baní', 'Nizao', 'Paya', 'Los Mameyes', 'Santa Cruz'],
//   'Puerto Plata': [
//     'Puerto Plata',
//     'Sosúa',
//     'Cabarete',
//     'Altos de Chavón',
//     'Maimón',
//   ],
//   Samaná: [
//     'Samaná',
//     'Las Terrenas',
//     'Las Galeras',
//     'El Limón',
//     'Santa Bárbara',
//   ],
//   'San Cristóbal': [
//     'San Cristóbal',
//     'Los Bajos',
//     'Haina',
//     'San Gregorio',
//     'Los Alcarrizos',
//   ],
//   'San José de Ocoa': [
//     'San José de Ocoa',
//     'Sabana Larga',
//     'Los Cacaos',
//     'Nizao',
//     'La Ciénaga',
//   ],
//   'San Juan': [
//     'San Juan de la Maguana',
//     'Las Matas de Farfán',
//     'El Cercado',
//     'Bohechío',
//     'San Juan',
//   ],
//   'San Pedro de Macorís': [
//     'San Pedro de Macorís',
//     'La Romana',
//     'Guaymate',
//     'San José de los Llanos',
//     'Yamasá',
//   ],
//   'Sánchez Ramírez': [
//     'Cotuí',
//     'Maimón',
//     'Fantino',
//     'La Vega',
//     'Sabana de la Mar',
//   ],
//   Santiago: ['Santiago', 'Licey al Medio', 'Tamboril', 'Navarrete', 'Puñal'],
//   'Santiago Rodríguez': [
//     'San Ignacio de Sabaneta',
//     'Castañuelas',
//     'Montecristi',
//     'Sabaneta',
//     'Santiago Rodríguez',
//   ],
//   Valverde: ['Mao', 'Esperanza', 'Monción', 'Jaibón', 'Valverde'],
// };
