export const ALGERIA_WILAYAS_CITIES = {
  Adrar: ['Adrar', 'Aoulef', 'Reggane', 'Timimoun'],
  'Aïn Defla': [
    'Aïn Defla',
    'El Abadia',
    'El Attaf',
    'Khemis Miliana',
    'Theniet el Had',
  ],
  'Aïn Témouchent': [
    'Aïn Temouchent',
    'Beni Saf',
    'El Amria',
    'El Malah',
    'Hammam Bou Hadjar',
  ],
  Algiers: [
    'Aïn Taya',
    'Algiers',
    'Bab Ezzouar',
    'Birkhadem',
    'Bordj el Kiffan',
    'Dar el Beïda',
    'Rouiba',
  ],
  Annaba: ['Annaba', 'Berrahal', 'Drean', 'El Hadjar'],
  Batna: [
    'Aïn Touta',
    'Arris',
    'Barika',
    'Batna',
    'Boumagueur',
    'Merouana',
    'Râs el Aïoun',
    'Tazoult-Lambese',
  ],
  Béchar: ['Béchar'],
  Béjaïa: [
    'Akbou',
    'Amizour',
    'Barbacha',
    'Bejaïa',
    'el hed',
    'El Kseur',
    'Feraoun',
    'Seddouk',
  ],
  Biskra: [
    'Biskra',
    'Oumache',
    'Sidi Khaled',
    'Sidi Okba',
    'Tolga',
    'Zeribet el Oued',
  ],
  Blida: [
    'Beni Mered',
    'Blida',
    'Boû Arfa',
    'Boufarik',
    'Bougara',
    'Bouinan',
    'Chebli',
    'Chiffa',
    'Larbaâ',
    'Meftah',
    'Sidi Moussa',
    'Souma',
  ],
  'Bordj Bou Arréridj': [
    'Bordj Bou Arreridj',
    'Bordj Ghdir',
    'Bordj Zemoura',
    'El Achir',
    'Mansourah',
    'Melouza',
    'Râs el Oued',
  ],
  Bouïra: [
    'Aïn Bessem',
    'Bouïra',
    'Chorfa',
    'Draa el Mizan',
    'Lakhdaria',
    'Sour el Ghozlane',
  ],
  Boumerdès: [
    'Arbatache',
    'Beni Amrane',
    'Boudouaou',
    'Boumerdas',
    'Chabet el Ameur',
    'Dellys',
    'Khemis el Khechna',
    'Makouda',
    'Naciria',
    'Ouled Moussa',
    'Reghaïa',
    'Tadmaït',
    'Thenia',
    'Tizi Gheniff',
  ],
  Chlef: [
    'Abou el Hassan',
    'Boukadir',
    'Chlef',
    'Ech Chettia',
    'Oued Fodda',
    'Oued Sly',
    'Sidi Akkacha',
  ],
  Constantine: [
    '’Aïn Abid',
    'Aïn Smara',
    'Constantine',
    'Didouche Mourad',
    'El Khroub',
    'Hamma Bouziane',
  ],
  Djelfa: [
    '’Aïn el Bell',
    'Aïn Oussera',
    'Birine',
    'Charef',
    'Dar Chioukh',
    'Djelfa',
    'El Idrissia',
    'Messaad',
  ],
  'El Bayadh': ['Brezina', 'El Abiodh Sidi Cheikh', 'El Bayadh'],
  'El Oued': ['Debila', 'El Oued', 'Reguiba', 'Robbah'],
  'El Tarf': ['Ben Mehidi', 'Besbes', 'El Kala', 'El Tarf'],
  Ghardaïa: ['Berriane', 'Ghardaïa', 'Metlili Chaamba'],
  Guelma: ['Boumahra Ahmed', 'Guelma', 'Héliopolis'],
  Illizi: ['Illizi'],
  Jijel: ['Jijel'],
  Khenchela: ['Khenchela'],
  Laghouat: ['Aflou', 'Laghouat'],
  "M'Sila": ['‘Aïn el Hadjel', '’Aïn el Melh', 'M’Sila', 'Sidi Aïssa'],
  Mascara: ['Bou Hanifia el Hamamat', 'Mascara', 'Oued el Abtal', 'Sig'],
  Médéa: ['’Aïn Boucif', 'Berrouaghia', 'Ksar el Boukhari', 'Médéa'],
  Mila: ['Chelghoum el Aïd', 'Mila', 'Rouached', 'Sidi Mérouane', 'Telerghma'],
  Mostaganem: ['Mostaganem'],
  Naama: ['Aïn Sefra', 'Naama'],
  Oran: [
    '’Aïn el Turk',
    'Aïn el Bya',
    'Bir el Djir',
    'Bou Tlelis',
    'Es Senia',
    'Mers el Kebir',
    'Oran',
    'Sidi ech Chahmi',
  ],
  Ouargla: [
    'Djamaa',
    'El Hadjira',
    'Hassi Messaoud',
    'Megarine',
    'Ouargla',
    'Rouissat',
    'Sidi Amrane',
    'Tebesbest',
    'Touggourt',
  ],
  'Oum El Bouaghi': [
    'Aïn Beïda',
    'Aïn Fakroun',
    'Aïn Kercha',
    'El Aouinet',
    'Meskiana',
    'Oum el Bouaghi',
  ],
  Relizane: [
    '’Aïn Merane',
    'Ammi Moussa',
    'Djidiouia',
    'Mazouna',
    'Oued Rhiou',
    'Relizane',
    'Smala',
    'Zemoura',
  ],
  Saïda: ['’Aïn el Hadjar', 'Saïda'],
  Sétif: [
    'Aïn Arnat',
    'BABOR - VILLE',
    'Bougaa',
    'El Eulma',
    'Salah Bey',
    'Sétif',
  ],
  'Sidi Bel Abbès': [
    'Aïn El Berd District',
    'Balidat Ameur',
    'Belarbi',
    'Ben Badis Sid Bel Abbés',
    'Djamaa',
    'El Bour',
    'El Hadjira',
    'Haoud El Hamra',
    'Hassi Messaoud',
    'Lamtar',
    'Marhoum',
    'Megarine',
    'Merine',
    'Mezaourou',
    'Moggar',
    'Moulay Slissen',
    "N'Goussa",
    'Ouargla',
    'Rouissat',
    'Sfissef',
    'Sidi Ali Boussidi',
    'Sidi Amrane',
    'Sidi Bel Abbès',
    'Sidi Brahim',
    'Sidi Hamadouche',
    'Sidi Slimane',
    'Sidi Yacoub',
    'Sidi Yahia',
    'Tabia Sid Bel Abbés',
    'Taibet',
    'Tamellaht',
    'Tamerna Djedida',
    'Tebesbest',
    'Teghalimet',
    'Telagh',
    'Tenezara',
    'Tenira',
    'Tessala',
    'Touggourt',
    'Zerouala',
  ],
  Skikda: ['Azzaba', 'Karkira', 'Skikda', 'Tamalous'],
  'Souk Ahras': ['Sedrata', 'Souk Ahras'],
  Tamanghasset: ['I-n-Salah', 'Tamanrasset'],
  Tébessa: ['Bir el Ater', 'Cheria', 'Hammamet', 'Tébessa'],
  Tiaret: [
    '’Aïn Deheb',
    'Djebilet Rosfa',
    'Frenda',
    'Ksar Chellala',
    'Mehdia daira de meghila',
    'Sougueur',
    'Tiaret',
  ],
  Tindouf: ['Tindouf'],
  Tipasa: [
    '’Aïn Benian',
    'Baraki',
    'Bou Ismaïl',
    'Cheraga',
    'Douera',
    'El Affroun',
    'Hadjout',
    'Kolea',
    'Mouzaïa',
    'Oued el Alleug',
    'Saoula',
    'Tipasa',
    'Zeralda',
  ],
  Tissemsilt: ['Lardjem', 'Tissemsilt'],
  'Tizi Ouzou': [
    '’Aïn el Hammam',
    'Arhribs',
    'Azazga',
    'Beni Douala',
    'Boghni',
    'Boudjima',
    'Chemini',
    'Draa Ben Khedda',
    'Freha',
    'Ighram',
    'L’Arbaa Naït Irathen',
    'Mekla',
    'Timizart',
    'Tirmitine',
    'Tizi Ouzou',
    'Tizi Rached',
    'Tizi-n-Tleta',
  ],
  Tlemcen: [
    'Beni Mester',
    'Bensekrane',
    'Chetouane',
    'Hennaya',
    'Mansoûra',
    'Nedroma',
    'Ouled Mimoun',
    'Remchi',
    'Sebdou',
    'Sidi Abdelli',
    'Sidi Senoussi سيدي سنوسي',
    'Tlemcen',
  ],
};
