export const ECUADOR_PROVINCES_CITIES = {
  Azuay: [
    'Cantón San Fernando',
    'Cuenca',
    'Gualaceo',
    'La Unión',
    'Llacao',
    'Nulti',
  ],
  Bolívar: ['Guaranda', 'San Miguel'],
  Cañar: ['Azogues', 'Cañar', 'La Troncal'],
  Carchi: ['El Ángel', 'San Gabriel', 'Tulcán'],
  Chimborazo: ['Alausí', 'Guano', 'Riobamba'],
  Cotopaxi: [
    'La Maná',
    'Latacunga',
    'Pujilí',
    'San Miguel de Salcedo',
    'Saquisilí',
  ],
  'El Oro': [
    'Huaquillas',
    'Machala',
    'Pasaje',
    'Piñas',
    'Portovelo',
    'Puerto Bolívar',
    'Santa Rosa',
    'Zaruma',
  ],
  Esmeraldas: [
    'Esmeraldas',
    'Muisne',
    'Pampanal de Bolívar',
    'Rio Verde',
    'Rosa Zarate',
    'San Lorenzo de Esmeraldas',
    'Valdez',
  ],
  Galápagos: ['Puerto Ayora', 'Puerto Baquerizo Moreno', 'Puerto Villamil'],
  Guayas: [
    'Alfredo Baquerizo Moreno',
    'Baláo',
    'Balzar',
    'Colimes',
    'Coronel Marcelino Maridueña',
    'El Triunfo',
    'Eloy Alfaro',
    'Guayaquil',
    'Lomas de Sargentillo',
    'Milagro',
    'Naranjal',
    'Naranjito',
    'Palestina',
    'Pedro Carbo',
    'Playas',
    'Samborondón',
    'Santa Lucía',
    'Velasco Ibarra',
    'Yaguachi Nuevo',
  ],
  Imbabura: ['Atuntaqui', 'Cotacachi', 'Ibarra', 'Otavalo', 'Pimampiro'],
  Loja: ['Loja'],
  'Los Ríos': [
    'Babahoyo',
    'Catarama',
    'Montalvo',
    'Palenque',
    'Quevedo',
    'Ventanas',
    'Vinces',
  ],
  Manabí: [
    'Bahía de Caráquez',
    'Calceta',
    'Cantón Portoviejo',
    'Chone',
    'Jipijapa',
    'Junín',
    'Manta',
    'Montecristi',
    'Paján',
    'Pedernales',
    'Portoviejo',
    'Rocafuerte',
    'San Vicente',
    'Santa Ana',
    'Sucre',
    'Tosagua',
  ],
  'Morona-Santiago': ['Gualaquiza', 'Macas', 'Palora', 'Sucúa'],
  Napo: ['Archidona', 'Tena'],
  Orellana: [
    'Boca Suno',
    'Francisco de Orellana Canton',
    'Loreto Canton',
    'Puerto Francisco de Orellana',
  ],
  Pastaza: ['Puyo'],
  Pichincha: ['Cayambe', 'Machachi', 'Quito', 'Sangolquí', 'Tutamandahostel'],
  'Santa Elena': ['La Libertad', 'Salinas', 'Santa Elena'],
  'Santo Domingo de los Tsáchilas': ['Santo Domingo de los Colorados'],
  Sucumbíos: ['Nueva Loja'],
  Tungurahua: ['Ambato', 'Baños', 'Pelileo', 'Píllaro'],
  'Zamora Chinchipe': ['Yantzaza', 'Zamora'],
};
