export const ESTONIA_COUNTIES_CITIES = {
  'Harju County': [
    'Anija vald',
    'Aruküla',
    'Haabneeme',
    'Harku',
    'Harku vald',
    'Jõelähtme vald',
    'Jüri',
    'Kehra',
    'Keila',
    'Kiili',
    'Kiili vald',
    'Kose',
    'Kuusalu',
    'Laagri',
    'Loksa',
    'Loksa linn',
    'Loo',
    'Maardu',
    'Maardu linn',
    'Paldiski',
    'Pringi',
    'Raasiku',
    'Rae vald',
    'Riisipere',
    'Rummu',
    'Saku',
    'Saku vald',
    'Saue',
    'Saue vald',
    'Tabasalu',
    'Tallinn',
    'Turba',
    'Vaida',
    'Viimsi',
    'Viimsi vald',
  ],
  'Hiiu County': ['Kärdla'],
  'Ida-Viru County': [
    'Iisaku',
    'Jõhvi',
    'Jõhvi vald',
    'Kiviõli',
    'Kohtla-Järve',
    'Kohtla-Nõmme',
    'Lüganuse vald',
    'Narva',
    'Narva-Jõesuu',
    'Narva-Jõesuu linn',
    'Püssi',
    'Sillamäe',
    'Toila',
    'Voka',
  ],
  'Järva County': [
    'Järva-Jaani',
    'Koeru',
    'Paide',
    'Paide linn',
    'Särevere',
    'Türi',
    'Türi vald',
  ],
  'Jõgeva County': [
    'Jõgeva',
    'Jõgeva vald',
    'Mustvee',
    'Põltsamaa',
    'Põltsamaa vald',
  ],
  'Lääne County': [
    'Haapsalu',
    'Haapsalu linn',
    'Hullo',
    'Lääne-Nigula vald',
    'Taebla',
    'Uuemõisa',
    'Vormsi vald',
  ],
  'Lääne-Viru County': [
    'Aseri',
    'Haljala',
    'Haljala vald',
    'Kadrina',
    'Kadrina vald',
    'Kunda',
    'Pajusti',
    'Rakke',
    'Rakvere',
    'Rakvere vald',
    'Sõmeru',
    'Tamsalu',
    'Tapa',
    'Tapa vald',
    'Vaiatu',
    'Väike-Maarja',
    'Väike-Maarja vald',
    'Vinni',
    'Vinni vald',
    'Viru-Nigula vald',
  ],
  'Pärnu County': [
    'Audru',
    'Kihnu vald',
    'Kilingi-Nõmme',
    'Lihula',
    'Linaküla',
    'Paikuse',
    'Pärnu',
    'Pärnu linn',
    'Pärnu-Jaagupi',
    'Saarde vald',
    'Sauga',
    'Sindi',
    'Tootsi',
    'Tori vald',
    'Uulu',
    'Vändra',
  ],
  'Põlva County': [
    'Kanepi',
    'Kanepi vald',
    'Põlva',
    'Põlva vald',
    'Räpina',
    'Räpina vald',
  ],
  'Rapla County': [
    'Järvakandi',
    'Kehtna',
    'Kehtna vald',
    'Kohila',
    'Kohila vald',
    'Märjamaa',
    'Märjamaa vald',
    'Rapla',
    'Rapla vald',
  ],
  'Saare County': [
    'Kuressaare',
    'Liiva',
    'Muhu vald',
    'Orissaare',
    'Ruhnu',
    'Ruhnu vald',
    'Tehumardi',
  ],
  'Tartu County': [
    'Alatskivi',
    'Elva',
    'Kallaste',
    'Kambja vald',
    'Kõrveküla',
    'Kurepalu',
    'Luunja',
    'Luunja vald',
    'Nõo',
    'Nõo vald',
    'Peipsiääre vald',
    'Puhja',
    'Tartu',
    'Tartu linn',
    'Tartu vald',
    'Ülenurme',
  ],
  'Valga County': ['Otepää vald', 'Tõrva', 'Valga'],
  'Viljandi County': [
    'Abja-Paluoja',
    'Karksi-Nuia',
    'Mõisaküla',
    'Suure-Jaani',
    'Viiratsi',
    'Viljandi',
    'Viljandi vald',
    'Võhma',
  ],
  'Võru County': [
    'Antsla',
    'Antsla vald',
    'Rõuge',
    'Rõuge vald',
    'Vana-Antsla',
    'Värska',
    'Võru',
    'Võru vald',
  ],
};
