export const EGYPT_STATE_CITY = {
  Alexandria: [
    'Abu Qir',
    'Agami',
    'Alexandria',
    'Ar-Raml',
    'Borg El Arab',
    'Montaza',
    'New Borg El Arab',
    'Sidi Bishr',
  ],
  Aswan: ['Abu Simbel', 'Aswan', 'Idfū', 'Kawm Umbū'],
  Asyut: [
    'Abnūb',
    'Abū Tīj',
    'Al Badārī',
    'Al Qūşīyah',
    'Asyūţ',
    'Dayrūţ',
    'Manfalūţ',
  ],
  Beheira: [
    'Abū al Maţāmīr',
    'Ad Dilinjāt',
    'Damanhūr',
    'Ḩawsh ‘Īsá',
    'Idkū',
    'Kafr ad Dawwār',
    'Kawm Ḩamādah',
    'Rosetta',
  ],
  'Beni Suef': ['Al Fashn', 'Banī Suwayf', 'Būsh', 'Sumusţā as Sulţānī'],
  Cairo: [
    'Badr',
    'Bulaq',
    'Cairo',
    'El Mataria',
    'Fustat',
    'Hadayek El Kobba',
    'Heliopolis',
    'Helwan',
    'Maadi',
    'Musturud',
    'New Administrative Capital of Egypt',
    'Shubra',
    'Tura',
  ],
  Dakahlia: [
    '‘Izbat al Burj',
    'Ajā',
    'Al Jammālīyah',
    'Al Manşūrah',
    'Al Manzalah',
    'Al Maţarīyah',
    'Bilqās',
    'Dikirnis',
    'Minyat an Naşr',
    'Shirbīn',
    'Ţalkhā',
  ],
  Damietta: ['Az Zarqā', 'Damietta', 'Fāraskūr'],
  Faiyum: ['Al Fayyūm', 'Al Wāsiţah', 'Ibshawāy', 'Iţsā', 'Ţāmiyah'],
  Gharbia: [
    'Al Maḩallah al Kubrá',
    'Basyūn',
    'Kafr az Zayyāt',
    'Quţūr',
    'Samannūd',
    'Tanda',
    'Zefta',
  ],
  Giza: [
    'Al ‘Ayyāţ',
    'Al Bawīţī',
    'Al Ḩawāmidīyah',
    'Aş Şaff',
    'Awsīm',
    'Giza',
    'Madīnat Sittah Uktūbar',
  ],
  Ismailia: ['Ismailia'],
  'Kafr el-Sheikh': [
    'Al Ḩāmūl',
    'Disūq',
    'Fuwwah',
    'Kafr ash Shaykh',
    'Markaz Disūq',
    'Munshāt ‘Alī Āghā',
    'Sīdī Sālim',
  ],
  Luxor: ['Luxor', 'Markaz al Uqşur'],
  Matrouh: ['Al ‘Alamayn', 'Mersa Matruh', 'Siwa Oasis'],
  Minya: [
    'Abū Qurqāş',
    'Al Minyā',
    'Banī Mazār',
    'Dayr Mawās',
    'Mallawī',
    'Maţāy',
    'Samālūţ',
  ],
  Monufia: [
    'Al Bājūr',
    'Ash Shuhadā’',
    'Ashmūn',
    'Munūf',
    'Quwaysinā',
    'Shibīn al Kawm',
    'Talā',
  ],
  'New Valley': ['Al Khārijah', 'Qaşr al Farāfirah'],
  'North Sinai': ['Arish'],
  'Port Said': ['Port Said'],
  Qalyubia: [
    'Al Khānkah',
    'Al Qanāţir al Khayrīyah',
    'Banhā',
    'Qalyūb',
    'Shibīn al Qanāṭir',
    'Toukh',
  ],
  Qena: ['Dishnā', 'Farshūţ', 'Isnā', 'Kousa', "Naja' Ḥammādī", 'Qinā'],
  'Red Sea': [
    'Al Quşayr',
    'El Gouna',
    'Hurghada',
    'Makadi Bay',
    'Marsa Alam',
    'Ras Gharib',
    'Safaga',
  ],
  Sharqia: [
    '10th of Ramadan',
    'Al Qurein',
    'Awlad Saqr',
    'Bilbeis',
    'Diyarb Negm',
    'El Husseiniya',
    'Faqous',
    'Hihya',
    'Kafr Saqr',
    'Markaz Abū Ḩammād',
    'Mashtoul El Souk',
    'Minya El Qamh',
    'New Salhia',
    'Zagazig',
  ],
  Sohag: [
    'Akhmīm',
    'Al Balyanā',
    'Al Manshāh',
    'Jirjā',
    'Juhaynah',
    'Markaz Jirjā',
    'Markaz Sūhāj',
    'Sohag',
    'Ţahţā',
  ],
  'South Sinai': [
    'Dahab',
    'El-Tor',
    'Nuwaybi‘a',
    'Saint Catherine',
    'Sharm el-Sheikh',
  ],
  Suez: ['Ain Sukhna', 'Suez'],
};
