export const ETHIOPIA_STATE_CITY = {
  'Addis Ababa': ['Addis Ababa'],
  'Afar Region': [
    'Administrative Zone 2',
    'Administrative Zone 3',
    'Asaita',
    'Āwash',
    'Dubti',
    'Gewanē',
    'Semera',
  ],
  'Amhara Region': [
    'Abomsa',
    'Addiet Canna',
    'Ādīs Zemen',
    'Bahir Dar',
    'Batī',
    'Bichena',
    'Burē',
    'Dabat',
    'Debark’',
    'Debre Birhan',
    'Debre Mark’os',
    'Debre Sīna',
    'Debre Tabor',
    'Debre Werk’',
    'Dejen',
    'Desē',
    'Finote Selam',
    'Gondar',
    'Kemisē',
    'Kombolcha',
    'Lalībela',
    'North Shewa Zone',
    'North Wollo Zone',
    'Robīt',
    'South Gondar Zone',
    'South Wollo Zone',
    'Wag Hemra Zone',
    'Were Īlu',
    'Werota',
  ],
  'Benishangul-Gumuz Region': ['Asosa', 'Metekel'],
  'Dire Dawa': ['Dire Dawa'],
  'Gambela Region': ['Administrative Zone 1', 'Gambēla'],
  'Harari Region': ['Harar'],
  'Oromia Region': [
    'Ādīs ‘Alem',
    'Āgaro',
    'Arsi Zone',
    'Āsasa',
    'Āsbe Teferī',
    'Bedelē',
    'Bedēsa',
    'Bishoftu',
    'Deder',
    'Dembī Dolo',
    'Dodola',
    'East Harerghe Zone',
    'East Shewa Zone',
    'East Wellega Zone',
    'Fichē',
    'Gebre Guracha',
    'Gēdo',
    'Gelemso',
    'Genet',
    'Gimbi',
    'Ginir',
    'Goba',
    'Gorē',
    'Guji Zone',
    'Hāgere Hiywet',
    'Hagere Maryam',
    'Hīrna',
    'Huruta',
    'Illubabor Zone',
    'Jimma',
    'Jimma Zone',
    'Kibre Mengist',
    'Kofelē',
    'Mēga',
    'Mendī',
    'Metahāra',
    'Metu',
    'Mojo',
    'Nazrēt',
    'Nejo',
    'North Shewa Zone',
    'Sebeta',
    'Sendafa',
    'Shakiso',
    'Shambu',
    'Shashemenē',
    'Sirre',
    'Tulu Bolo',
    'Waliso',
    'Wenjī',
    'West Harerghe Zone',
    'West Wellega Zone',
    'Yabēlo',
    'Ziway',
  ],
  'Somali Region': [
    'Afder Zone',
    'Degehabur Zone',
    'Gode Zone',
    'Jijiga',
    'Liben zone',
    'Shinile Zone',
  ],
  "Southern Nations, Nationalities, and Peoples' Region": [
    'Alaba Special Wereda',
    'Arba Minch',
    'Āreka',
    'Bako',
    'Bench Maji Zone',
    'Bodītī',
    'Bonga',
    'Butajīra',
    'Dīla',
    'Felege Neway',
    'Gedeo Zone',
    'Gīdolē',
    'Guraghe Zone',
    'Hadiya Zone',
    'Hāgere Selam',
    'Hawassa',
    'Hosa’ina',
    'Jinka',
    'K’olīto',
    'Kembata Alaba Tembaro Zone',
    'Konso',
    'Leku',
    'Lobuni',
    'Mīzan Teferī',
    'Sheka Zone',
    'Sidama Zone',
    'Sodo',
    'Tippi',
    'Turmi',
    'Wendo',
    'Wolayita Zone',
    'Yem',
    'Yirga ‘Alem',
  ],
  'Tigray Region': [
    'Ādīgrat',
    'Axum',
    'Inda Silasē',
    'Korem',
    'Maych’ew',
    "Mek'ele",
    'Southeastern Tigray Zone',
    'Southern Tigray Zone',
  ],
};
