export const GEORGIA_COUNTIES_CITIES = {
  Abkhazia: [
    'Bich’vinta',
    'Dranda',
    'Gagra',
    'Gali',
    'Gantiadi',
    'Gudauta',
    'Kelasuri',
    'Och’amch’ire',
    'P’rimorsk’oe',
    'Sokhumi',
    'Stantsiya Novyy Afon',
    "Tqvarch'eli",
  ],
  Adjara: [
    'Akhaldaba',
    'Batumi',
    'Chakvi',
    'Dioknisi',
    'Khelvachauri',
    'Khulo',
    'Kobuleti',
    'Makhinjauri',
    'Ochkhamuri',
    'Shuakhevi',
    'Tsikhisdziri',
  ],
  Guria: ['Lanchkhuti', 'Naruja', 'Ozurgeti', 'Urek’i'],
  Imereti: [
    'Baghdatis Munitsip’alit’et’i',
    'Chiat’ura',
    'K’alak’i Chiat’ura',
    'K’ulashi',
    'Kharagauli',
    'Khoni',
    'Kutaisi',
    'Sach’khere',
    'Samtredia',
    'Shorapani',
    'Tqibuli',
    'Tsqaltubo',
    'Vani',
    'Zestap’oni',
  ],
  Kakheti: [
    'Akhmet’a',
    'Akhmet’is Munitsip’alit’et’i',
    'Gurjaani',
    'Lagodekhi',
    'Qvareli',
    'Sagarejo',
    'Sighnaghi',
    'Sighnaghis Munitsip’alit’et’i',
    'Telavi',
    'Tsinandali',
    'Tsnori',
  ],
  'Kvemo Kartli': [
    'Bolnisi',
    'Bolnisis Munitsip’alit’et’i',
    'Didi Lilo',
    'Dmanisis Munitsip’alit’et’i',
    'Gardabani',
    'Gardabnis Munitsip’alit’et’i',
    'Manglisi',
    'Marneuli',
    'Marneulis Munitsip’alit’et’i',
    'Naghvarevi',
    'Rust’avi',
    'T’et’ri Tsqaro',
    'Tetrits’q’alos Munitsip’alit’et’i',
    'Ts’alk’is Munitsip’alit’et’i',
    'Tsalka',
  ],
  'Mtskheta-Mtianeti': [
    'Akhalgori',
    'Dzegvi',
    'Gudauri',
    'Java',
    'Mtskheta',
    'P’asanauri',
    'Step’antsminda',
    'Zhinvali',
  ],
  'Racha-Lechkhumi and Kvemo Svaneti': [
    'Ambrolauri',
    'Ambrolauris Munitsip’alit’et’i',
    'Lent’ekhi',
    'Oni',
  ],
  'Samegrelo-Zemo Svaneti': [
    'Abasha',
    'Jvari',
    'Khobi',
    'Kveda Chkhorots’q’u',
    'Mart’vili',
    'Mest’ia',
    'Mest’iis Munitsip’alit’et’i',
    'Orsant’ia',
    'P’ot’i',
    'Senak’i',
    'Tsalenjikha',
    'Zugdidi',
  ],
  'Samtskhe-Javakheti': [
    'Adigeni',
    'Adigeni Municipality',
    'Akhaldaba',
    'Akhalk’alak’i',
    'Akhaltsikhe',
    'Akhaltsikhis Munitsip’alit’et’i',
    'Asp’indzis Munitsip’alit’et’i',
    'Aspindza',
    'Bakuriani',
    'Borjomi',
    'Ninotsminda',
    'Tsaghveri',
    'Vale',
  ],
  'Shida Kartli': [
    'Agara',
    'Gori',
    'Goris Munitsip’alit’et’i',
    'Kaspi',
    'Khashuri',
    'Surami',
    'Ts’khinvali',
  ],
  Tbilisi: ['Tbilisi'],
};
