export const GHANA_REGIONS_CITIES = {
  Ahafo: [
    'Asunafo North',
    'Asunafo South',
    'Asutifi North',
    'Asutifi South',
    'Tano North',
    'Tano South',
  ],
  Ashanti: [
    'Agogo',
    'Bekwai',
    'Ejura',
    'Konongo',
    'Kumasi',
    'Mampong',
    'Obuase',
    'Tafo',
  ],
  Bono: [
    'Banda',
    'Berekum East',
    'Berekum West',
    'Dormaa Central',
    'Dormaa East',
    'Dormaa West',
    'Jaman North',
    'Jaman South',
    'Sunyani',
    'Sunyani West',
    'Tain',
    'Wenchi',
  ],
  'Bono East': [
    'Atebubu-Amantin',
    'Kintampo North',
    'Kintampo South',
    'Nkoranza North',
    'Nkoranza South',
    'Pru East',
    'Pru West',
    'Sene East',
    'Sene West',
    'Techiman',
    'Techiman North',
  ],
  Central: [
    'Apam',
    'Cape Coast',
    'Dunkwa',
    'Elmina',
    'Foso',
    'Kasoa',
    'Mumford',
    'Saltpond',
    'Swedru',
    'Winneba',
  ],
  Eastern: [
    'Aburi',
    'Akim Oda',
    'Akim Swedru',
    'Akropong',
    'Akwatia',
    'Asamankese',
    'Begoro',
    'Kibi',
    'Koforidua',
    'Mpraeso',
    'Nsawam',
    'Suhum',
  ],
  'Greater Accra': [
    'Accra',
    'Atsiaman',
    'Dome',
    'Gbawe',
    'Medina Estates',
    'Nungua',
    'Tema',
    'Teshi Old Town',
  ],
  'North East': [
    'Bunkpurugu-Nyakpanduri',
    'Chereponi',
    'East Mamprusi',
    'Mamprugu-Moagduri',
    'West Mamprusi',
    'Yunyoo-Nasuan',
  ],
  Northern: ['Kpandae', 'Salaga', 'Savelugu', 'Tamale', 'Yendi'],
  Oti: [
    'Biakoye',
    'Jasikan',
    'Kadjebi',
    'Krachi East',
    'Krachi Nchumuru',
    'Krachi West',
    'Nkwanta North',
    'Nkwanta South',
  ],
  Savannah: [
    'Bole',
    'Central Gonja',
    'East Gonja',
    'North East Gonja',
    'North Gonja',
    'Sawla-Tuna-Kalba',
    'West Gonja',
  ],
  'Upper East': ['Bawku', 'Bolgatanga', 'Navrongo'],
  'Upper West': ['Wa'],
  Volta: ['Aflao', 'Anloga', 'Ho', 'Hohoe', 'Keta', 'Kete Krachi', 'Kpandu'],
  Western: [
    'Aboso',
    'Axim',
    'Bibiani',
    'Prestea',
    'Sekondi-Takoradi',
    'Shama Junction',
    'Takoradi',
    'Tarkwa',
  ],
  'Western North': [
    'Aowin',
    'Bia East',
    'Bia West',
    'Bibiani-Anhwiaso-Bekwai',
    'Bodi',
    'Juaboso',
    'Sefwi-Akontombra',
    'Sefwi-Wiawso',
    'Suaman',
  ],
};
