export const GAMBIA_REGIONS_CITIES = {
  Banjul: ['Bakau', 'Banjul', 'Kombo Saint Mary District', 'Serekunda'],
  'Central River Division': [
    'Bansang',
    'Brikama Nding',
    'Dankunku',
    'Denton',
    'Fulladu West',
    'Galleh Manda',
    'Georgetown',
    'Jakhaly',
    'Janjanbureh',
    'Jarreng',
    'Karantaba',
    'Kass Wollof',
    'Kuntaur',
    'Kunting',
    'Lower Saloum',
    'Niamina East District',
    'Niamina West District',
    'Niani',
    'Nianija District',
    'Pateh Sam',
    'Sami',
    'Sami District',
    'Saruja',
    'Sukuta',
    'Upper Saloum',
    'Wassu',
  ],
  'Lower River Division': [
    'Baro Kunda',
    'Bureng',
    'Jali',
    'Jarra Central',
    'Jarra East',
    'Jarra West',
    'Jenoi',
    'Jifarong',
    'Kaiaf',
    'Karantaba',
    'Keneba',
    'Kiang Central',
    'Kiang East',
    'Kiang West District',
    'Mansa Konko',
    'Nioro',
    'Sankwia',
    'Si Kunda',
    'Soma',
    'Sutukung',
    'Toniataba',
    'Wellingara Ba',
  ],
  'North Bank Division': [
    'Bambali',
    'Barra',
    'Central Baddibu',
    'Chilla',
    'Daru Rilwan',
    'Essau',
    'Farafenni',
    'Gunjur',
    'Jokadu',
    'Katchang',
    'Kerewan',
    'Lamin',
    'Lower Baddibu District',
    'Lower Niumi District',
    'No Kunda',
    'Saba',
    'Sara Kunda',
    'Upper Baddibu',
    'Upper Niumi District',
  ],
  'Upper River Division': [
    'Bakadagy',
    'Basse Santa Su',
    'Brifu',
    'Daba Kunda',
    'Demba Kunda',
    'Diabugu',
    'Diabugu Basilla',
    'Fulladu East',
    'Gunjur Kuta',
    'Kantora',
    'Koina',
    'Kumbija',
    'Nyamanari',
    'Perai',
    'Sabi',
    'Sandu',
    'Sudowol',
    'Sun Kunda',
    'Sutukoba',
    'Wuli',
  ],
  'West Coast Division': [
    'Abuko',
    'Brikama',
    'Foni Bondali',
    'Foni Brefet',
    'Foni Jarrol',
    'Foni Kansala',
    'Gunjur',
    'Kombo Central District',
    'Kombo East District',
    'Kombo North District',
    'Kombo South District',
    'Somita',
    'Sukuta',
  ],
};
