export const GUINEA_REGIONS_CITIES = {
  'Boké Region': [
    'Boffa',
    'Boké',
    'Boke Prefecture',
    'Fria',
    'Gaoual',
    'Gaoual Prefecture',
    'Kimbo',
    'Koundara',
    'Koundara Prefecture',
    'Sanguéya',
    'Youkounkoun',
  ],
  Conakry: ['Camayenne', 'Conakry'],
  'Kankan Region': [
    'Kankan',
    'Kankan Prefecture',
    'Kérouané',
    'Kerouane Prefecture',
    'Kouroussa',
    'Mandiana',
    'Mandiana Prefecture',
    'Siguiri',
    'Siguiri Prefecture',
    'Tokonou',
  ],
  'Kindia Region': [
    'Coyah',
    'Dubréka',
    'Forécariah',
    'Kindia',
    'Préfecture de Dubréka',
    'Préfecture de Forécariah',
    'Télimélé',
    'Telimele Prefecture',
    'Tondon',
  ],
  'Labé Region': [
    'Koubia',
    'Labé',
    'Labe Prefecture',
    'Lélouma',
    'Lelouma Prefecture',
    'Mali',
    'Mali Prefecture',
    'Tougué',
    'Tougue Prefecture',
  ],
  'Mamou Region': ['Dalaba', 'Mamou', 'Mamou Prefecture', 'Pita'],
  'Nzérékoré Region': [
    'Beyla',
    'Beyla Prefecture',
    'Gueckedou',
    'Lola',
    'Macenta',
    'Nzérékoré',
    'Nzerekore Prefecture',
    'Préfecture de Guékédou',
    'Yomou',
  ],
};
