export const HONG_KONG_STATE_CITY = {
  'Central and Western': ['Admiralty', 'Central'],
  Islands: ['Tai O'],
  'Kowloon City': ['Kowloon Tong'],
  'Kwun Tong': ['Kwun Tong', 'Lam Tin'],
  North: ['Sheung Shui'],
  'Sai Kung': ['Sai Kung', 'Tseung Kwan O'],
  'Sha Tin': ['Ma On Shan', 'Sha Tin', 'Sha Tin Wai'],
  'Sham Shui Po': ['Cheung Sha Wan', 'Lai Chi Kok'],
  Southern: ['Aberdeen', 'Stanley', 'Stanley Peninsula'],
  'Tai Po': ['Tai Mei Tuk', 'Tai Po'],
  'Tsuen Wan': ['Tsuen Wan', 'Tuen Mun\t'],
  'Wan Chai': ['Causeway Bay', 'Wan Chai'],
  'Wong Tai Sin': ['Wong Tai Sin'],
  'Yau Tsim Mong': ['Mong Kok', 'Tsim Sha Tsui'],
  'Yuen Long': ['Yuen Long'],
};
