export const CROATIA_COUNTIES_CITIES = {
  'Bjelovar-Bilogora': [
    'Bjelovar',
    'Brezovac',
    'Čazma',
    'Daruvar',
    'Dežanovac',
    'Đulovac',
    'Garešnica',
    'Grad Bjelovar',
    'Grad Čazma',
    'Grad Daruvar',
    'Grad Garešnica',
    'Grad Grubišno Polje',
    'Grubišno Polje',
    'Gudovac',
    'Hercegovac',
    'Ivanska',
    'Kapela',
    'Končanica',
    'Predavac',
    'Rovišće',
    'Šandrovac',
    'Severin',
    'Sirač',
    'Velika Pisanica',
    'Veliki Grđevac',
    'Ždralovi',
    'Zrinski Topolovac',
  ],
  'Brod-Posavina': [
    'Batrina',
    'Brodski Varoš',
    'Bukovlje',
    'Cernik',
    'Davor',
    'Donji Andrijevci',
    'Garčin',
    'Gornji Bogićevci',
    'Grad Nova Gradiška',
    'Grad Slavonski Brod',
    'Gundinci',
    'Korenica',
    'Kruševica',
    'Lužani',
    'Nova Gradiška',
    'Okučani',
    'Oprisavci',
    'Oriovac',
    'Podvinje',
    'Rešetari',
    'Ruščica',
    'Sibinj',
    'Sikirevci',
    'Slavonski Brod',
    'Slobodnica',
    'Stari Perkovci',
    'Velika Kopanica',
    'Vrpolje',
  ],
  'Dubrovnik-Neretva': [
    'Cavtat',
    'Čibača',
    'Dubrovačko primorje',
    'Grad Dubrovnik',
    'Grad Korčula',
    'Grad Ploče',
    'Komin',
    'Konavle',
    'Korčula',
    'Lastovo',
    'Lumbarda',
    'Metković',
    'Mljet',
    'Mokošica',
    'Općina Lastovo',
    'Opuzen',
    'Orebić',
    'Podgora',
    'Pojezerje',
    'Slivno',
    'Smokvica',
    'Ston',
    'Vela Luka',
    'Zažablje',
    'Žrnovo',
    'Župa dubrovačka',
  ],
  Istria: [
    'Bale',
    'Bale-Valle',
    'Brtonigla',
    'Brtonigla-Verteneglio',
    'Buje',
    'Buje-Buie',
    'Buzet',
    'Fažana',
    'Fažana-Fasana',
    'Funtana',
    'Funtana-Fontane',
    'Galižana',
    'Grad Buzet',
    'Grad Labin',
    'Grad Pazin',
    'Grožnjan',
    'Grožnjan-Grisignana',
    'Kanfanar',
    'Karojba',
    'Kaštelir-Labinci',
    'Labin',
    'Ližnjan',
    'Ližnjan-Lisignano',
    'Lupoglav',
    'Marčana',
    'Medulin',
    'Motovun',
    'Motovun-Montona',
    'Novigrad',
    'Novigrad-Cittanova',
    'Općina Lanišće',
    'Oprtalj-Portole',
    'Pazin',
    'Poreč',
    'Poreč-Parenzo',
    'Pula',
    'Pula-Pola',
    'Rabac',
    'Raša',
    'Rovinj',
    'Rovinj-Rovigno',
    'Sveta Nedelja',
    'Sveti Lovreč',
    'Tar',
    'Tar-Vabriga-Torre Abrega',
    'Umag',
    'Umag-Umago',
    'Valbandon',
    'Vinež',
    'Višnjan-Visignano',
    'Vižinada-Visinada',
    'Vodnjan',
    'Vodnjan-Dignano',
    'Vrsar',
    'Vrsar-Orsera',
    'Žminj',
  ],
  'Koprivnica-Križevci': [
    'Drnje',
    'Đelekovec',
    'Đurđevac',
    'Ferdinandovac',
    'Gola',
    'Gornja Rijeka',
    'Grad Koprivnica',
    'Grad Križevci',
    'Hlebine',
    'Kalinovac',
    'Koprivnica',
    'Koprivnički Ivanec',
    'Križevci',
    'Legrad',
    'Molve',
    'Novo Virje',
    'Peteranec',
    'Rasinja',
    'Reka',
    'Sigetec',
    'Virje',
  ],
  'Krapina-Zagorje': [
    'Bedekovčina',
    'Budinščina',
    'Đurmanec',
    'Grad Donja Stubica',
    'Grad Klanjec',
    'Grad Krapina',
    'Grad Zabok',
    'Grad Zlatar',
    'Jesenje',
    'Klanjec',
    'Konjščina',
    'Krapina',
    'Kumrovec',
    'Mače',
    'Marija Bistrica',
    'Mihovljan',
    'Oroslavje',
    'Pregrada',
    'Radoboj',
    'Stubičke Toplice',
    'Sveti Križ Začretje',
    'Zabok',
    'Zlatar',
    'Zlatar Bistrica',
  ],
  'Lika-Senj': [
    'Brinje',
    'Gospić',
    'Karlobag',
    'Lički Osik',
    'Novalja',
    'Otočac',
    'Perušić',
    'Plitvička Jezera',
    'Popovača',
    'Senj',
  ],
  Međimurje: [
    'Belica',
    'Čakovec',
    'Dekanovec',
    'Domašinec',
    'Goričan',
    'Grad Čakovec',
    'Hodošan',
    'Ivanovec',
    'Kotoriba',
    'Kuršanec',
    'Lopatinec',
    'Mačkovec',
    'Mala Subotica',
    'Mihovljan',
    'Mursko Središće',
    'Nedelišće',
    'Novo Selo Rok',
    'Orehovica',
    'Peklenica',
    'Podturen',
    'Prelog',
    'Pribislavec',
    'Šenkovec',
    'Strahoninec',
    'Sveti Juraj na Bregu',
    'Vratišinec',
  ],
  'Osijek-Baranja': [
    'Antunovac',
    'Beli Manastir',
    'Belišće',
    'Bijelo Brdo',
    'Bilje',
    'Bistrinci',
    'Bizovac',
    'Brijest',
    'Budrovci',
    'Čeminac',
    'Čepin',
    'Dalj',
    'Darda',
    'Donji Miholjac',
    'Draž',
    'Đakovo',
    'Đurđenovac',
    'Erdut',
    'Ernestinovo',
    'Feričanci',
    'Gorjani',
    'Grad Beli Manastir',
    'Grad Donji Miholjac',
    'Grad Našice',
    'Grad Osijek',
    'Grad Valpovo',
    'Jagodnjak',
    'Jelisavac',
    'Josipovac',
    'Karanac',
    'Kneževi Vinogradi',
    'Koška',
    'Kuševac',
    'Ladimirevci',
    'Laslovo',
    'Magadenovac',
    'Marijanci',
    'Marjanci',
    'Markovac Našički',
    'Martin',
    'Našice',
    'Osijek',
    'Petlovac',
    'Petrijevci',
    'Piškorevci',
    'Podgorač',
    'Podravska Moslavina',
    'Sarvaš',
    'Satnica Đakovačka',
    'Semeljci',
    'Široko Polje',
    'Šodolovci',
    'Strizivojna',
    'Tenja',
    'Valpovo',
    'Velimirovac',
    'Viljevo',
    'Viškovci',
    'Višnjevac',
    'Vladislavci',
    'Vuka',
  ],
  'Požega-Slavonia': [
    'Brestovac',
    'Grad Pakrac',
    'Grad Požega',
    'Jakšić',
    'Kaptol',
    'Kutjevo',
    'Lipik',
    'Pakrac',
    'Pleternica',
    'Požega',
    'Velika',
    'Vidovci',
  ],
  'Primorje-Gorski Kotar': [
    'Bakar',
    'Banjol',
    'Baška',
    'Bribir',
    'Buzdohanj',
    'Čavle',
    'Cernik',
    'Cres',
    'Crikvenica',
    'Delnice',
    'Dražice',
    'Drenova',
    'Fužine',
    'Grad Čabar',
    'Grad Crikvenica',
    'Grad Delnice',
    'Grad Krk',
    'Grad Opatija',
    'Grad Rijeka',
    'Grad Vrbovsko',
    'Hreljin',
    'Jadranovo',
    'Kampor',
    'Kastav',
    'Klana',
    'Kraljevica',
    'Krasica',
    'Krk',
    'Lopar',
    'Lovran',
    'Mali Lošinj',
    'Malinska-Dubašnica',
    'Marčelji',
    'Marinići',
    'Matulji',
    'Mihotići',
    'Mrkopalj',
    'Njivice',
    'Novi Vinodolski',
    'Omišalj',
    'Opatija',
    'Podhum',
    'Punat',
    'Rab',
    'Rijeka',
    'Rubeši',
    'Selce',
    'Skrad',
    'Škrljevo',
    'Supetarska Draga',
    'Vinodolska općina',
    'Viškovo',
    'Vrbnik',
    'Vrbovsko',
  ],
  'Šibenik-Knin': [
    'Brodarica',
    'Drniš',
    'Grad Drniš',
    'Grad Šibenik',
    'Kistanje',
    'Knin',
    'Murter',
    'Murter-Kornati',
    'Pirovac',
    'Primošten',
    'Promina',
    'Rogoznica',
    'Rogoznica Općina',
    'Šibenik',
    'Skradin',
    'Tisno',
    'Tribunj',
    'Vodice',
  ],
  'Sisak-Moslavina': [
    'Budaševo',
    'Dvor',
    'Glina',
    'Grad Glina',
    'Grad Hrvatska Kostajnica',
    'Grad Kutina',
    'Grad Novska',
    'Grad Petrinja',
    'Grad Sisak',
    'Gvozd',
    'Hrvatska Kostajnica',
    'Kutina',
    'Lekenik',
    'Lipovljani',
    'Martinska Ves',
    'Novska',
    'Općina Dvor',
    'Općina Gvozd',
    'Petrinja',
    'Popovača',
    'Repušnica',
    'Sisak',
    'Sunja',
    'Voloder',
  ],
  'Split-Dalmatia': [
    'Baška Voda',
    'Bol',
    'Brela',
    'Brnaze',
    'Dicmo',
    'Donji Vinjani',
    'Duće',
    'Dugi Rat Općina',
    'Dugopolje',
    'Gala',
    'Grabovci',
    'Grad Hvar',
    'Grad Imotski',
    'Grad Makarska',
    'Grad Omiš',
    'Grad Sinj',
    'Grad Split',
    'Grad Supetar',
    'Grad Trogir',
    'Grad Vis',
    'Grad Vrgorac',
    'Gradac',
    'Greda',
    'Grubine',
    'Hrvace',
    'Hvar',
    'Imotski',
    'Jelsa',
    'Jesenice',
    'Kamen',
    'Kaštel Gomilica',
    'Kaštel Kambelovac',
    'Kaštel Lukšić',
    'Kaštel Novi',
    'Kaštel Štafilić',
    'Kaštel Stari',
    'Kaštela',
    'Klis',
    'Komiža',
    'Košute',
    'Lokvičići',
    'Lovreć',
    'Makarska',
    'Milna',
    'Mravince',
    'Muć',
    'Nerežišća',
    'Okrug',
    'Okrug Gornji',
    'Omiš',
    'Otok',
    'Podstrana',
    'Postira',
    'Proložac',
    'Pučišća',
    'Runović',
    'Runovići',
    'Seget',
    'Seget Vranjica',
    'Selca',
    'Sinj',
    'Slatine',
    'Solin',
    'Šolta',
    'Split',
    'Srinjine',
    'Stari Grad',
    'Stobreč',
    'Supetar',
    'Trilj',
    'Trogir',
    'Tučepi',
    'Turjaci',
    'Veliki Drvenik',
    'Vis',
    'Vranjic',
    'Vrgorac',
    'Vrlika',
    'Zagvozd',
    'Zmijavci',
    'Žrnovnica',
  ],
  Varaždin: [
    'Beretinec',
    'Breznica',
    'Breznički Hum',
    'Cestica',
    'Donje Ladanje',
    'Gornje Vratno',
    'Gornji Kneginec',
    'Grad Ivanec',
    'Grad Ludbreg',
    'Grad Novi Marof',
    'Grad Varaždin',
    'Hrašćica',
    'Ivanec',
    'Jalkovec',
    'Jalžabet',
    'Klenovnik',
    'Kućan Marof',
    'Lepoglava',
    'Ljubešćica',
    'Ludbreg',
    'Nedeljanec',
    'Petrijanec',
    'Remetinec',
    'Sračinec',
    'Sveti Đurđ',
    'Tužno',
    'Varaždin',
    'Vidovec',
    'Vinica',
  ],
  'Virovitica-Podravina': [
    'Čačinci',
    'Čađavica',
    'Crnac',
    'Grad Orahovica',
    'Grad Slatina',
    'Grad Virovitica',
    'Gradina',
    'Mikleuš',
    'Nova Bukovica',
    'Orahovica',
    'Pitomača',
    'Rezovac',
    'Slatina',
    'Sopje',
    'Špišić Bukovica',
    'Suhopolje',
    'Virovitica',
    'Voćin',
    'Zdenci',
  ],
  'Vukovar-Syrmia': [
    'Andrijaševci',
    'Babina Greda',
    'Bobota',
    'Bogdanovci',
    'Borovo',
    'Borovo Selo',
    'Bošnjaci',
    'Bršadin',
    'Cerić',
    'Cerna',
    'Drenovci',
    'Grad Vinkovci',
    'Grad Vukovar',
    'Grad Županja',
    'Gradište',
    'Gunja',
    'Ilok',
    'Ivankovo',
    'Jarmina',
    'Komletinci',
    'Lovas',
    'Markušica',
    'Mirkovci',
    'Negoslavci',
    'Nijemci',
    'Nuštar',
    'Otok',
    'Privlaka',
    'Retkovci',
    'Rokovci',
    'Soljani',
    'Stari Jankovci',
    'Štitar',
    'Tordinci',
    'Tovarnik',
    'Trpinja',
    'Vinkovci',
    'Vođinci',
    'Vrbanja',
    'Vukovar',
    'Županja',
  ],
  Zadar: [
    'Benkovac',
    'Bibinje',
    'Biograd na Moru',
    'Galovac',
    'Gornji Karin',
    'Gračac',
    'Grad Biograd na Moru',
    'Jasenice',
    'Kali',
    'Kruševo',
    'Nin',
    'Novigrad Općina',
    'Obrovac',
    'Osljak',
    'Pag',
    'Pakoštane',
    'Polača',
    'Poličnik',
    'Posedarje',
    'Preko',
    'Pridraga',
    'Privlaka',
    'Ražanac',
    'Sali',
    'Škabrnja',
    'Stari Grad',
    'Starigrad',
    'Sukošan',
    'Sveti Filip i Jakov',
    'Tkon',
    'Turanj',
    'Ugljan',
    'Vir',
    'Vrsi',
    'Zadar',
  ],
  Zagreb: [
    'Brezovica',
    'Centar',
    'Dubrava',
    'Gradska četvrt Donji grad',
    'Gradska četvrt Gornji Grad - Medvescak',
    'Gradska četvrt Podsljeme',
    'Horvati',
    'Jankomir',
    'Ježdovec',
    'Kašina',
    'Lučko',
    'Novi Zagreb',
    'Odra',
    'Sesvete',
    'Stenjevec',
    'Strmec',
    'Zadvorsko',
    'Zagreb',
  ],
};
//  {
//   Zagreb: [
//     'Zagreb',
//     'Samobor',
//     'Velika Gorica',
//     'Zaprešić',
//     'Sveta Nedelja',
//     'Jastrebarsko',
//     'Dugo Selo',
//   ],
//   'Split-Dalmatia': [
//     'Split',
//     'Makarska',
//     'Hvar',
//     'Trogir',
//     'Sinj',
//     'Omis',
//     'Imotski',
//   ],
//   'Dubrovnik-Neretva': [
//     'Dubrovnik',
//     'Metković',
//     'Ploče',
//     'Korčula',
//     'Cavtat',
//     'Opuzen',
//     'Ston',
//   ],
//   'Primorje-Gorski Kotar': [
//     'Rijeka',
//     'Crikvenica',
//     'Senj',
//     'Opatija',
//     'Vrbovsko',
//     'Delnice',
//     'Kraljevica',
//   ],
//   'Osijek-Baranja': [
//     'Osijek',
//     'Baranja',
//     'Valpovo',
//     'Našice',
//     'Beli Manastir',
//     'Đakovo',
//     'Bizovac',
//   ],
//   'Vukovar-Srijem': [
//     'Vukovar',
//     'Vinkovci',
//     'Ilok',
//     'Valpovo',
//     'Borovo',
//     'Županja',
//     'Tovarnik',
//   ],
//   Karlovac: [
//     'Karlovac',
//     'Ogulin',
//     'Duga Resa',
//     'Slunj',
//     'Jastrebarsko',
//     'Rakovica',
//     'Vrhovine',
//   ],
//   Zadar: [
//     'Zadar',
//     'Nin',
//     'Biograd na Moru',
//     'Pag',
//     'Benkovac',
//     'Obrovac',
//     'Knin',
//   ],
//   'Šibenik-Knin': [
//     'Šibenik',
//     'Knin',
//     'Vodice',
//     'Drniš',
//     'Tisno',
//     'Pirovac',
//     'Murter',
//   ],
//   'Lika-Senj': [
//     'Gospić',
//     'Senj',
//     'Otočac',
//     'Novalja',
//     'Korenica',
//     'Brinje',
//     'Udbina',
//   ],
//   Istria: ['Pula', 'Rovinj', 'Poreč', 'Umag', 'Labin', 'Novigrad', 'Buje'],
// };
