export const HAITI_REGIONS_CITIES = {
  Artibonite: [
    'Anse Rouge',
    'Arrondissement de Saint-Marc',
    'Désarmes',
    'Dessalines',
    'Ennery',
    'Gonaïves',
    'Grande Saline',
    'Gros Morne',
    'Marmelade',
    'Saint-Marc',
    'Verrettes',
  ],
  Centre: [
    'Arrondissement de Cerca La Source',
    'Cerca la Source',
    'Hinche',
    'Lascahobas',
    'Mayisad',
    'Mirebalais',
    'Thomassique',
    'Thomonde',
  ],
  "Grand'Anse": [
    'Anse-à-Veau',
    'Chambellan',
    'Corail',
    'Dame-Marie',
    'Jeremi',
    'Jérémie',
    'Les Abricots',
    'Les Irois',
    'Moron',
    'Petite Rivière de Nippes',
  ],
  Nippes: ['Ansavo', 'Baradères', 'Miragoâne', 'Petit Trou de Nippes'],
  Nord: [
    'Acul du Nord',
    'Arrondissement de la Grande Rivière du Nord',
    'Arrondissement de Plaisance',
    'Arrondissement du Borgne',
    'Bahon',
    'Borgne',
    'Dondon',
    'Grande Rivière du Nord',
    'Lenbe',
    'Limonade',
    'Milot',
    'Okap',
    'Pignon',
    'Pilate',
    'Plaine du Nord',
    'Plaisance',
    'Port-Margot',
    'Quartier Morin',
    'Ranquitte',
    'Saint-Raphaël',
  ],
  'Nord-Est': [
    'Arrondissement de Fort Liberté',
    'Arrondissement du Trou du Nord',
    'Caracol',
    'Carice',
    'Dérac',
    'Ferrier',
    'Fort Liberté',
    'Montòrganize',
    'Ouanaminthe',
    'Perches',
    'Phaëton',
    'Trou du Nord',
    'Wanament',
  ],
  'Nord-Ouest': [
    'Arcahaie',
    'Arrondissement de Port-de-Paix',
    'Arrondissement de Saint-Louis du Nord',
    'Arrondissement du Môle Saint-Nicolas',
    'Baie de Henne',
    'Bombardopolis',
    'Fond Bassin Bleu',
    'Jean-Rabel',
    'Môle Saint-Nicolas',
    'Petite Anse',
    'Port-de-Paix',
    'Saint-Louis du Nord',
    'Ti Port-de-Paix',
  ],
  Ouest: [
    'Anse à Galets',
    'Arcahaie',
    'Arrondissement de Croix des Bouquets',
    'Arrondissement de Léogâne',
    'Arrondissement de Port-au-Prince',
    'Cabaret',
    'Carrefour',
    'Cornillon',
    'Croix-des-Bouquets',
    'Delmas 73',
    'Fond Parisien',
    'Fonds Verrettes',
    'Grangwav',
    'Gressier',
    'Kenscoff',
    'Lagonav',
    'Léogâne',
    'Pétionville',
    'Port-au-Prince',
    'Thomazeau',
    'Tigwav',
  ],
  Sud: [
    'Aquin',
    'Arrondissement de Port-Salut',
    'Arrondissement des Cayes',
    'Cavaillon',
    'Chantal',
    'Chardonnière',
    'Fond des Blancs',
    'Koto',
    'Les Anglais',
    'Les Cayes',
    'Port-à-Piment',
    'Roche-à-Bateau',
    'Saint-Louis du Sud',
    'Tiburon',
    'Torbeck',
  ],
  'Sud-Est': [
    'Anse-à-Pitre',
    'Arrondissement de Bainet',
    'Arrondissement de Jacmel',
    'Belle-Anse',
    'Cayes-Jacmel',
    'Jacmel',
    'Kotdefè',
    'Marigot',
    'Thiotte',
  ],
};
