export const IRAQ_GOVERNORATES_CITIES = {
  'Al Anbar': [
    '‘Anah',
    '‘Anat al Qadīmah',
    'Al Fallūjah',
    'Ar Ruţbah',
    'Ḩadīthah',
    'Hīt',
    'Hīt District',
    'Ramadi',
    'Rāwah',
  ],
  'Al Muthanna': ['Ar Rumaythah', 'As Samawah'],
  'Al-Qādisiyyah': [
    '‘Afak',
    'Ad Dīwānīyah',
    'Ash Shāmīyah',
    'Nāḩiyat ash Shināfīyah',
    'Nahiyat Ghammas',
  ],
  Babylon: [
    'Al Ḩillah',
    'Al Musayyib',
    'Imam Qasim',
    'Nāḩīyat Saddat al Hindīyah',
  ],
  Baghdad: [
    'Abu Ghraib District',
    'Abū Ghurayb',
    'Adamiyah',
    'Al Adel',
    'Al Baladiyat',
    'Al Jamaa',
    'Al Saadoon Park',
    'Al Salhiah',
    "Al Za'franiya",
    'Al-Ubaidi',
    'Al-Wahda',
    'Ameria',
    'Amil District',
    'Amin',
    'Arasat AlHindiya',
    'At Taifiya',
    'Bab Al Moatham',
    'Bab Al Sharqi',
    'Baghdad',
    'Baghdad Al Jadeeda',
    'Baijai',
    'Bataween',
    'Bayaa',
    'Binouk',
    "Bo'aitha",
    'Camp Sarah',
    'Daoudi',
    'Dora',
    'Ghadeer',
    'Ghazaliya',
    "Gherai'at",
    'Green Zone',
    'Habibiya',
    'Harthiya',
    'Hurriya',
    'Iskan',
    'Jadriyah',
    'Jamila',
    'Jihad',
    'Kadhimiya',
    'Kamaliyah',
    'Karada',
    'Khadra',
    'Mansour',
    'Mashtal',
    'Mustansiriya',
    'Qadisiyah',
    'Sadr City',
    'Saidiya',
    "Sha'ab",
    'Sheik Maaruf',
    'Shorjah',
    'Suleikh',
    'Ur District',
    'Wazireya',
    'Yarmouk',
    'Ziyouna',
  ],
  Basra: [
    'Al Başrah al Qadīmah',
    'Al Fāw',
    'Al Hārithah',
    'Az Zubayr',
    'Basrah',
    'Umm Qaşr',
  ],
  'Dhi Qar': ['Ash Shaţrah', 'Nāḩiyat al Fuhūd', 'Nasiriyah'],
  Diyala: [
    'Al Miqdādīyah',
    'Baladrūz',
    'Baqubah',
    'Khāliş',
    'Kifrī',
    'Mandalī',
    'Qaḑā’ Kifrī',
  ],
  Dohuk: ['Al ‘Amādīyah', 'Batifa', 'Dihok', 'Sīnah', 'Zaxo'],
  Erbil: ['Arbil', 'Erbil', 'Koysinceq', 'Ruwāndiz', 'Shaqlāwah', 'Soran'],
  Karbala: ['Al Hindīyah', 'Karbala'],
  Kirkuk: ['Kirkuk'],
  Maysan: ['‘Alī al Gharbī', 'Al ‘Amārah', 'Al-Mejar Al-Kabi District'],
  Najaf: ['Al Mishkhāb', 'Kufa', 'Najaf'],
  Nineveh: [
    '‘Aqrah',
    'Al Mawşil al Jadīdah',
    'Al-Hamdaniya',
    'Ash Shaykhān',
    'Mosul',
    'Sinjar',
    'Tall ‘Afar',
    'Tallkayf',
  ],
  Saladin: ['Ad Dujayl', 'Balad', 'Bayjī', 'Sāmarrā’', 'Tikrīt', 'Tozkhurmato'],
  Sulaymaniyah: ['As Sulaymānīyah', 'Baynjiwayn', 'Ḩalabjah', 'Jamjamāl'],
  Wasit: ['Al ‘Azīzīyah', 'Al Ḩayy', 'Al Kūt', 'Aş Şuwayrah'],
};
