export const ICELAND_REGIONS_CITIES = {
  'Capital Region': [
    'Álftanes',
    'Garðabær',
    'Hafnarfjörður',
    'Kjósarhreppur',
    'Kópavogur',
    'Mosfellsbaer',
    'Mosfellsbær',
    'Reykjavík',
    'Seltjarnarnes',
  ],
  'Eastern Region': [
    'Borgarfjarðarhreppur',
    'Breiðdalshreppur',
    'Egilsstaðir',
    'Eskifjörður',
    'Fjarðabyggð',
    'Fljótsdalshérað',
    'Fljótsdalshreppur',
    'Höfn',
    'Neskaupstaður',
    'Reyðarfjörður',
  ],
  'Northeastern Region': [
    'Akureyri',
    'Dalvík',
    'Dalvíkurbyggð',
    'Eyjafjarðarsveit',
    'Fjallabyggð',
    'Grýtubakkahreppur',
    'Hörgársveit',
    'Húsavík',
    'Langanesbyggð',
    'Laugar',
    'Siglufjörður',
    'Skútustaðahreppur',
    'Svalbarðsstrandarhreppur',
    'Tjörneshreppur',
    'Þingeyjarsveit',
  ],
  'Northwestern Region': [
    'Akrahreppur',
    'Húnaþing Vestra',
    'Sauðárkrókur',
    'Skagabyggð',
    'Sveitarfélagið Skagafjörður',
  ],
  'Southern Peninsula Region': [
    'Garður',
    'Grindavík',
    'Keflavík',
    'Reykjanesbær',
    'Sandgerði',
    'Vogar',
  ],
  'Southern Region': [
    'Ásahreppur',
    'Bláskógabyggð',
    'Flóahreppur',
    'Grímsnes- og Grafningshreppur',
    'Hrunamannahreppur',
    'Hveragerði',
    'Mýrdalshreppur',
    'Selfoss',
    'Skaftárhreppur',
    'Skeiða- og Gnúpverjahreppur',
    'Vestmannaeyjabær',
    'Vestmannaeyjar',
    'Þorlákshöfn',
  ],
  'Western Region': [
    'Akranes',
    'Borgarbyggð',
    'Borgarnes',
    'Dalabyggð',
    'Eyja- og Miklaholtshreppur',
    'Helgafellssveit',
    'Hvalfjarðarsveit',
    'Ólafsvík',
    'Skorradalshreppur',
    'Snæfellsbær',
    'Stykkishólmur',
  ],
  Westfjords: [
    'Ísafjarðarbær',
    'Ísafjörður',
    'Reykhólahreppur',
    'Strandabyggð',
    'Tálknafjarðarhreppur',
  ],
};
