export const JORDAN_GOVERNORATES_CITIES = {
  Ajloun: ['‘Ajlūn', '‘Anjarah', '‘Ayn Jannah', 'Ḩalāwah', 'Şakhrah'],
  Amman: [
    'Al Jīzah',
    'Al Jubayhah',
    'Amman',
    'Ḩayy al Bunayyāt',
    'Ḩayy al Quwaysimah',
    'Jāwā',
    'Saḩāb',
    'Umm as Summāq',
    'Wādī as Sīr',
  ],
  Aqaba: ['Aqaba', 'Tala Bay'],
  Balqa: ['Al Karāmah', 'As Salţ', 'Yarqā'],
  Irbid: [
    'Ar Ramthā',
    'Ash Shajarah',
    'Aţ Ţayyibah',
    'Aţ Ţurrah',
    'Aydūn',
    'Bayt Īdis',
    'Bayt Yāfā',
    'Dayr Yūsuf',
    'Ḩakamā',
    'Ḩātim',
    'Irbid',
    'Judita',
    'Kafr Abīl',
    'Kafr Asad',
    'Kafr Sawm',
    'Kharjā',
    'Kitim',
    'Kurayyimah',
    'Malkā',
    'Qumaym',
    'Saḩam al Kaffārāt',
    'Sāl',
    'Şammā',
    'Tibnah',
    'Umm Qays',
    'Waqqāş',
    'Zaḩar',
  ],
  Jerash: [
    'Al Kittah',
    'Balīlā',
    'Burmā',
    'Jarash',
    'Qafqafā',
    'Raymūn',
    'Sakib',
    'Sūf',
  ],
  Karak: [
    '‘Ayy',
    '‘Izrā',
    'Adir',
    'Al Khinzīrah',
    'Al Mazār al Janūbī',
    'Al Qaşr',
    'Ar Rabbah',
    'Karak City',
    'Safi',
  ],
  "Ma'an": [
    'Al Jafr',
    'Al Quwayrah',
    'Ash Shawbak',
    'Aţ Ţayyibah',
    "Ma'an",
    'Petra',
    'Qīr Moāv',
  ],
  Madaba: ['Mādabā'],
  Mafraq: ['Al Ḩamrā’', 'Mafraq', 'Rehab', 'Rukban', 'Şabḩā', 'Umm al Qiţţayn'],
  Tafilah: ['Aţ Ţafīlah', 'Buşayrā'],
  Zarqa: ['Al Azraq ash Shamālī', 'Russeifa', 'Zarqa'],
};
