export const KENYA_STATE_CITY = {
  Baringo: ['Baringo', 'Eldama Ravine', 'Kabarnet'],
  Bomet: ['Sotik', 'Sotik Post'],
  Bungoma: ['Bungoma', 'Malikisi', 'Webuye'],
  Busia: ['Busia', 'Luanda', 'Lugulu', 'Malaba', 'Nambare', 'Port Victoria'],
  Embu: ['Embu'],
  Garissa: ['Garissa'],
  'Homa Bay': ['Homa Bay', 'Oyugis', 'Rachuonyo District'],
  Isiolo: ['Isiolo'],
  Kajiado: ['Kajiado', 'Magadi', 'Ngong'],
  Kakamega: ['Butere', 'Kakamega', 'Mumias'],
  Kericho: ['Kericho', 'Kipkelion', 'Litein', 'Londiani'],
  Kiambu: ['Kiambu', 'Kikuyu', 'Limuru', 'Thika'],
  Kilifi: ['Iten', 'Kapsowar', 'Kilifi', 'Malindi', 'Mariakani', 'Takaungu'],
  Kirinyaga: ['Kerugoya', 'Sagana'],
  Kisii: ['Kisii', 'Ogembo'],
  Kisumu: ['Ahero', 'Kisumu', 'Muhoroni'],
  Kitui: ['Kitui', 'Mwingi'],
  Kwale: ['Gazi', 'Kinango', 'Kwale', 'Sawa Sawa', 'Shimoni'],
  Laikipia: ['Nanyuki', 'Nyahururu', 'Rumuruti'],
  Lamu: ['Lamu', 'Witu'],
  Machakos: ['Athi River', 'Kangundo', 'Konza', 'Machakos'],
  Makueni: ['Makueni Boma', 'Mtito Andei', 'Wote'],
  Mandera: ['Mandera'],
  Marsabit: ['Marsabit', 'Moyale'],
  Meru: ['Maua', 'Meru'],
  Migori: ['Kihancha', 'Migori'],
  Mombasa: ['Mombasa'],
  "Murang'a": ['Kangema', 'Karuri', 'Maragua', 'Murang’a'],
  'Nairobi City': ['Nairobi', 'Pumwani'],
  Nakuru: ['Kijabe', 'Molo', 'Naivasha', 'Nakuru', 'Rongai'],
  Nandi: ['Kapsabet', 'Nandi Hills'],
  Narok: ['Narok'],
  Nyamira: ['Keroka', 'Nyamira'],
  Nyandarua: ['Ol Kalou'],
  Nyeri: ['Naro Moru', 'Nyeri', 'Othaya'],
  Samburu: ['Maralal'],
  Siaya: ['Bondo', 'Siaya', 'Yala'],
  'Tana River': ['Hola', 'Kipini'],
  'Tharaka-Nithi': ['Chuka'],
  'Trans Nzoia': ['Kitale'],
  Turkana: ['Lodwar'],
  'Uasin Gishu': ['Eldoret'],
  Wajir: ['Wajir'],
  'West Pokot': ['Chepareria', 'Kapenguria', 'Taveta', 'Voi', 'Wundanyi'],
};
