export const KYRGYZSTAN_PROVINCES_CITIES = {
  'Batken Region': [
    'Aydarken',
    'Batken',
    'Iradan',
    'Isfana',
    'Karavan',
    'Kyzyl-Kyya',
    'Suluktu',
  ],
  Bishkek: ['Bishkek'],
  'Chuy Region': [
    'Alamudunskiy Rayon',
    'Belovodskoye',
    'Chuyskiy Rayon',
    'Ivanovka',
    'Kaindy',
    'Kant',
    'Kara-Balta',
    'Kemin',
    'Lebedinovka',
    'Sokulukskiy Rayon',
    'Sosnovka',
    'Tokmok',
    'Ysyk-Ata',
  ],
  'Issyk-Kul Region': [
    'Ak-Suu',
    'Balykchy',
    'Cholpon-Ata',
    'Kadzhi-Say',
    'Karakol',
    'Kyzyl-Suu',
    'Tyup',
  ],
  'Jalal-Abad Region': [
    'Ala-Buka',
    'Bazar-Korgon',
    'Jalal-Abad',
    'Kazarman',
    'Kerben',
    'Kochkor-Ata',
    'Suzak',
    'Tash-Kumyr',
    'Toktogul',
    'Toktogul District',
  ],
  'Naryn Region': ['At-Bashi', 'Jumgal', 'Naryn'],
  'Osh Region': [
    'Chong-Alay District',
    'Daroot-Korgon',
    'Kara Kulja',
    'Kara Suu',
    'Kyzyl-Eshme',
    'Nookat',
    'Osh',
    'Uzgen',
    'Uzgen District',
  ],
  'Talas Region': ['Kara-Buurinskiy Rayon', 'Talas', 'Talasskiy Rayon'],
};
