export const CAMBODIA_PROVINCES_CITIES = {
  'Banteay Meanchey': [
    'Mongkol Borei',
    'Paoy Paet',
    'Sisophon',
    'Srŏk Malai',
    'Srŏk Svay Chék',
  ],
  Battambang: [
    'Battambang',
    'Srŏk Âk Phnŭm',
    'Srŏk Banăn',
    'Srŏk Bâvĭl',
    'Srŏk Rotanak Mondol',
  ],
  'Kampong Cham': ['Cheung Prey', 'Kampong Cham', 'Srŏk Bathéay'],
  'Kampong Chhnang': [
    'Baribour',
    'Kampong Chhnang',
    "Rolea B'ier",
    'Srŏk Chol Kiri',
    'Srŏk Sameakki Mean Chey',
  ],
  'Kampong Speu': [
    'Kampong Speu',
    'Krŏng Chbar Mon',
    'Srŏk Basedth',
    'Srŏk Kông Pĭsei',
    'Srŏk Ŏdŏngk',
  ],
  Kampot: [
    'Angkor Chey',
    'Banteay Meas',
    'Chhouk District',
    'Kampong Bay',
    'Kampong Tranch',
    'Kampot',
    'Srŏk Chŭm Kiri',
    'Srŏk Dângtóng',
    'Srok Tuek Chhou',
  ],
  Kandal: ['Krŏng Ta Khmau', 'Srŏk Khsăch Kândal', 'Ta Khmau'],
  Kep: ['Krong Kep', 'Srŏk Dâmnăk Châng’aeur'],
  'Koh Kong': [
    'Koh Kong',
    'Smach Mean Chey',
    'Srae Ambel',
    'Srŏk Batum Sakôr',
    'Srŏk Môndôl Seima',
  ],
  Kratie: ['Kracheh', 'Kratié', 'Snuol'],
  Mondulkiri: [
    'Krŏng Sênmônoŭrôm',
    'Sen Monorom',
    'Srŏk Kaev Seima',
    'Srŏk Pech Chreada',
  ],
  'Oddar Meanchey': [
    'Samraong',
    'Srŏk Bântéay Âmpĭl',
    'Srŏk Sâmraông',
    'Srŏk Trâpeăng Prasat',
  ],
  Pailin: ['Khan Sala Krau', 'Pailin'],
  'Phnom Penh': [
    'Khan 7 Makara',
    'Khan Châmkar Mon',
    'Khan Dângkaô',
    'Khan Duŏn Pénh',
    'Khan Méan Chey',
    'Khan Russey Keo',
    'Khan Saen Sokh',
    'Phnom Penh',
  ],
  'Preah Vihear': [
    'Sangkom Thmei',
    'Srŏk Ch’êh Sên',
    'Srŏk Chhêb',
    'Srŏk Kulén',
    'Srŏk Rôviĕng',
    'Srŏk Tbêng Méanchey',
    'Tbeng Meanchey',
  ],
  'Prey Veng': [
    'Prey Veng',
    'Srŏk Kâmpóng Léav',
    'Srŏk Mésang',
    'Srŏk Preăh Sdéch',
  ],
  Pursat: [
    'Bakan',
    'Krakor',
    'Pursat',
    'Sampov Meas',
    'Srŏk Kândiĕng',
    'Srŏk Véal Vêng',
  ],
  Ratanakiri: [
    'Banlung',
    'Lumphat',
    'Srŏk Ândong Méas',
    'Srŏk Bâ Kêv',
    'Srŏk Ban Lŭng',
    'Srŏk Koun Mom',
    'Srŏk Ou Chum',
    'Srŏk Ou Ya Dav',
    'Srŏk Ta Vêng',
  ],
  'Siem Reap': [
    'Siem Reap',
    'Srŏk Ângkôr Thum',
    'Srŏk Prasat Bakong',
    'Svay Leu',
    'Varin',
  ],
  Sihanoukville: ['Sihanoukville', 'Srok Stueng Hav'],
  'Stung Treng': ['Srŏk Srêsén', 'Stueng Traeng', 'Stung Treng'],
  'Svay Rieng': ['Srŏk Svay Chrŭm', 'Svay Rieng'],
  Takeo: [
    'Krŏng Doun Kaev',
    'Phumĭ Véal Srê',
    'Srŏk Ângkôr Borei',
    'Srŏk Borei Cholsar',
    'Takeo',
  ],
};
