export const ST_KITTS_AND_NEVIS_REGIONS_TOWNS = {
  'Christ Church Nichola Town Parish': ['Nicola Town'],
  'Saint Anne Sandy Point Parish': ['Sandy Point Town'],
  'Saint George Gingerland Parish': ['Market Shop'],
  'Saint James Windward Parish': ['Newcastle'],
  'Saint John Capisterre Parish': ['Dieppe Bay Town'],
  'Saint John Figtree Parish': ['Fig Tree'],
  'Saint Mary Cayon Parish': ['Cayon'],
  'Saint Paul Capisterre Parish': ['Saint Paul’s'],
  'Saint Paul Charlestown Parish': ['Charlestown'],
  'Saint Peter Basseterre Parish': ['Monkey Hill'],
  'Saint Thomas Lowland Parish': ['Cotton Ground'],
  'Saint Thomas Middle Island Parish': ['Middle Island'],
  'Trinity Palmetto Point Parish': ['Trinity'],
};
