export const KAZAKHSTAN_REGIONS_CITIES = {
  'Akmola Region': [
    'Akkol',
    'Akkol’',
    'Aksu',
    'Astrakhan',
    'Atbasar',
    'Balkashino',
    'Bestobe',
    'Derzhavīnsk',
    'Egindiköl',
    'Esil',
    'Kokshetau',
    'Krasnogorskiy',
    'Makinsk',
    'Shantobe',
    'Shchuchinsk',
    'Shortandy',
    'Stepnogorsk',
    'Stepnyak',
    'Yermentau',
    'Zavodskoy',
    'Zhaqsy',
    'Zholymbet',
  ],
  'Aktobe Region': [
    'Aktobe',
    'Batamshinskiy',
    'Bayganin',
    'Embi',
    'Kandyagash',
    'Khromtau',
    'Martuk',
    'Shalqar',
    'Shubarkuduk',
    'Shubarshi',
    'Temir',
    'Yrghyz',
  ],
  Almaty: ['Almaty'],
  'Almaty Region': [
    'Bakanas',
    'Balpyk Bī',
    'Burunday',
    'Chemolgan',
    'Druzhba',
    'Esik',
    'Kapshagay',
    'Kegen',
    'Lepsy',
    'Matay',
    'Otegen Batyra',
    'Pervomayka',
    'Sarkand',
    'Saryozek',
    'Taldykorgan',
    'Talghar',
    'Tekeli',
    'Turgen',
    'Ülken',
    'Ush-Tyube',
    'Zharkent',
  ],
  'Atyrau Region': [
    'Akkol’',
    'Atyrau',
    'Balykshi',
    'Bayshonas',
    'Dossor',
    'Inderbor',
    'Makhambet',
    'Maloye Ganyushkino',
    'Maqat',
    'Miyaly',
    'Qaraton',
    'Qulsary',
    'Shalkar',
  ],
  Baikonur: ['Baikonur'],
  'East Kazakhstan Region': [
    'Altayskiy',
    'Aqtoghay',
    'Asūbulaq',
    'Auezov',
    'Ayagoz',
    'Belogorskīy',
    'Belousovka',
    'Borodulikha',
    'Georgīevka',
    'Glubokoye',
    'Kurchatov',
    'Kurchum',
    'Maleyevsk',
    'Ognevka',
    'Priisk Boko',
    'Qaraūyl',
    'Ridder',
    'Semey',
    'Shar',
    'Shemonaīkha',
    'Suykbulak',
    'Tūghyl',
    'Urzhar',
    'Ust-Kamenogorsk',
    'Ūst’-Talovka',
    'Zaysan',
    'Zhalghyztobe',
    'Zhanga Buqtyrma',
    'Zhezkent',
    'Zyryanovsk',
  ],
  'Jambyl Region': [
    'Aqbaqay',
    'Chu',
    'Georgiyevka',
    'Granitogorsk',
    'Karatau',
    'Khantaū',
    'Lugovoy',
    'Lugovoye',
    'Merke',
    'Moyynkum',
    'Mynaral',
    'Oytal',
    'Sarykemer',
    'Shyghanaq',
    'Taraz',
    'Zhangatas',
  ],
  'Karaganda Region': [
    'Abay',
    'Abay Qalasy',
    'Aksu-Ayuly',
    'Aktas',
    'Aktau',
    'Aktogay',
    'Aqadyr',
    'Aqshataū',
    'Aqtoghay Aūdany',
    'Atasū',
    'Balqash',
    'Bukhar-Zhyrau',
    'Dolinka',
    'Karagandy',
    'Kīevka',
    'Koktal',
    'Kushoky',
    'Kyzylzhar',
    'Moyynty',
    'Novodolinskiy',
    'Osakarovka',
    'Prigorodnoye',
    'Priozersk',
    'Qarazhal',
    'Qarqaraly',
    'Saryshaghan',
    'Sayaq',
    'Shakhan',
    'Shakhtinsk',
    'Shashūbay',
    'Shubarköl',
    'Soran',
    'Temirtau',
    'Tokarevka',
    'Verkhniye Kayrakty',
    'Zhambyl',
    'Zharyk',
    'Zhezqazghan',
  ],
  'Kostanay Region': [
    'Arkalyk',
    'Ayat',
    'Borovskoy',
    'Dzhetygara',
    'Fyodorovka',
    'Karasu',
    'Komsomolets',
    'Kostanay',
    'Lisakovsk',
    'Ordzhonikidze',
    'Qashar',
    'Qusmuryn',
    'Rudnyy',
    'Tobol',
    'Torghay',
    'Troyebratskiy',
  ],
  'Kyzylorda Region': [
    'Aral',
    'Ayteke Bi',
    'Belköl',
    'Dzhalagash',
    'Kyzylorda',
    'Qazaly',
    'Sekseūil',
    'Shalqīya',
    'Shīeli',
    'Tasböget',
    'Terenozek',
    'Yanykurgan',
    'Zhosaly',
  ],
  'Mangystau Region': [
    'Aktau',
    'Baūtīno',
    'Beyneu',
    'Fort-Shevchenko',
    'Munayshy',
    'Ömirzaq',
    'Sayötesh',
    'Shetpe',
    'Taūshyq',
    'Yeraliyev',
    'Zhanaozen',
    'Zhetibay',
  ],
  'North Kazakhstan Region': [
    'Birlestik',
    'Bishkul',
    'Bulayevo',
    'Būrabay',
    'Kzyltu',
    'Novoishimskiy',
    'Petropavl',
    'Sergeyevka',
    'Smirnovo',
    'Taiynsha',
    'Talshik',
    'Timiryazevo',
    'Volodarskoye',
    'Yavlenka',
  ],
  'Nur-Sultan': ['Nur-Sultan'],
  'Pavlodar Region': [
    'Aksu',
    'Bayanaul',
    'Belogor’ye',
    'Ekibastuz',
    'Irtyshsk',
    'Kalkaman',
    'Leninskiy',
    'Mayqayyng',
    'Pavlodar',
    'Qashyr',
    'Zhelezinka',
  ],
  'Turkestan Region': [
    'Arys',
    'Ashchysay',
    'Asyqata',
    'Atakent',
    'Bayzhansay',
    'Belyye Vody',
    'Chardara',
    'Chayan',
    'Chulakkurgan',
    'Kantagi',
    'Kentau',
    'Kokterek',
    'Lenger',
    'Leninskoye',
    'Maqtaaral Aūdany',
    'Myrzakent',
    'Qogham',
    'Saryaghash',
    'Saryaghash Aūdany',
    'Sastobe',
    'Sozaq Aūdany',
    'Temirlanovka',
    'Turar Ryskulov',
    'Turkestan',
    'Tyul’kubas',
    'Zhabagly',
  ],
  'West Kazakhstan Province': [
    'Aqsay',
    'Burlin',
    'Chapaev',
    'Chingirlau',
    'Dzhambeyty',
    'Fedorovka',
    'Kaztalovka',
    'Krūgloozernoe',
    'Oral',
    'Peremetnoe',
    'Saykhin',
    'Tasqala',
    'Zhänibek',
  ],
};
