export const SRI_LANKA_PROVINCES_DISTRICTS = {
  'Central Province': [
    'Dambulla',
    'Hatton',
    'Kandy',
    'Kandy District',
    'Matale',
    'Matale District',
    'Nuwara Eliya',
    'Nuwara Eliya District',
    'Sigiriya',
    'Talawakele',
  ],
  'Colombo District': [
    'Dehiwala-Mount Lavinia',
    'Homagama',
    'Kaduwela',
    'Kesbewa',
    'Kolonnawa',
    'Kotte',
    'Maharagama',
    'Moratuwa',
    'Padukka',
    'Ratmalana',
    'Seethawaka',
    'Thimbirigasyaya',
  ],
  'Eastern Province': [
    'Ampara',
    'Ampara District',
    'Batticaloa',
    'Batticaloa District',
    'Eravur Town',
    'Kalmunai',
    'Trincomalee',
    'Trincomalee District',
    'Vakarai',
  ],
  'Kandy District': [
    'Akurana',
    'Alawatugoda',
    'Ambatenna',
    'Daskara',
    'Daulagala',
    'Delthota',
    'Doluwa',
    'Galagedara',
    'Galhinna',
    'Gampola',
    'Ganga Ihala Korale',
    'Hanguranketa',
    'Hapugastalawa',
    'Harispattuwa',
    'Hatharaliyadda',
    'Kadugannawa',
    'Kandy Four Gravets',
    'Katugastota',
    'Kundasale',
    'Madawala',
    'Medadumbara',
    'Menikdiwela',
    'Minipe',
    'Nawalapitiya',
    'Pallekele',
    'Panvila',
    'Pasbage Korale',
    'Pathadumbara',
    'Pathahewaheta',
    'Peradeniya',
    'Pilimathalawa',
    'Poojapitiya',
    'Pussellawa',
    'Talatuoya',
    'Teldeniya',
    'Thumpane',
    'Udadumbara',
    'Udapalatha',
    'Ududumbara',
    'Udunuwara',
    'Ulapane',
    'Watadeniya',
    'Wattegama',
    'Welamboda',
    'Yatinuwara',
  ],
  'North Central Province': [
    'Anuradhapura',
    'Anuradhapura District',
    'Mihintale',
    'Polonnaruwa',
    'Polonnaruwa District',
  ],
  'North Western Province': [
    'Chilaw',
    'Kuliyapitiya',
    'Kurunegala',
    'Kurunegala District',
    'Puttalam',
    'Puttalam District',
  ],
  'Northern Province': [
    'Jaffna',
    'Jaffna District',
    'Kilinochchi',
    'Kilinochchi District',
    'Point Pedro',
    'Valvedditturai',
    'Vavuniya',
    'Vavuniya District',
  ],
  'Sabaragamuwa Province': [
    'Kegalle',
    'Kegalle District',
    'Ratnapura',
    'Ratnapura District',
  ],
  'Southern Province': [
    'Ambalangoda',
    'Bentota',
    'Devinuwara',
    'Galle',
    'Galle District',
    'Hambantota District',
    'Hikkaduwa',
    'Koggala',
    'Matara',
    'Matara District',
    'Mirissa city',
    'Talpe',
    'Tangalle',
    'Unawatuna',
    'Weligama',
  ],
  'Uva Province': [
    'Badulla',
    'Badulla District',
    'Ella Town',
    'Haputale',
    'Kataragama',
    'Monaragala',
    'Moneragala District',
    'Wellawaya',
  ],
  'Western Province': [
    'Battaramulla South',
    'Beruwala',
    'Colombo',
    'Colombo District',
    'Gampaha',
    'Gampaha District',
    'Hanwella Ihala',
    'Hendala',
    'Horana South',
    'Horawala Junction',
    'Ja Ela',
    'Kalutara',
    'Kandana',
    'Katunayaka',
    'Kelaniya',
    'Kotikawatta',
    'Minuwangoda',
    'Mulleriyawa',
    'Negombo',
    'Panadura',
    'Peliyagoda',
    'Pita Kotte',
    'Sri Jayewardenepura Kotte',
    'Wattala',
    'Welisara',
  ],
};
