export const LIBERIA_COUNTIES_CITIES = {
  'Bomi County': ['Tubmanburg'],
  'Bong County': ['Gbarnga'],
  'Gbarpolu County': ['Bopolu'],
  'Grand Bassa County': ['Buchanan'],
  'Grand Cape Mount County': ['Robertsport'],
  'Grand Gedeh County': ['Zwedru'],
  'Grand Kru County': ['Barclayville'],
  'Lofa County': ['Voinjama'],
  'Margibi County': ['Kakata'],
  'Maryland County': ['Harper'],
  'Montserrado County': ['Bensonville', 'Monrovia'],
  Nimba: ['Ganta', 'New Yekepa', 'Sanniquellie'],
  'River Cess County': ['Cestos City'],
  'River Gee County': ['Fish Town'],
  'Sinoe County': ['Greenville'],
};
