export const LITHUANIA_COUNTIES_CITIES = {
  'Alytus City Municipality': [
    'Alytus',
    'Daugai',
    'Druskininkai',
    'Lazdijai',
    'Simnas',
    'Varėna',
    'Veisiejai',
  ],
  'Kaunas City Municipality': [
    'Akademija (Kaunas)',
    'Aleksotas',
    'Ariogala',
    'Birštonas',
    'Dainava (Kaunas)',
    'Eiguliai',
    'Ežerėlis',
    'Garliava',
    'Jieznas',
    'Jonava',
    'Kaišiadorys',
    'Karmėlava',
    'Kaunas',
    'Kėdainiai',
    'Kulautuva',
    'Mastaiciai',
    'Prienai',
    'Ramučiai',
    'Raseiniai',
    'Sargėnai',
    'Šilainiai',
    'Vilkija',
    'Žiežmariai',
  ],
  'Klaipėda District Municipality': [
    'Gargždai',
    'Klaipėda',
    'Kretinga',
    'Neringa',
    'Nida',
    'Palanga',
    'Priekulė',
    'Rusnė',
    'Salantai',
    'Silute',
    'Skuodas',
    'Šventoji',
    'Žemaičių Naumiestis',
  ],
  'Marijampolė Municipality': [
    'Gelgaudiškis',
    'Kalvarija',
    'Kalvarija Municipality',
    'Kazlų Rūda',
    'Kazlų Rūda Municipality',
    'Kudirkos Naumiestis',
    'Kybartai',
    'Marijampolė',
    'Marijampolė Municipality',
    'Sakiai',
    'Vilkaviskis',
    'Vilkaviškis District Municipality',
    'Virbalis',
  ],
  'Panevėžys District Municipality': [
    'Birzai',
    'Juodupė',
    'Kupiskis',
    'Obeliai',
    'Panevėžys',
    'Panevėžys City',
    'Panevėžys District Municipality',
    'Pasvalys',
    'Ramygala',
    'Rokiškis',
    'Vabalninkas',
  ],
  'Šiauliai City Municipality': [
    'Akmenė',
    'Joniškis',
    'Kelmė',
    'Kuršėnai',
    'Linkuva',
    'Naujoji Akmene',
    'Pakruojis',
    'Radviliskis',
    'Šeduva',
    'Šiauliai',
    'Tytuvėnėliai',
    'Venta',
    'Žagarė',
  ],
  'Tauragė County': ['Būgai', 'Jurbarkas', 'Pagėgiai', 'Šilalė', 'Taurage'],
  'Telšiai District Municipality': [
    'Mazeikiai',
    'Plateliai',
    'Plunge',
    'Rietavas',
    'Seda',
    'Telsiai',
    'Varniai',
    'Viekšniai',
  ],
  'Utena County': [
    'Anyksciai',
    'Dūkštas',
    'Ignalina',
    'Moletai',
    'Utena',
    'Visaginas',
    'Zarasai',
  ],
  'Vilnius City Municipality': [
    'Aukstadvaris',
    'Baltoji Vokė',
    'Eišiškės',
    'Elektrėnai',
    'Fabijoniškės',
    'Grigiškės',
    'Justiniškės',
    'Lazdynai',
    'Lentvaris',
    'Naujamiestis',
    'Nemenčinė',
    'Pabradė',
    'Pašilaičiai',
    'Pilaitė',
    'Rasos',
    'Rūdiškės',
    'Šalčininkai',
    'Senieji Trakai',
    'Šeškinė',
    'Sirvintos',
    'Skaidiškės',
    'Švenčionėliai',
    'Svencionys',
    'Trakai',
    'Ukmerge',
    'Vievis',
    'Vilkpėdė',
    'Vilnius',
    'Vilnius District Municipality',
  ],
};
