export const LUXEMBOURG_REGIONS_CITIES = {
  'Canton of Capellen': [
    'Bascharage',
    'Bridel',
    'Capellen',
    'Clemency',
    'Dippach',
    'Eischen',
    'Garnich',
    'Hautcharage',
    'Hobscheid',
    'Käerjeng',
    'Kehlen',
    'Koerich',
    'Kopstal',
    'Mamer',
    'Schouweiler',
    'Septfontaines',
    'Steinfort',
  ],
  'Canton of Clervaux': [
    'Clervaux',
    'Hosingen',
    'Parc Hosingen',
    'Troisvierges',
    'Weiswampach',
    'Wincrange',
  ],
  'Canton of Diekirch': [
    'Bettendorf',
    'Bourscheid',
    'Commune de la Vallée de l’Ernz',
    'Diekirch',
    'Erpeldange',
    'Ettelbruck',
    'Feulen',
    'Medernach',
    'Mertzig',
    'Niederfeulen',
    'Reisdorf',
    'Schieren',
    'Warken',
  ],
  'Canton of Echternach': [
    'Beaufort',
    'Bech',
    'Berdorf',
    'Consdorf',
    'Echternach',
    'Mompach',
    'Rosport',
    'Waldbillig',
  ],
  'Canton of Esch-sur-Alzette': [
    'Aspelt',
    'Belvaux',
    'Bergem',
    'Bettembourg',
    'Crauthem',
    'Differdange',
    'Dudelange',
    'Esch-sur-Alzette',
    'Frisange',
    'Kayl',
    'Lamadelaine',
    'Leudelange',
    'Mondercange',
    'Niedercorn',
    'Obercorn',
    'Pétange',
    'Pontpierre',
    'Reckange-sur-Mess',
    'Rodange',
    'Roeser',
    'Rumelange',
    'Sanem',
    'Schifflange',
    'Soleuvre',
    'Tétange',
  ],
  'Canton of Grevenmacher': [
    'Betzdorf',
    'Biwer',
    'Flaxweiler',
    'Gonderange',
    'Grevenmacher',
    'Junglinster',
    'Manternach',
    'Mertert',
    'Wasserbillig',
    'Wormeldange',
  ],
  'Canton of Luxembourg': [
    'Alzingen',
    'Béreldange',
    'Bertrange',
    'Contern',
    'Fentange',
    'Heisdorf',
    'Helmsange',
    'Hesperange',
    'Itzig',
    'Kirchberg',
    'Luxembourg',
    'Moutfort',
    'Müllendorf',
    'Niederanven',
    'Olm',
    'Sandweiler',
    'Schrassig',
    'Schuttrange',
    'Steinsel',
    'Strassen',
    'Walferdange',
    'Weiler-la-Tour',
  ],
  'Canton of Mersch': [
    'Bissen',
    'Boevange-sur-Attert',
    'Colmar',
    'Fischbach',
    'Heffingen',
    'Larochette',
    'Lintgen',
    'Lorentzweiler',
    'Mersch',
    'Nommern',
    'Rollingen',
    'Tuntange',
  ],
  'Canton of Redange': [
    'Beckerich',
    'Bettborn',
    'Commune de Préizerdaul',
    'Ell',
    'Grosbous',
    'Rambrouch',
    'Redange-sur-Attert',
    'Saeul',
    'Useldange',
    'Vichten',
    'Wahl',
  ],
  'Canton of Remich': [
    'Bous',
    'Dalheim',
    'Lenningen',
    'Mondorf-les-Bains',
    'Remich',
    'Schengen',
    'Stadtbredimus',
    'Waldbredimus',
  ],
  'Canton of Vianden': ['Putscheid', 'Tandel', 'Vianden'],
  'Canton of Wiltz': [
    'Bavigne',
    'Boulaide',
    'Esch-sur-Sûre',
    'Goesdorf',
    'Kiischpelt',
    'Lac de la Haute-Sûre',
    'Wiltz',
    'Wilwerwiltz',
    'Winseler',
  ],
};
