export const LATVIA_REGIONS_CITIES = {
  'Aglona Municipality': ['Aglona'],
  'Aizkraukle Municipality': ['Aizkraukle'],
  'Aizpute Municipality': ['Aizpute'],
  'Aknīste Municipality': ['Aknīste'],
  'Aloja Municipality': ['Aloja', 'Staicele'],
  'Alsunga Municipality': ['Alsunga'],
  'Alūksne Municipality': ['Alūksne'],
  'Ape Municipality': ['Ape'],
  'Auce Municipality': ['Auce'],
  'Babīte Municipality': ['Piņķi'],
  'Baldone Municipality': ['Baldone'],
  'Baltinava Municipality': ['Baltinava'],
  'Balvi Municipality': ['Balvi'],
  'Bauska Municipality': ['Bauska'],
  'Beverīna Municipality': ['Mūrmuiža'],
  'Brocēni Municipality': ['Brocēni'],
  'Carnikava Municipality': ['Carnikava'],
  'Cēsis Municipality': ['Cēsis'],
  'Cesvaine Municipality': ['Cesvaine'],
  'Cibla Municipality': ['Cibla'],
  'Dagda Municipality': ['Dagda'],
  'Daugavpils Municipality': ['Daugavpils'],
  'Dobele Municipality': ['Dobele'],
  'Dundaga Municipality': ['Dundaga'],
  'Durbe Municipality': ['Lieģi'],
  'Engure Municipality': ['Smārde'],
  'Ērgļi Municipality': ['Ērgļi'],
  'Garkalne Municipality': ['Garkalne'],
  'Grobiņa Municipality': ['Grobiņa'],
  'Gulbene Municipality': ['Gulbene'],
  'Iecava Municipality': ['Iecava'],
  'Ikšķile Municipality': ['Ikšķile'],
  'Ilūkste Municipality': ['Ilūkste'],
  'Inčukalns Municipality': ['Inčukalns', 'Vangaži'],
  'Jaunjelgava Municipality': ['Jaunjelgava'],
  'Jaunpils Municipality': ['Jaunpils'],
  'Jēkabpils Municipality': ['Jēkabpils', 'Krustpils'],
  Jelgava: ['Jelgava'],
  'Jelgava Municipality': ['Tīreļi'],
  Jūrmala: ['Jūrmala'],
  'Kandava Municipality': ['Kandava'],
  'Kārsava Municipality': ['Kārsava'],
  'Ķegums Municipality': ['Ķegums'],
  'Ķekava Municipality': ['Baloži', 'Ķekava'],
  'Kocēni Municipality': ['Kocēni'],
  'Koknese Municipality': ['Koknese'],
  'Krāslava Municipality': ['Krāslava'],
  'Kuldīga Municipality': ['Kuldīga'],
  'Lielvārde Municipality': ['Lielvārde'],
  Liepāja: ['Karosta', 'Liepāja'],
  'Līgatne Municipality': ['Līgatne'],
  'Limbaži Municipality': ['Limbaži'],
  'Līvāni Municipality': ['Līvāni'],
  'Lubāna Municipality': ['Lubāna'],
  'Ludza Municipality': ['Ludza'],
  'Madona Municipality': ['Madona'],
  'Mālpils Municipality': ['Mālpils'],
  'Mārupe Municipality': ['Mārupe'],
  'Mazsalaca Municipality': ['Mazsalaca'],
  'Naukšēni Municipality': ['Naukšēni'],
  'Nereta Municipality': ['Nereta'],
  'Nīca Municipality': ['Nīca'],
  'Ogre Municipality': ['Jumprava', 'Ogre'],
  'Olaine Municipality': ['Olaine'],
  'Ozolnieki Municipality': ['Ozolnieki'],
  'Pārgauja Municipality': ['Stalbe'],
  'Pāvilosta Municipality': ['Pāvilosta'],
  'Pļaviņas Municipality': ['Pļaviņas'],
  'Preiļi Municipality': ['Jaunaglona', 'Preiļi'],
  'Priekule Municipality': ['Priekule'],
  'Priekuļi Municipality': ['Priekuļi'],
  'Rauna Municipality': ['Rauna'],
  Rēzekne: ['Rēzekne'],
  'Riebiņi Municipality': ['Riebiņi'],
  Riga: ['Bolderaja', 'Daugavgrīva', 'Jaunciems', 'Mežaparks', 'Riga'],
  'Roja Municipality': ['Roja'],
  'Ropaži Municipality': ['Ropaži'],
  'Rucava Municipality': ['Rucava'],
  'Rugāji Municipality': ['Rugāji'],
  'Rūjiena Municipality': ['Rūjiena'],
  'Rundāle Municipality': ['Pilsrundāle'],
  'Salacgrīva Municipality': ['Ainaži', 'Salacgrīva'],
  'Salaspils Municipality': ['Salaspils'],
  'Saldus Municipality': ['Saldus'],
  'Saulkrasti Municipality': ['Saulkrasti'],
  'Sēja Municipality': ['Engure', 'Tukums'],
  'Sigulda Municipality': ['Sigulda'],
  'Skrīveri Municipality': ['Skrīveri'],
  'Skrunda Municipality': ['Skrunda'],
  'Smiltene Municipality': ['Smiltene'],
  'Stopiņi Municipality': ['Ulbroka'],
  'Strenči Municipality': ['Seda', 'Strenči'],
  'Talsi Municipality': ['Sabile', 'Stende', 'Talsi', 'Valdemārpils'],
  'Tērvete Municipality': ['Tērvete', 'Zelmeņi'],
  'Vaiņode Municipality': ['Vaiņode'],
  'Valka Municipality': ['Valka'],
  Valmiera: ['Valmiera'],
  'Varakļāni Municipality': ['Varakļāni'],
  'Vārkava Municipality': ['Vecvārkava'],
  'Vecpiebalga Municipality': ['Vecpiebalga'],
  'Vecumnieki Municipality': ['Vecumnieki'],
  Ventspils: ['Ventspils'],
  'Ventspils Municipality': ['Piltene'],
  'Viesīte Municipality': ['Viesīte'],
  'Viļaka Municipality': ['Viļaka'],
  'Viļāni Municipality': ['Viļāni'],
  'Zilupe Municipality': ['Zilupe'],
};
