export const LIBYA_DISTRICTS_CITIES = {
  'Al Wahat District': [
    'Ajdabiya',
    'Al Burayqah',
    'Awjilah',
    'Az Zuwaytīnah',
    'Gialo',
    'Marādah',
  ],
  Benghazi: ['Benghazi', 'Qaryat Sulūq'],
  'Derna District': ['Al Qubbah', 'Darnah'],
  'Ghat District': ['Ghat'],
  'Jabal al Akhdar': ['Al Bayḑā’'],
  'Jabal al Gharbi District': [
    'Gharyan',
    'Giado',
    'Mizdah',
    'Yafran',
    'Zintan',
  ],
  Jafara: ['Al ‘Azīzīyah'],
  Jufra: ['Hūn', 'Waddān'],
  'Kufra District': ['Al Jawf', 'At Tāj'],
  'Marj District': ['Al Abyār', 'Al Marj', 'Tūkrah'],
  'Misrata District': ['Bani Walid', 'Mişrātah', 'Zliten'],
  Murqub: ['Al Khums', 'Masallātah', 'Tarhuna'],
  'Murzuq District': ['Al Qaţrūn', 'Murzuq'],
  'Nalut District': ['Ghadāmis', 'Nālūt'],
  'Nuqat al Khams': ['Al Ajaylat', 'Zalţan', 'Zuwārah'],
  'Sabha District': ['Al Jadīd', 'Sabhā'],
  'Sirte District': ['Qasr Abu Hadi', 'Sirte'],
  'Tripoli District': ['Tagiura', 'Tripoli'],
  'Wadi al Hayaa District': ['Ubari'],
  'Wadi al Shatii District': ['Brak', 'Idrī'],
  'Zawiya District': ['Az Zāwīyah', 'Şabrātah', 'Şurmān', 'Zawiya'],
};
