export const MOROCCO_REGIONS_CITIES = {
  'Assa-Zag (EH-partial)': [
    'Agadir',
    'Agadir Melloul',
    'Agadir-Ida-ou-Tnan',
    'Aoulouz',
    'Aourir',
    'Arazane',
    'Argana',
    'Bigoudine',
    'Chtouka-Ait-Baha',
    'Inezgane',
    'Inezgane-Ait Melloul',
    'Ouijjane',
    'Oulad Teïma',
    'Reggada',
    'Sidi Ifni',
    'Tadrart',
    'Tafraout',
    'Taghazout',
    'Taliouine',
    'Tamri',
    'Tanalt',
    'Taroudannt',
    'Taroudant',
    'Tarsouat',
    'Tata',
    'Tiznit',
  ],
  'Casablanca-Settat': [
    'Azemmour',
    'Benslimane',
    'Berrechid',
    'Berrechid Province',
    'Boulaouane',
    'Bouskoura',
    'Bouznika',
    'Casablanca',
    'El Jadid',
    'El-Jadida',
    'Mediouna',
    'Mohammedia',
    'Nouaceur',
    'Oualidia',
    'Oulad Frej',
    'Settat',
    'Settat Province',
    'Sidi Bennour',
    'Sidi Smai’il',
    'Tit Mellil',
    'Zawyat an Nwaçer',
  ],
  'Drâa-Tafilalet': [
    'Agdz',
    'Alnif',
    'Aoufous',
    'Arfoud',
    'Errachidia',
    'Imilchil',
    'Jebel Tiskaouine',
    'Jorf',
    'Kelaat Mgouna',
    'Mhamid',
    'Midelt',
    'Ouarzazat',
    'Ouarzazate',
    'Reçani',
    'Taznakht',
    'Telouet',
    'Tinghir',
    'Tinghir Province',
    'Zagora',
  ],
  'Fès-Meknès': [
    'Aïn Leuh',
    'Aknoul',
    'Almis Marmoucha',
    'Azrou',
    'Bhalil',
    'Bouarouss',
    'Boulemane',
    'El Hajeb',
    'El-Hajeb',
    'Fes',
    'Fès al Bali',
    'Galaz',
    'Ghouazi',
    'Guercif',
    'Ifrane',
    'Meknes',
    'Missour',
    'Moulay Bouchta',
    'Moulay-Yacoub',
    'Oued Amlil',
    'Oulad Tayeb',
    'Ourtzagh',
    'Sefrou',
    'Tahla',
    'Talzemt',
    'Taounate',
    'Taza',
    'Tmourghout',
  ],
  'Guelmim-Oued Noun (EH-partial)': [
    'Assa-Zag',
    'Guelmim',
    'Sidi Ifni',
    'Tan-Tan',
  ],
  Kénitra: [
    'Arbaoua',
    'Had Kourt',
    'Kenitra',
    'Kenitra Province',
    'Khemisset',
    'Mechraa Bel Ksiri',
    'Oulmes',
    'Rabat',
    'Sale',
    'Sidi Bousber',
    'Sidi Qacem',
    'Sidi Redouane',
    'Sidi Slimane',
    'Sidi Yahia El Gharb',
    'Sidi-Kacem',
    'Skhirate',
    'Skhirate-Temara',
    'Souq Larb’a al Gharb',
    'Temara',
    'Teroual',
    'Tiflet',
  ],
  Khénifra: [
    'Aguelmous',
    'Al Fqih Ben Çalah',
    'Azilal',
    'Azilal Province',
    'Beni Mellal',
    'Beni-Mellal',
    'Boujniba',
    'Bzou',
    'Dar Ould Zidouh',
    'Demnate',
    'El Ksiba',
    'Fquih Ben Salah Province',
    'Ifrane',
    'Isseksi',
    'Itzer',
    'Kasba Tadla',
    'Kerrouchen',
    'Khenifra',
    'Khouribga',
    'Khouribga Province',
    'Midelt',
    'Ouaoula',
    'Oued Zem',
    'Sidi Jaber',
    'Timoulilt',
    'Zawyat ech Cheïkh',
  ],
  "L'Oriental": [
    'Ahfir',
    'Aïn Beni Mathar',
    'Al Aaroui',
    'Berkane',
    'Bouarfa',
    'Debdou',
    'Driouch Province',
    'El Aïoun',
    'Figuig',
    'Guercif Province',
    'Jerada',
    'Madagh',
    'Midar',
    'Nador',
    'Oujda-Angad',
    'Saidia',
    'Selouane',
    'Taourirt',
    'Tiztoutine',
    'Zaïo',
  ],
  'Laâyoune-Sakia El Hamra (EH-partial)': [
    'Akhfennir',
    'Boujdour',
    'Es-Semara',
    'Gueltat Zemmour',
    'Laayoune',
    'Smara',
    'Tarfaya',
  ],
  'Oued Ed-Dahab (EH)': ['Aousserd', 'Imlili', 'Oued-Ed-Dahab'],
  Safi: [
    'Abadou',
    'Adassil',
    'Al-Haouz',
    'Bouabout',
    'Chichaoua',
    'Essaouira',
    'Kelaa-Des-Sraghna',
    'Marrakech',
    'Marrakesh',
    'Oukaïmedene',
    'Rehamna',
    'Safi',
    'Setti Fatma',
    'Sidi Rahhal',
    'Smimou',
    'Tamanar',
    'Taouloukoult',
    'Tidili Mesfioua',
    'Timezgadiouine',
    'Youssoufia',
    'Zerkten',
  ],
  'Tanger-Tétouan-Al Hoceïma': [
    'Al Hoceïma',
    'Al-Hoceima',
    'Asilah',
    'Bni Bouayach',
    'Brikcha',
    'Cap Negro II',
    'Chefchaouen Province',
    'Chefchaouene',
    'Derdara',
    'Fahs-Anjra',
    'Fnidek',
    'Imzouren',
    'Ksar El Kebir',
    'Larache',
    "M'Diq-Fnideq",
    'Martil',
    'Oued Laou',
    'Ouezzane',
    'Ouezzane Province',
    'Senada',
    'Tamorot',
    'Tanger-Assilah',
    'Tangier',
    'Targuist',
    'Tetouan',
    'Tirhanimîne',
    'Zinat',
    'Zoumi',
  ],
};
