export const MOLDOVA_REGIONS_CITIES = {
  'Anenii Noi District': ['Anenii Noi', 'Varniţa'],
  'Bălți Municipality': ['Bălţi'],
  'Basarabeasca District': ['Basarabeasca'],
  'Bender Municipality': ['Bender'],
  'Briceni District': ['Briceni'],
  'Cahul District': ['Cahul', 'Giurgiuleşti'],
  'Călărași District': ['Călăraşi'],
  'Cantemir District': ['Cantemir', 'Iargara', 'Vişniovca'],
  'Căușeni District': ['Căuşeni', 'Chiţcani'],
  'Chișinău Municipality': [
    'Chisinau',
    'Ciorescu',
    'Cricova',
    'Sîngera',
    'Stăuceni',
    'Vadul lui Vodă',
    'Vatra',
  ],
  'Cimișlia District': ['Cimişlia'],
  'Criuleni District': ['Criuleni'],
  'Dondușeni District': ['Briceni', 'Donduşeni'],
  'Drochia District': ['Drochia'],
  'Dubăsari District': ['Cocieri', 'Ustia'],
  'Edineț District': ['Edineţ'],
  'Fălești District': ['Fălești'],
  'Florești District': ['Floreşti', 'Ghindești', 'Mărculeşti'],
  Gagauzia: ['Bugeac', 'Ceadîr-Lunga', 'Comrat', 'Vulcăneşti'],
  'Glodeni District': ['Glodeni'],
  'Hîncești District': ['Dancu', 'Hînceşti'],
  'Ialoveni District': ['Ialoveni'],
  'Nisporeni District': ['Nisporeni'],
  'Ocnița District': ['Ocniţa', 'Otaci'],
  'Orhei District': ['Orhei'],
  'Rezina District': ['Rezina', 'Saharna'],
  'Rîșcani District': ['Rîşcani'],
  'Sîngerei District': ['Bilicenii Vechi', 'Biruinţa', 'Sîngerei'],
  'Șoldănești District': ['Şoldăneşti'],
  'Soroca District': ['Soroca'],
  'Ștefan Vodă District': ['Ştefan Vodă'],
  'Strășeni District': ['Bucovăţ', 'Strășeni'],
  'Taraclia District': ['Taraclia', 'Tvardița'],
  'Telenești District': ['Mîndreşti', 'Teleneşti'],
  'Transnistria autonomous territorial unit': [
    'Camenca',
    'Crasnoe',
    'Dnestrovsc',
    'Dubăsari',
    'Hryhoriopol',
    'Maiac',
    'Pervomaisc',
    'Rîbniţa',
    'Slobozia',
    'Tiraspol',
    'Tiraspolul Nou',
  ],
  'Ungheni District': ['Ungheni'],
};
