export const MONTENEGRO_REGIONS_CITIES = {
  'Andrijevica Municipality': ['Andrijevica'],
  'Bar Municipality': ['Bar', 'Stari Bar', 'Šušanj', 'Sutomore'],
  'Berane Municipality': ['Berane'],
  'Bijelo Polje Municipality': ['Bijelo Polje'],
  'Budva Municipality': ['Budva', 'Petrovac na Moru'],
  'Danilovgrad Municipality': ['Danilovgrad', 'Spuž'],
  'Gusinje Municipality': ['Gusinje'],
  'Kolašin Municipality': ['Kolašin'],
  'Kotor Municipality': ['Dobrota', 'Kotor', 'Prčanj', 'Risan'],
  'Mojkovac Municipality': ['Mojkovac'],
  'Nikšić Municipality': ['Nikšić'],
  'Old Royal Capital Cetinje': ['Cetinje'],
  'Plav Municipality': ['Plav'],
  'Pljevlja Municipality': ['Pljevlja'],
  'Plužine Municipality': ['Plužine'],
  'Podgorica Municipality': [
    'Golubovci',
    'Goričani',
    'Mataguži',
    'Mojanovići',
    'Podgorica',
    'Tuzi',
  ],
  'Rožaje Municipality': ['Rožaje'],
  'Šavnik Municipality': ['Šavnik'],
  'Tivat Municipality': ['Tivat'],
  'Ulcinj Municipality': ['Ulcinj'],
  'Žabljak Municipality': ['Žabljak'],
};
