export const NORTH_MACEDONIA_REGIONS_CITIES = {
  'Aračinovo Municipality': ['Арачиново'],
  'Berovo Municipality': ['Berovo', 'Rusinovo', 'Vladimirovo'],
  'Bitola Municipality': [
    'Bistrica',
    'Bitola',
    'Capari',
    'Dolno Orizari',
    'Gorno Orizari',
    'Kukurečani',
    'Logovardi',
  ],
  'Bogdanci Municipality': ['Bogdanci', 'Stojakovo'],
  'Bogovinje Municipality': [
    'Bogovinje',
    'Dolno Palčište',
    'Gradec',
    'Kamenjane',
  ],
  'Bosilovo Municipality': ['Bosilovo', 'Ilovica', 'Sekirnik'],
  'Brvenica Municipality': ['Brvenica', 'Čelopek', 'Gurgurnica', 'Miletino'],
  'Butel Municipality': ['Butel', 'Radishani'],
  'Čair Municipality': ['Čair'],
  'Čaška Municipality': ['Bogomila', 'Čaška'],
  'Centar Župa Municipality': ['Centar Župa'],
  'Češinovo-Obleševo Municipality': ['Češinovo', 'Oblesevo'],
  'Čučer-Sandevo Municipality': ['Чучер - Сандево'],
  'Debarca Municipality': ['Belčišta', 'Mešeišta'],
  'Delčevo Municipality': ['Delcevo'],
  'Demir Hisar Municipality': ['Demir Hisar', 'Slepče', 'Sopotnica'],
  'Demir Kapija Municipality': ['Demir Kapija'],
  'Dojran Municipality': ['Star Dojran'],
  'Dolneni Municipality': [
    'Crnilište',
    'Desovo',
    'Dolneni',
    'Lažani',
    'Žitoše',
  ],
  'Gazi Baba Municipality': ['Cresevo'],
  'Gevgelija Municipality': ['Gevgelija', 'Miravci'],
  'Gjorče Petrov Municipality': ['Gjorče Petro'],
  'Gostivar Municipality': [
    'Cegrane',
    'Dolna Banjica',
    'Forino',
    'Gostivar',
    'Srbinovo',
    'Vrutok',
  ],
  'Gradsko Municipality': ['Gradsko'],
  'Greater Skopje': ['Bojane', 'Dračevo', 'Ljubin', 'Saraj', 'Usje'],
  'Ilinden Municipality': [
    'Ilinden',
    'Kadino',
    'Marino',
    'Miladinovci',
    'Идризово',
    'Јурумлери',
  ],
  'Jegunovce Municipality': ['Jegunovce', 'Vratnica'],
  Karbinci: ['Karbinci'],
  'Karpoš Municipality': ['Skopje'],
  'Kavadarci Municipality': ['Kavadarci', 'Vataša'],
  'Kičevo Municipality': [
    'Drugovo',
    'Kičevo',
    'Srbica',
    'Strelci',
    'Tuin',
    'Vraneštica',
    'Zajas',
  ],
  'Kisela Voda Municipality': ['Kisela Voda'],
  'Kočani Municipality': ['Kochani', 'Orizari'],
  'Konče Municipality': ['Konče'],
  'Kratovo Municipality': ['Kratovo'],
  'Kriva Palanka Municipality': ['Kriva Palanka'],
  'Krivogaštani Municipality': ['Krivogashtani', 'Obršani', 'Клечовце'],
  'Kruševo Municipality': ['Bučin', 'Krusevo'],
  'Kumanovo Municipality': ['Bedinje', 'Kumanovo', 'Romanovci'],
  'Lipkovo Municipality': [
    'Izvor',
    'Lipkovo',
    'Lojane',
    'Matejce',
    'Otlja',
    'Vaksince',
    'Слупчане',
  ],
  'Lozovo Municipality': ['Lozovo'],
  'Makedonska Kamenica Municipality': ['Makedonska Kamenica'],
  'Makedonski Brod Municipality': ['Makedonski Brod', 'Samokov'],
  'Mavrovo and Rostuša Municipality': ['Rostusa'],
  'Mogila Municipality': ['Beranci', 'Dobruševo', 'Dolno Srpci', 'Mogila'],
  'Negotino Municipality': ['Negotino'],
  'Novaci Municipality': ['Novaci'],
  'Novo Selo Municipality': ['Novo Selo', 'Sušica'],
  'Ohrid Municipality': ['Kosel', 'Ohrid', 'Ohrid Opština'],
  'Pehčevo Municipality': ['Pehčevo'],
  'Petrovec Municipality': ['Sredno Konjare', 'Петровец'],
  'Plasnica Municipality': ['Lisičani', 'Plasnica'],
  'Prilep Municipality': ['Kanatlarci', 'Markov Grad', 'Prilep', 'Topolčani'],
  'Probištip Municipality': ['Probishtip', 'Zletovo'],
  'Radoviš Municipality': ['Oraovica', 'Podareš', 'Radovis'],
  'Rankovce Municipality': ['Ранковце'],
  'Resen Municipality': ['Grnčari', 'Jankovec', 'Krani', 'Resen'],
  'Rosoman Municipality': ['Rosoman'],
  'Saraj Municipality': ['Bukovik', 'Grčec', 'Kondovo', 'Krušopek'],
  'Sopište Municipality': ['Сопиште'],
  'Staro Nagoričane Municipality': ['Старо Нагоричане'],
  'Štip Municipality': ['Shtip'],
  'Struga Municipality': [
    'Delogožda',
    'Labunista',
    'Lukovo',
    'Mislesevo',
    'Oktisi',
    'Radolista',
    'Struga',
    'Velesta',
  ],
  'Strumica Municipality': ['Kuklis', 'Murtino', 'Strumica', 'Veljusa'],
  'Studeničani Municipality': [
    'Batinci',
    'Dolno Količani',
    'Morani',
    'Studeničane',
  ],
  'Šuto Orizari Municipality': ['Šuto Orizare'],
  'Sveti Nikole Municipality': ['Gorobinci', 'Sveti Nikole'],
  'Tearce Municipality': ['Nerašte', 'Orashac', 'Pršovce', 'Slatino', 'Tearce'],
  'Tetovo Municipality': [
    'Dobrošte',
    'Džepčište',
    'Golema Rečica',
    'Pirok',
    'Poroj',
    'Selce',
    'Šipkovica',
    'Tetovo',
  ],
  'Valandovo Municipality': ['Pirava', 'Valandovo'],
  'Vasilevo Municipality': ['Vasilevo'],
  'Veles Municipality': ['Gorno Orizari', 'Ivankovci', 'Veles'],
  'Vevčani Municipality': ['Vevčani'],
  'Vinica Municipality': ['Blatec', 'Gradec', 'Vinica'],
  'Vrapčište Municipality': ['Dobri Dol', 'Negotino', 'Vrapčište'],
  'Zelenikovo Municipality': ['Zelenikovo'],
  'Želino Municipality': [
    'Dobarce',
    'Larce',
    'Sedlarevo',
    'Strimnica',
    'Zelino',
  ],
  'Zrnovci Municipality': ['Zrnovci'],
};
