export const MALI_REGIONS_CITIES = {
  Bamako: ['Bamako'],
  'Gao Region': ['Ansongo', 'Cercle de Bourem', 'Gao', 'Gao Cercle', 'Inékar'],
  'Kayes Region': ['Bafoulabé', 'Kayes', 'Kita', 'Kokofata', 'Sagalo'],
  'Kidal Region': ['Abeïbara', 'Cercle d’Abeïbara', 'Kidal'],
  'Koulikoro Region': ['Banamba', 'Kangaba', 'Kati', 'Kolokani', 'Koulikoro'],
  'Mopti Region': [
    'Bandiagara',
    'Djénné',
    'Douentza',
    'Douentza Cercle',
    'Mopti',
    'Ténenkou',
  ],
  'Ségou Region': [
    'Baroueli',
    'Cercle de San',
    'Ké-Macina',
    'Kinmparana',
    'Markala',
    'San',
    'Ségou',
    'Sokolo',
  ],
  'Sikasso Region': [
    'Bougouni',
    'Kolondiéba',
    'Koutiala',
    'Koutiala Cercle',
    'Ntossoni',
    'Sikasso',
    'Yorosso',
  ],
  'Tombouctou Region': [
    'Araouane',
    'Cercle de Goundam',
    'Dire',
    'Goundam',
    'Gourma-Rharous Cercle',
    'Niafunké',
    'Timbuktu',
  ],
};
