export const MYANMAR_STATES_CITIES = {
  'Ayeyarwady Region': [
    'Bogale',
    'Hinthada',
    'Kyaiklat',
    'Maubin',
    'Mawlamyinegyunn',
    'Myanaung',
    'Nyaungdon',
    'Pathein',
    'Pyapon',
    'Wakema',
  ],
  Bago: [
    'Bago',
    'Letpandan',
    'Nyaunglebin',
    'Paungde',
    'Pyay',
    'Pyu',
    'Taungoo',
    'Thanatpin',
    'Tharyarwady',
  ],
  'Chin State': ['Falam', 'Hakha'],
  'Kachin State': ['Bhamo', 'Myitkyina'],
  'Kayah State': ['Loikaw'],
  'Kayin State': [
    'Dellok',
    'Hpa-An',
    'Klonhtoug',
    'Kyain Seikgyi Township',
    'Mikenaungea',
    'Myawadi',
    'Pulei',
    'Tagondaing',
    'Tamoowoug',
  ],
  'Magway Region': [
    'Chauk',
    'Magway',
    'Minbu',
    'Myaydo',
    'Pakokku',
    'Taungdwingyi',
    'Thayetmyo',
    'Yenangyaung',
  ],
  'Mandalay Region': [
    'Kyaukse',
    'Mandalay',
    'Meiktila',
    'Mogok',
    'Myingyan',
    'Nyaungshwe',
    'Pyin Oo Lwin',
    'Yamethin',
  ],
  'Mon State': [
    'Kyaikkami',
    'Kyaikto',
    'Martaban',
    'Mawlamyine',
    'Mudon',
    'Thaton',
  ],
  'Naypyidaw Union Territory': ['Nay Pyi Taw', 'Pyinmana'],
  'Rakhine State': ['Sittwe'],
  'Sagaing Region': ['Mawlaik', 'Monywa', 'Sagaing', 'Shwebo'],
  'Shan State': ['Lashio', 'Tachilek', 'Taunggyi'],
  'Tanintharyi Region': ['Dawei', 'Kawthoung', 'Myeik'],
  'Yangon Region': ['Kanbe', 'Kayan', 'Syriam', 'Thongwa', 'Twante', 'Yangon'],
};
