export const MONGOLIA_PROVINCES_CITIES = {
  'Arkhangai Province': ['Tsetserleg'],
  'Bayan-Ölgii Province': ['Altay', 'Ölgii', 'Tsengel'],
  'Bayankhongor Province': ['Bayanhongor'],
  'Bulgan Province': ['Bulgan'],
  'Darkhan-Uul Province': ['Darhan'],
  'Dornod Province': ['Choibalsan', 'Ereencav'],
  'Dundgovi Province': ['Mandalgovi'],
  'Govi-Altai Province': ['Altai'],
  'Govisümber Province': ['Choyr'],
  'Khentii Province': ['Undurkhaan'],
  'Khovd Province': ['Khovd', 'Möst', 'Üyönch'],
  'Khövsgöl Province': ['Hanh', 'Murun-kuren', 'Tsengel', 'Turt'],
  'Ömnögovi Province': ['Dalandzadgad', 'Hanhongor', 'Nomgon Sum'],
  'Orkhon Province': ['Erdenet'],
  'Övörkhangai Province': [
    'Arvayheer',
    'Harhorin',
    'Hovd',
    'Kharkhorin',
    'Nariynteel',
  ],
  'Selenge Province': ['Dzüünharaa', 'Sühbaatar'],
  'Sükhbaatar Province': ['Baruun-Urt'],
  'Töv Province': ['Dzuunmod', 'Möngönmorĭt', 'Ulaanhudag', 'Зуунмод'],
  'Uvs Province': ['Ulaangom'],
  'Zavkhan Province': ['Uliastay'],
};
