export const MAURITANIA_REGIONS_CITIES = {
  Adrar: ['Atar', 'Azougui', 'Chingueṭṭi', 'Ksar el Khali'],
  Assaba: ['Barkéwol', 'Kiffa'],
  Brakna: ['’Elb el Jmel', 'Aleg', 'Bofal', 'Sori Malé'],
  'Dakhlet Nouadhibou': ['Cansado', 'Iouik', 'Nouadhibou'],
  Gorgol: ['Kaédi'],
  Guidimaka: ['Sélibaby'],
  'Hodh Ech Chargui': ['Diade', 'Kataouane', 'Néma', 'Timbedra'],
  'Hodh El Gharbi': ['Aioun', 'Ayoun el Atrous', 'Togba'],
  Inchiri: ['Akjoujt'],
  'Nouakchott-Nord': ['Dar-Naim', 'Teyarett', 'Toujouonine'],
  'Nouakchott-Ouest': ['Ksar', 'Sebkha', 'Tevragh-Zeina'],
  'Nouakchott-Sud': ['Arafat', 'Riyad'],
  'Tiris Zemmour': ['Ain Ben Tili', 'Chegga', 'Fderîck', 'Zouérat', 'Zouerate'],
  Trarza: ['Legat', 'Rosso', 'Tékane'],
};
