export const MALTA_REGIONS_CITIES = {
  Attard: ['Attard'],
  Balzan: ['Balzan'],
  Birgu: ['Birgu (Vittoriosa)'],
  Birkirkara: ['Birkirkara', 'Fleur De Lys', 'Swatar'],
  Birżebbuġa: ['Birżebbuġa', 'Ħal Far'],
  Cospicua: ['Cospicua'],
  Dingli: ['Dingli'],
  Fgura: ['Fgura'],
  Floriana: ['Floriana'],
  Fontana: ['Fontana'],
  Għajnsielem: ['Għajnsielem', 'Ħal Għargħur'],
  Għargħur: ['Ħal Għaxaq'],
  Għasri: ['Gudja'],
  Għaxaq: ['Gżira'],
  Gżira: ['Għarb'],
  Ħamrun: ["Blata l' Bajda", 'Ħamrun'],
  Iklin: ['L-Iklin'],
  Kalkara: ['Imġarr', 'Mġarr'],
  Kerċem: ['Mqabba'],
  Kirkop: ['Imsida', 'Kirkop'],
  Lija: ['Ħal Lija', 'Imtarfa'],
  Luqa: ['Ħal Luqa', 'Ħal Safi', 'Senglea'],
  Marsa: ['Kalkara'],
  Marsaskala: ['Kerċem', 'Marsaskala'],
  Marsaxlokk: ['Marsaxlokk'],
  Mellieħa: ['Manikata'],
  Mġarr: ['Marsa'],
  Mosta: ['Bidnija'],
  Msida: ['Mellieħa'],
  Munxar: ['Munxar'],
  Nadur: ['Nadur'],
  Naxxar: ['Baħar iċ-Ċagħaq', 'Magħtab', 'Naxxar', 'Salina'],
  Paola: ['Paola'],
  Pembroke: ['Pembroke'],
  Pietà: ['Pietà'],
  Qala: ['Qala'],
  Qormi: ['Qormi'],
  Qrendi: ['Qrendi'],
  Rabat: ['Baħrija', 'Binġemma'],
  'San Ġwann': ["San Ġiljan (St. Julian's)"],
  'San Lawrenz': ['San Lawrenz'],
  Sannat: ['San Pawl il-Baħar', 'Sannat'],
  'Santa Luċija': ['Santa Venera'],
  Senglea: ['Imdina'],
  Siġġiewi: ['Siġġiewi'],
  Sliema: ['Sliema'],
  "St. Julian's": ['Paceville', 'San Ġwann'],
  "St. Paul's Bay": [
    'Buġibba',
    'Burmarrad',
    'Mosta',
    'Qawra',
    'Santa Luċija',
    'Santa Luċija, Gozo',
    'Wardija',
    'Xemxija',
  ],
  Swieqi: ['Madliena', 'Swieqi'],
  "Ta' Xbiex": ['Ta’ Xbiex'],
  Tarxien: ['Ħal Tarxien'],
  Valletta: ['Valletta'],
  Victoria: ['Rabat', 'Victoria'],
  Xagħra: ['Xagħra'],
  Xewkija: ['Xewkija'],
  Xgħajra: ['Xgħajra'],
  Żabbar: ['Żabbar'],
  'Żebbuġ Gozo': ['Ħaż-Żebbuġ'],
  'Żebbuġ Malta': ['Żebbuġ'],
  Żejtun: ['Żejtun'],
  Żurrieq: ['Żurrieq'],
};
