export const MALDIVES_ATOLLS_ISLANDS = {
  'Addu Atoll': ['Hithadhoo', 'Meedhoo'],
  'Dhaalu Atoll': ['Kudahuvadhoo'],
  'Gaafu Alif Atoll': ['Viligili'],
  'Gaafu Dhaalu Atoll': ['Thinadhoo'],
  'Gnaviyani Atoll': ['Fuvahmulah'],
  'Haa Alif Atoll': ['Dhidhdhoo'],
  'Haa Dhaalu Atoll': ['Kulhudhuffushi'],
  'Kaafu Atoll': ['Guraidhoo', 'Hulhumale', 'Maafushi', 'Male'],
  'Laamu Atoll': ['Fonadhoo'],
  'Lhaviyani Atoll': ['Naifaru'],
  'Meemu Atoll': ['Muli'],
  'Noonu Atoll': ['Manadhoo'],
  'Raa Atoll': ['Ugoofaaru'],
  'Shaviyani Atoll': ['Funadhoo'],
  'South Central Province': ['Mahibadhoo'],
  'Thaa Atoll': ['Veymandoo'],
  'Vaavu Atoll': ['Felidhoo'],
};
// {
//   'Alifu Alifu Atoll': [
//     'Rasdhoo',
//     'Ukulhas',
//     'Thoddoo',
//     'Mathiveri',
//     'Bodufolhudhoo',
//     'Feridhoo',
//     'Kudafolhudhoo',
//     'Maagaa',
//   ],
//   'Alifu Dhaalu Atoll': [
//     'Mahibadhoo',
//     'Dhigurah',
//     'Omadhoo',
//     'Dhangethi',
//     'Hangnaameedhoo',
//     'Maamigili',
//     'Fenfushi',
//   ],
//   'Baa Atoll': [
//     'Eydhafushi',
//     'Dharavandhoo',
//     'Thulhaadhoo',
//     'Maalhos',
//     'Goidhoo',
//     'Kamadhoo',
//     'Hithaadhoo',
//   ],
//   'Dhaalu Atoll': [
//     'Kudahuvadhoo',
//     'Meedhoo',
//     'Rinbudhoo',
//     'Maaenboodhoo',
//     'Vaanee',
//     'Hulhudheli',
//     'Bandidhoo',
//   ],
//   'Faafu Atoll': [
//     'Nilandhoo',
//     'Magoodhoo',
//     'Dharanboodhoo',
//     'Feeali',
//     'Bileddhoo',
//     'Fiyoaree',
//   ],
//   'Gaafu Alifu Atoll': [
//     'Vilingili',
//     'Maamendhoo',
//     'Dhevvadhoo',
//     'Kolamaafushi',
//     'Kondey',
//     'Gemanafushi',
//     'Nilandhoo',
//   ],
//   'Gaafu Dhaalu Atoll': [
//     'Thinadhoo',
//     'Fares-Maathodaa',
//     'Vaadhoo',
//     'Fiyoaree',
//     'Gadhdhoo',
//     'Kanduhulhudhoo',
//     'Rathafandhoo',
//   ],
//   'Gnaviyani Atoll': ['Fuvahmulah'],
//   'Haa Alifu Atoll': [
//     'Dhidhdhoo',
//     'Ihavandhoo',
//     'Utheemu',
//     'Kelaa',
//     'Thakandhoo',
//     'Filladhoo',
//     'Molhadhoo',
//   ],
//   'Haa Dhaalu Atoll': [
//     'Kulhudhuffushi',
//     'Nolhivaranfaru',
//     'Naivaadhoo',
//     'Hanimaadhoo',
//     'Makunudhoo',
//     'Neykurendhoo',
//     'Finey',
//   ],
//   'Kaafu Atoll': [
//     'Malé',
//     'Hulhumalé',
//     'Villingili',
//     'Himmafushi',
//     'Thulusdhoo',
//     'Dhiffushi',
//     'Guraidhoo',
//   ],
//   'Laamu Atoll': [
//     'Fonadhoo',
//     'Gan',
//     'Maabaidhoo',
//     'Isdhoo',
//     'Kalaidhoo',
//     'Mundoo',
//     'Hithadhoo',
//   ],
//   'Lhaviyani Atoll': [
//     'Naifaru',
//     'Hinnavaru',
//     'Kurendhoo',
//     'Felivaru',
//     'Olhuvelifushi',
//     'Maafilaafushi',
//   ],
//   'Meemu Atoll': [
//     'Muli',
//     'Mulaku',
//     'Dhiggaru',
//     'Maduvvari',
//     'Naalaafushi',
//     'Kolhufushi',
//     'Veyvah',
//   ],
//   'Noonu Atoll': [
//     'Manadhoo',
//     'Velidhoo',
//     'Holhudhoo',
//     'Miladhoo',
//     'Kandoodhoo',
//     'Maafaru',
//     'Magoodhoo',
//   ],
//   'Raa Atoll': [
//     'Ugoofaaru',
//     'Meedhoo',
//     'Alifushi',
//     'Innamaadhoo',
//     'Kinolhas',
//     'Kendhoo',
//     'Kottefaru',
//   ],
//   'Seenu Atoll': [
//     'Hithadhoo',
//     'Feydhoo',
//     'Maradhoo',
//     'Gan',
//     'Hulhudhoo',
//     'Meedhoo',
//     'Maradhoo-Feydhoo',
//   ],
//   'Shaviyani Atoll': [
//     'Funadhoo',
//     'Kanditheemu',
//     'Foakaidhoo',
//     'Narudhoo',
//     'Lhaimagu',
//     'Milandhoo',
//     'Feevah',
//   ],
//   'Thaa Atoll': [
//     'Veymandoo',
//     'Thimarafushi',
//     'Kinbidhoo',
//     'Omadhoo',
//     'Madifushi',
//     'Guraidhoo',
//     'Hirilandhoo',
//   ],
//   'Vaavu Atoll': ['Felidhoo', 'Keyodhoo', 'Thinadhoo', 'Fulidhoo', 'Rakeedhoo'],
// };
