export const MALAWI_REGIONS_CITIES = {
  'Central Region': [
    'Chipoka',
    'Dedza',
    'Dedza District',
    'Dowa',
    'Dowa District',
    'Kasungu',
    'Kasungu District',
    'Lilongwe',
    'Lilongwe District',
    'Mchinji',
    'Mchinji District',
    'Mponela',
    'Nkhotakota',
    'Nkhotakota District',
    'Ntcheu',
    'Ntcheu District',
    'Ntchisi',
    'Ntchisi District',
    'Salima',
    'Salima District',
  ],
  'Northern Region': [
    'Chitipa',
    'Chitipa District',
    'Karonga',
    'Karonga District',
    'Likoma District',
    'Livingstonia',
    'Mzimba',
    'Mzimba District',
    'Mzuzu',
    'Nkhata Bay',
    'Nkhata Bay District',
    'Rumphi',
    'Rumphi District',
  ],
  'Southern Region': [
    'Balaka',
    'Balaka District',
    'Blantyre',
    'Blantyre District',
    'Chikwawa',
    'Chikwawa District',
    'Chiradzulu',
    'Chiradzulu District',
    'Liwonde',
    'Luchenza',
    'Machinga',
    'Machinga District',
    'Mangochi',
    'Mangochi District',
    'Monkey Bay',
    'Mulanje',
    'Mulanje District',
    'Mwanza',
    'Mwanza District',
    'Neno District',
    'Nsanje',
    'Nsanje District',
    'Phalombe',
    'Phalombe District',
    'Thyolo',
    'Thyolo District',
    'Zomba',
    'Zomba District',
  ],
};
