export const MAXICO_STATE_CITY = {
  Aguascalientes: [
    'Aguascalientes',
    'Calvillo',
    'Jesús María',
    'Pabellón de Arteaga',
  ],
  'Baja California': ['Mexicali', 'Tijuana', 'Ensenada', 'Rosarito'],
  'Baja California Sur': [
    'La Paz',
    'Cabo San Lucas',
    'San José del Cabo',
    'Loreto',
  ],
  Campeche: ['Campeche', 'Ciudad del Carmen', 'Champotón', 'Escárcega'],
  Chiapas: [
    'Tuxtla Gutiérrez',
    'San Cristóbal de las Casas',
    'Tapachula',
    'Comitán',
  ],
  Chihuahua: ['Chihuahua', 'Ciudad Juárez', 'Delicias', 'Hidalgo del Parral'],
  Coahuila: ['Saltillo', 'Torreón', 'Monclova', 'Piedras Negras'],
  Colima: ['Colima', 'Manzanillo', 'Tecomán', 'Villa de Álvarez'],
  Durango: ['Durango', 'Gómez Palacio', 'Lerdo', 'Ciudad Lerdo'],
  Guanajuato: ['Guanajuato', 'León', 'Irapuato', 'Celaya'],
  Guerrero: ['Chilpancingo', 'Acapulco', 'Iguala', 'Taxco'],
  Hidalgo: ['Pachuca', 'Tulancingo', 'Tula de Allende', 'Huejutla'],
  Jalisco: ['Guadalajara', 'Zapopan', 'Tlaquepaque', 'Tonalá'],
  'Mexico City': ['Mexico City'],
  'State Of Mexico': ['Toluca', 'Ecatepec', 'Naucalpan', 'Tlalnepantla'],
  Michoacán: ['Morelia', 'Uruapan', 'Zamora', 'Lázaro Cárdenas'],
  Morelos: ['Cuernavaca', 'Cuautla', 'Jiutepec', 'Temixco'],
  Nayarit: ['Tepic', 'Bahía de Banderas', 'Compostela', 'Ixtlán del Río'],
  'Nuevo León': [
    'Monterrey',
    'Guadalupe',
    'San Nicolás de los Garza',
    'San Pedro Garza García',
  ],
  Oaxaca: [
    'Oaxaca',
    'Salina Cruz',
    'Juchitán de Zaragoza',
    'San Juan Bautista Tuxtepec',
  ],
  Puebla: ['Puebla', 'Tehuacán', 'San Martín Texmelucan', 'Atlixco'],
  Querétaro: ['Querétaro', 'San Juan del Río', 'El Marqués', 'Corregidora'],
  'Quintana Roo': ['Chetumal', 'Cancún', 'Playa del Carmen', 'Cozumel'],
  'San Luis Potosí': [
    'San Luis Potosí',
    'Soledad de Graciano Sánchez',
    'Matehuala',
    'Ciudad Valles',
  ],
  Sinaloa: ['Culiacán', 'Mazatlán', 'Los Mochis', 'Guasave'],
  Sonora: ['Hermosillo', 'Ciudad Obregón', 'Nogales', 'San Luis Río Colorado'],
  Tabasco: ['Villahermosa', 'Cárdenas', 'Comalcalco', 'Macuspana'],
  Tamaulipas: ['Ciudad Victoria', 'Reynosa', 'Matamoros', 'Nuevo Laredo'],
  Tlaxcala: ['Tlaxcala', 'Apizaco', 'Huamantla', 'Chiautempan'],
  Veracruz: ['Xalapa', 'Veracruz', 'Coatzacoalcos', 'Orizaba'],
  Yucatán: ['Mérida', 'Valladolid', 'Tizimín', 'Progreso'],
  Zacatecas: ['Zacatecas', 'Guadalupe', 'Fresnillo', 'Jerez'],
};
