export const MALAYSIA_STATES_CITIES = {
  Johor: [
    'Bakri',
    'Batu Pahat',
    'Buloh Kasap',
    'Chaah',
    'Daerah Batu Pahat',
    'Daerah Johor Baharu',
    'Daerah Keluang',
    'Daerah Kota Tinggi',
    'Daerah Mersing',
    'Daerah Muar',
    'Daerah Pontian',
    'Daerah Segamat',
    'Johor Bahru',
    'Kampung Pasir Gudang Baru',
    'Kampung Simpang Renggam',
    'Kelapa Sawit',
    'Kluang',
    'Kota Tinggi',
    'Kulai',
    'Labis',
    'Mersing',
    'Muar',
    'Parit Raja',
    'Pekan Nenas',
    'Pontian Kechil',
    'Segamat',
    'Skudai',
    'Taman Senai',
    'Tangkak',
    'Ulu Tiram',
    'Yong Peng',
  ],
  Kedah: [
    'Alor Setar',
    'Ayer Hangat',
    'Bedong',
    'Gurun',
    'Jitra',
    'Kampung Kilim',
    'Kampung Kok',
    'Kuah',
    'Kuala Kedah',
    'Kuala Teriang',
    'Kulim',
    'Langkawi',
    'Padang Mat Sirat',
    'Sungai Petani',
  ],
  Kelantan: [
    'Gua Musang',
    'Kampong Kadok',
    'Kampong Pangkal Kalong',
    'Kota Bharu',
    'Pasir Mas',
    'Peringat',
    'Tumpat',
  ],
  'Kuala Lumpur': ['Kuala Lumpur'],
  Labuan: ['Labuan'],
  Malacca: [
    'Alor Gajah',
    'Batu Berendam',
    'Bemban',
    'Bukit Rambai',
    'Kampong Masjid Tanah',
    'Kampung Ayer Keroh',
    'Kampung Ayer Molek',
    'Kampung Bukit Baharu',
    'Klebang Besar',
    'Kuala Sungai Baru',
    'Malacca',
    'Pulau Sebang',
    'Sungai Udang',
  ],
  'Negeri Sembilan': [
    'Bahau',
    'Kampung Baharu Nilai',
    'Kuala Pilah',
    'Port Dickson',
    'Seremban',
    'Tampin',
  ],
  Pahang: [
    'Bentong Town',
    'Jerantut',
    'Kampung Bukit Tinggi Bentong',
    'Kampung Tekek',
    'Kuala Lipis',
    'Kuantan',
    'Mentekab',
    'Pekan',
    'Raub',
    'Tanah Rata',
    'Temerluh',
  ],
  Penang: [
    'Batu Feringgi',
    'Bukit Mertajam',
    'Butterworth',
    'George Town',
    'Juru',
    'Kampung Batu Feringgi',
    'Kampung Sungai Ara',
    'Kepala Batas',
    'Nibong Tebal',
    'Perai',
    'Permatang Kuching',
    'Seberang Perai',
    'Tanjung Tokong',
    'Tasek Glugor',
    'Telaga Batu',
  ],
  Perak: [
    'Bagan Serai',
    'Batu Gajah',
    'Bidur',
    'Ipoh',
    'Kampar',
    'Kampong Dungun',
    'Kuala Kangsar',
    'Lumut',
    'Pantai Remis',
    'Parit Buntar',
    'Simpang Empat',
    'Taiping',
    'Tapah Road',
    'Teluk Intan',
  ],
  Perlis: ['Kangar', 'Kuala Perlis', 'Pantai Cenang'],
  Putrajaya: ['Putrajaya'],
  Sabah: [
    'Bandar Labuan',
    'Beaufort',
    'Donggongon',
    'Keningau',
    'Kinarut',
    'Kota Belud',
    'Kota Kinabalu',
    'Kudat',
    'Lahad Datu',
    'Papar',
    'Putatan',
    'Ranau',
    'Sandakan',
    'Semporna',
    'Taman Rajawali',
    'Tawau',
  ],
  Sarawak: [
    'Bintulu',
    'Data Kakus',
    'Kapit',
    'Kuching',
    'Lawas',
    'Lidung Jelo',
    'Limbang',
    'Long Ampan Aing or Abanang',
    'Marudi',
    'Miri',
    'Mukah',
    'Sarikei',
    'Sibu',
    'Simanggang',
  ],
  Selangor: [
    'Ampang',
    'Bagan Pulau Ketam',
    'Banting',
    'Batang Berjuntai',
    'Batu Arang',
    'Jenjarum',
    'Kampong Baharu Balakong',
    'Kampung Baru Subang',
    'Kampung Tanjung Karang',
    'Klang',
    'Kuala Selangor',
    'Kuang',
    'Ladang Seri Kundang',
    'Pelabuhan Klang',
    'Petaling Jaya',
    'Puchong',
    'Putra Heights',
    'Rawang',
    'Semenyih',
    'Serendah',
    'Shah Alam',
    'Subang Jaya',
    'Sungai Besar',
    'Sungai Pelek New Village',
    'Tanjung Sepat',
  ],
  Terengganu: [
    'Cukai',
    'Jertih',
    'Kampung Kuala Besut',
    'Kertih',
    'Kuala Besut',
    'Kuala Terengganu',
    'Marang',
    'Paka',
  ],
};
