export const MOZAMBIQUE_PROVINCES_CITIES = {
  'Cabo Delgado Province': ['Chiure', 'Mocímboa', 'Montepuez', 'Pemba'],
  'Gaza Province': ['Chibuto', 'Chokwé', 'Macia', 'Xai-Xai'],
  'Inhambane Province': ['Inhambane', 'Maxixe'],
  'Manica Province': ['Chimoio'],
  Maputo: ['KaTembe', 'Maputo'],
  'Maputo Province': [
    'Boane District',
    'Concelho de Matola',
    'Magude District',
    'Manhica',
    'Marracuene District',
    'Matola',
    'Matutiune District',
    'Moamba District',
    'Namaacha District',
    'Ressano Garcia',
  ],
  'Nampula Province': [
    'António Enes',
    'Ilha de Moçambique',
    'Mutuáli',
    'Nacala',
    'Nampula',
  ],
  'Niassa Province': ['Cuamba', 'Lichinga', 'Mandimba'],
  'Sofala Province': ['Beira', 'Dondo', 'Nhamatanda District'],
  'Tete Province': ['Tete'],
  'Zambezia Province': ['Alto Molócuè', 'Chinde', 'Quelimane'],
};
