export const NAMIBIA_REGIONS_CITIES = {
  'Erongo Region': [
    'Arandis',
    'Hentiesbaai',
    'Karibib',
    'Omaruru',
    'Otjimbingwe',
    'Swakopmund',
    'Swakopmund Constituency',
    'Usakos',
    'Walvis Bay',
  ],
  'Hardap Region': [
    'Aranos',
    'Hoachanas',
    'Maltahöhe',
    'Mariental',
    'Rehoboth',
  ],
  'Karas Region': [
    'Bethanie',
    'Karasburg',
    'Keetmanshoop',
    'Lüderitz',
    'Oranjemund',
    'Tses',
    'Warmbad',
  ],
  'Kavango East Region': ['Rundu'],
  'Khomas Region': ['Katutura', 'Windhoek'],
  'Kunene Region': [
    'Epupa Constituency',
    'Khorixas',
    'Khorixas Constituency',
    'Opuwo',
    'Opuwo Constituency',
    'Outjo',
    'Sesfontein Constituency',
  ],
  'Ohangwena Region': ['Oshikango'],
  'Omaheke Region': ['Gobabis'],
  'Omusati Region': ['Okahao', 'Ongandjera', 'Outapi'],
  'Oshana Region': ['Ondangwa', 'Ongwediva', 'Oshakati'],
  'Oshikoto Region': ['Omuthiya', 'Tsumeb'],
  'Otjozondjupa Region': [
    'Grootfontein',
    'Okahandja',
    'Okakarara',
    'Otavi',
    'Otjiwarongo',
  ],
  'Zambezi Region': ['Bagani', 'Katima Mulilo'],
};
