export const NIGER_REGIONS_CITIES = {
  'Agadez Region': [
    'Agadez',
    'Alaghsas',
    'Arlit',
    'Bilma',
    'Département de Bilma',
    'Département de Tchirozérine',
  ],
  'Diffa Region': [
    'Département de Diffa',
    'Département de Maïné-Soroa',
    'Département de Nguigmi',
    'Diffa',
    'Maïné Soroa',
    'Nguigmi',
  ],
  'Dosso Region': [
    'Boboye Department',
    'Département de Dogondoutchi',
    'Département de Dosso',
    'Département de Gaya',
    'Département de Loga',
    'Dogondoutchi',
    'Dosso',
    'Gaya',
  ],
  'Maradi Region': [
    'Aguié',
    'Dakoro',
    'Département d’Aguié',
    'Département de Dakoro',
    'Département de Mayahi',
    'Département de Tessaoua',
    'Guidan Roumdji Department',
    'Madarounfa',
    'Maradi',
    'Mayahi',
    'Tessaoua',
    'Tibiri',
  ],
  'Tahoua Region': [
    'Abalak',
    'Birni N Konni',
    'Bouza',
    "Département d' Illéla",
    'Département de Birni Nkonni',
    'Département de Bouza',
    'Département de Keïta',
    'Département de Madaoua',
    'Département de Tahoua',
    'Département de Tchin-Tabaraden',
    'Illéla',
    'Keïta',
    'Madaoua',
    'Tahoua',
    'Tchintabaraden',
  ],
  'Tillabéri Region': [
    'Ayorou',
    'Balleyara',
    'Département de Filingué',
    'Département de Ouallam',
    'Département de Say',
    'Filingué',
    'Kollo',
    'Kollo Department',
    'Ouallam',
    'Say',
    'Téra',
    'Tera Department',
    'Tillabéri',
    'Tillaberi Department',
  ],
  'Zinder Region': [
    'Département de Gouré',
    'Département de Kantché',
    'Département de Tânout',
    'Gouré',
    'Magaria',
    'Matamey',
    'Mirriah',
    'Tanout',
    'Zinder',
  ],
};
