export const NIGERIA_STATE_CITY = {
  Abia: ['Aba', 'Amaigbo', 'Arochukwu', 'Bende', 'Ohafia-Ifigh', 'Umuahia'],
  'Abuja Federal Capital Territory': [
    'Abuja',
    'Asokoro',
    'Bamburu',
    'Garki',
    'Gwagwalada',
    'Gwarinpa',
    'Jikwoyi',
    'Karu',
    'Kubwa',
    'Kuje',
    'Kurunduma',
    'Kwali',
    'Madala',
    'Maitama',
    'Wuse',
    'Zuba',
  ],
  Adamawa: [
    'Ganye',
    'Gombi',
    'Holma',
    'Jimeta',
    'Madagali',
    'Mayo-Belwa',
    'Mubi',
    'Ngurore',
    'Numan',
    'Toungo',
    'Yola',
  ],
  'Akwa Ibom': ['Eket', 'Esuk Oron', 'Ikot Ekpene', 'Itu', 'Uyo'],
  Anambra: [
    'Agulu',
    'Atani',
    'Awka',
    'Enugu-Ukwu',
    'Igbo-Ukwu',
    'Ihiala',
    'Nkpor',
    'Nnewi',
    'Onitsha',
    'Ozubulu',
    'Uga',
    'Uruobo-Okija',
  ],
  Bauchi: [
    'Azare',
    'Bauchi',
    'Boi',
    'Bununu',
    'Darazo',
    'Dass',
    'Dindima',
    'Disina',
    'Gabarin',
    'Gwaram',
    'Kari',
    'Lame',
    'Lere',
    'Madara',
    'Misau',
    'Sade',
    'Yamrat',
    'Yanda Bayo',
    'Yuli',
    'Zadawa',
    'Zalanga',
  ],
  Bayelsa: ['Amassoma', 'Twon-Brass', 'Yenagoa'],
  Benue: [
    'Aliade',
    'Boju',
    'Gboko',
    'Igbor',
    'Makurdi',
    'Ochobo',
    'Otukpa',
    'Takum',
    'Ugbokpo',
    'Yandev',
    'Zaki Biam',
  ],
  Borno: [
    'Bama',
    'Benisheikh',
    'Biu',
    'Bornu Yassu',
    'Damasak',
    'Damboa',
    'Dikwa',
    'Gamboru',
    'Gwoza',
    'Kukawa',
    'Magumeri',
    'Maiduguri',
    'Marte',
    'Miringa',
    'Monguno',
    'Ngala',
    'Shaffa',
    'Shani',
    'Tokombere',
    'Uba',
    'Wuyo',
    'Yajiwa',
  ],
  'Cross River': ['Akankpa', 'Calabar', 'Gakem', 'Ikang', 'Ugep'],
  Delta: [
    'Abraka',
    'Agbor',
    'Asaba',
    'Bomadi',
    'Burutu',
    'Kwale',
    'Obiaruku',
    'Ogwashi-Uku',
    'Orerokpe',
    'Patani',
    'Sapele',
    'Ughelli',
    'Umunede',
    'Warri',
  ],
  Ebonyi: ['Abakaliki', 'Afikpo', 'Effium', 'Ezza-Ohu', 'Isieke'],
  Edo: [
    'Agenebode',
    'Auchi',
    'Benin City',
    'Ekpoma',
    'Igarra',
    'Illushi',
    'Siluko',
    'Ubiaja',
    'Uromi',
  ],
  Ekiti: [
    'Ado-Ekiti',
    'Aramoko-Ekiti',
    'Efon-Alaaye',
    'Emure-Ekiti',
    'Ifaki',
    'Igbara-Odo',
    'Igede-Ekiti',
    'Ijero-Ekiti',
    'Ikere-Ekiti',
    'Ipoti',
    'Ise-Ekiti',
    'Oke Ila',
    'Omuo-Ekiti',
  ],
  Enugu: [
    'Adani',
    'Ake-Eze',
    'Aku',
    'Amagunze',
    'Awgu',
    'Eha Amufu',
    'Enugu',
    'Enugu-Ezike',
    'Ete',
    'Ikem',
    'Mberubu',
    'Nsukka',
    'Obolo-Eke (1)',
    'Opi',
    'Udi',
  ],
  Gombe: [
    'Akko',
    'Bara',
    'Billiri',
    'Dadiya',
    'Deba',
    'Dukku',
    'Garko',
    'Gombe',
    'Hinna',
    'Kafarati',
    'Kaltungo',
    'Kumo',
    'Nafada',
    'Pindiga',
  ],
  Imo: ['Iho', 'Oguta', 'Okigwe', 'Orlu', 'Orodo', 'Owerri'],
  Jigawa: [
    'Babura',
    'Birnin Kudu',
    'Birniwa',
    'Dutse',
    'Gagarawa',
    'Gumel',
    'Gwaram',
    'Hadejia',
    'Kafin Hausa',
    'Kazaure',
    'Kiyawa',
    'Mallammaduri',
    'Ringim',
    'Samamiya',
  ],
  Kaduna: [
    'Anchau',
    'Burumburum',
    'Dutsen Wai',
    'Hunkuyi',
    'Kachia',
    'Kaduna',
    'Kafanchan',
    'Kagoro',
    'Kajuru',
    'Kujama',
    'Lere',
    'Mando',
    'Saminaka',
    'Soba',
    'Sofo-Birnin-Gwari',
    'Zaria',
  ],
  Kano: ['Dan Gora', 'Gaya', 'Kano'],
  Katsina: [
    'Danja',
    'Dankama',
    'Daura',
    'Dutsin-Ma',
    'Funtua',
    'Gora',
    'Jibia',
    'Jikamshi',
    'Kankara',
    'Katsina',
    'Mashi',
    'Ruma',
    'Runka',
    'Wagini',
  ],
  Kebbi: [
    'Argungu',
    'Bagudo',
    'Bena',
    'Bin Yauri',
    'Birnin Kebbi',
    'Dabai',
    'Dakingari',
    'Gulma',
    'Gwandu',
    'Jega',
    'Kamba',
    'Kangiwa',
    'Kende',
    'Mahuta',
    'Maiyama',
    'Shanga',
    'Wasagu',
    'Zuru',
  ],
  Kogi: [
    'Abocho',
    'Adoru',
    'Ankpa',
    'Bugana',
    'Dekina',
    'Egbe',
    'Icheu',
    'Idah',
    'Isanlu-Itedoijowa',
    'Kabba',
    'Koton-Karfe',
    'Lokoja',
    'Ogaminana',
    'Ogurugu',
    'Okene',
  ],
  Kwara: [
    'Ajasse Ipo',
    'Bode Saadu',
    'Gwasero',
    'Ilorin',
    'Jebba',
    'Kaiama',
    'Lafiagi',
    'Offa',
    'Okuta',
    'Omu-Aran',
    'Patigi',
    'Suya',
    'Yashikera',
  ],
  Lagos: [
    'Abule Egba',
    'Agege',
    'Alimosho',
    'Amuwo-Odofin',
    'Apapa',
    'Badagry',
    'Bariga',
    'Ebute Ikorodu',
    'Ebute Metta',
    'Ejirin',
    'Epe',
    'Eti-Osa',
    'Festac',
    'Ibeju-Lekki',
    'Idimu',
    'Ifako-Ijaiye',
    'Igando',
    'Ijora',
    'Ikeja',
    'Ikorodu',
    'Ipaja',
    'Isheri-Olofin',
    'Lagos',
    'Lagos Island',
    'Lekki',
    'Makoko',
    'Mushin',
    'Ogba',
    'Ojo',
    'Ojodu Berger',
    'Ojota',
    'Oshodi-Isolo',
    'Shomolu',
    'Surulere',
    'Victoria Island',
    'Yaba',
  ],
  Nasarawa: ['Buga', 'Doma', 'Keffi', 'Lafia', 'Nasarawa', 'Wamba'],
  Niger: [
    'Auna',
    'Babana',
    'Badeggi',
    'Baro',
    'Bokani',
    'Duku',
    'Ibeto',
    'Konkwesso',
    'Kontagora',
    'Kusheriki',
    'Kuta',
    'Lapai',
    'Minna',
    'New Shagunnu',
    'Suleja',
    'Tegina',
    'Ukata',
    'Wawa',
    'Zungeru',
  ],
  Ogun: [
    'Abeokuta',
    'Ado Odo',
    'Idi Iroko',
    'Ifo',
    'Ijebu-Ife',
    'Ijebu-Igbo',
    'Ijebu-Ode',
    'Ilaro',
    'Imeko',
    'Iperu',
    'Isara',
    'Owode',
  ],
  Ondo: [
    'Agbabu',
    'Akure',
    'Idanre',
    'Ifon',
    'Ilare',
    'Ode',
    'Ondo',
    'Ore',
    'Owo',
  ],
  Osun: [
    'Apomu',
    'Ejigbo',
    'Gbongan',
    'Ijebu-Jesa',
    'Ikire',
    'Ikirun',
    'Ila Orangun',
    'Ile-Ife',
    'Ilesa',
    'Ilobu',
    'Inisa',
    'Iwo',
    'Modakeke',
    'Oke Mesi',
    'Olupona',
    'Osogbo',
    'Otan Ayegbaju',
    'Oyan',
  ],
  Oyo: [
    'Ago Are',
    'Alapa',
    'Fiditi',
    'Ibadan',
    'Igbeti',
    'Igbo-Ora',
    'Igboho',
    'Kisi',
    'Lalupon',
    'Ogbomoso',
    'Okeho',
    'Orita Eruwa',
    'Oyo',
    'Saki',
  ],
  Plateau: [
    'Amper',
    'Bukuru',
    'Dengi',
    'Jos',
    'Kwolla',
    'Langtang',
    'Pankshin',
    'Panyam',
    'Vom',
    'Yelwa',
  ],
  Rivers: [
    'Abalama',
    'Abonnema',
    'Ahoada',
    'Bori',
    'Buguma',
    'Chokocho',
    'Elele',
    'Obonoma',
    'Omoku',
    'Onne',
    'Opobo',
    'Port Harcourt',
    'Rumuokoro',
  ],
  Sokoto: [
    'Binji',
    'Dange',
    'Gandi',
    'Goronyo',
    'Gwadabawa',
    'Illela',
    'Rabah',
    'Sokoto',
    'Tambuwal',
    'Wurno',
  ],
  Taraba: [
    'Baissa',
    'Beli',
    'Gassol',
    'Gembu',
    'Ibi',
    'Jalingo',
    'Lau',
    'Mutum Biyu',
    'Riti',
    'Wukari',
  ],
  Yobe: [
    'Damaturu',
    'Dankalwa',
    'Dapchi',
    'Daura',
    'Fika',
    'Gashua',
    'Geidam',
    'Goniri',
    'Gorgoram',
    'Gujba',
    'Gwio Kura',
    'Kumagunnam',
    'Lajere',
    'Machina',
    'Nguru',
    'Potiskum',
  ],
  Zamfara: [
    'Anka',
    'Dan Sadau',
    'Gummi',
    'Gusau',
    'Kaura Namoda',
    'Kwatarkwashi',
    'Maru',
    'Moriki',
    'Sauri',
    'Tsafe',
  ],
};
