export const NICARAGUA_DEPARTMENTS_CITIES = {
  Boaco: [
    'Boaco',
    'Camoapa',
    'San José de los Remates',
    'San Lorenzo',
    'Santa Lucía',
    'Teustepe',
  ],
  Carazo: [
    'Diriamba',
    'Dolores',
    'El Rosario',
    'Jinotepe',
    'La Conquista',
    'La Paz de Carazo',
    'Municipio de San Marcos',
    'San Marcos',
    'Santa Teresa',
  ],
  Chinandega: [
    'Chichigalpa',
    'Chinandega',
    'Cinco Pinos',
    'Corinto',
    'El Realejo',
    'El Viejo',
    'Jiquilillo',
    'Municipio de San Francisco del Norte',
    'Posoltega',
    'Puerto Morazán',
    'Santo Tomás del Norte',
    'Somotillo',
  ],
  Chontales: [
    'Acoyapa',
    'Comalapa',
    'Cuapa',
    'El Ayote',
    'Juigalpa',
    'La Libertad',
    'Santo Domingo',
    'Santo Tomás',
    'Villa Sandino',
  ],
  Estelí: [
    'Condega',
    'Estelí',
    'La Trinidad',
    'Pueblo Nuevo',
    'San Juan de Limay',
  ],
  Granada: ['Diriá', 'Diriomo', 'Granada', 'Nandaime'],
  Jinotega: [
    'El Cuá',
    'Jinotega',
    'La Concordia',
    'Las Praderas',
    'LLano de La Cruz',
    'San José de Bocay',
    'San Rafael del Norte',
    'San Sebastián de Yalí',
  ],
  León: [
    'Achuapa',
    'El Jicaral',
    'El Sauce',
    'La Paz Centro',
    'Larreynaga',
    'León',
    'Nagarote',
    'Quezalguaque',
    'Santa Rosa del Peñón',
    'Telica',
  ],
  Madriz: [
    'Las Sabanas',
    'Palacagüina',
    'San José de Cusmapa',
    'San Juan de Río Coco',
    'San Lucas',
    'Somoto',
    'Telpaneca',
    'Totogalpa',
    'Yalagüina',
  ],
  Managua: [
    'Ciudad Sandino',
    'El Crucero',
    'Managua',
    'Masachapa',
    'San Rafael del Sur',
    'Ticuantepe',
    'Tipitapa',
    'Valle San Francisco',
    'Villa El Carmen',
  ],
  Masaya: [
    'Catarina',
    'La Concepción',
    'Masatepe',
    'Masaya',
    'Municipio de Masatepe',
    'Municipio de Nandasmo',
    'Municipio de Niquinohomo',
    'Municipio de San Juan de Oriente',
    'Nandasmo',
    'Nindirí',
    'Niquinohomo',
    'San Juan de Oriente',
    'Tisma',
  ],
  Matagalpa: [
    'Ciudad Darío',
    'Matagalpa',
    'Matiguás',
    'Muy Muy',
    'Río Blanco',
    'San Dionisio',
    'San Ramón',
    'Terrabona',
  ],
  'North Caribbean Coast': [
    'Bonanza',
    'Prinzapolka',
    'Puerto Cabezas',
    'Siuna',
    'Waslala',
    'Waspán',
  ],
  'Nueva Segovia': [
    'Ciudad Antigua',
    'Dipilto',
    'El Jícaro',
    'Jalapa',
    'Macuelizo',
    'Mozonte',
    'Murra',
    'Ocotal',
    'Quilalí',
    'San Fernando',
    'Santa María',
    'Wiwilí',
  ],
  'Río San Juan': [
    'El Almendro',
    'Greytown',
    'Morrito',
    'San Carlos',
    'San Miguelito',
  ],
  Rivas: [
    'Altagracia',
    'Belén',
    'Buenos Aires',
    'Cárdenas',
    'Moyogalpa',
    'Municipio de Altagracia',
    'Municipio de Belén',
    'Municipio de Buenos Aires',
    'Municipio de Cárdenas',
    'Municipio de Moyogalpa',
    'Municipio de Potosí',
    'Municipio de Rivas',
    'Municipio de San Jorge',
    'Municipio de San Juan del Sur',
    'Municipio de Tola',
    'Potosí',
    'Rivas',
    'San Jorge',
    'San Juan del Sur',
    'Tola',
  ],
  'South Caribbean Coast': [
    'Bluefields',
    'Bocana de Paiwas',
    'Corn Island',
    'El Rama',
    'El Tortuguero',
    'Kukrahill',
    'La Cruz de Río Grande',
    'Laguna de Perlas',
    'Muelle de los Bueyes',
    'Nueva Guinea',
  ],
};
