export const NEPAL_PROVINCES_CITIES = {
  'Central Region': [
    'Banepā',
    'Bharatpur',
    'Birgañj',
    'Dhulikhel',
    'Gaur',
    'Hari Bdr Tamang House',
    'Hetauda',
    'Jaleshwar',
    'Janakpur',
    'kankrabari Dovan',
    'Kathmandu',
    'Kirtipur',
    'Madhyapur Thimi',
    'Malaṅgawā',
    'Nagarkot',
    'Panauti',
    'Pātan',
    'Rāmechhāp',
  ],
  'Eastern Development Region': [
    'Bhadrapur',
    'Bhojpur',
    'Biratnagar',
    'Dhankutā',
    'Dharān',
    'Ilām',
    'Inaruwa',
    'Khanbari',
    'Lahān',
    'Lobujya',
    'Namche Bazar',
    'Rājbirāj',
    'Siraha',
    'Titahari',
    'Triyuga',
  ],
  'Far-Western Development Region': [
    'Dadeldhurā',
    'Dhangaḍhi̇̄',
    'Dipayal',
    'Mahendranagar',
    'Ṭikāpur',
  ],
  'Mid-Western Region': [
    'Bhojpur',
    'Birendranagar',
    'Dailekh',
    'Gulariyā',
    'Jumla',
    'Nepalgunj',
    'Tulsīpur',
  ],
  'Western Region': [
    'Bāglung',
    'Bhattarai Danda',
    'Butwāl',
    'Chitre',
    'Dārchulā',
    'Dihi',
    'Pokhara',
    'Siddharthanagar',
    'Tānsen',
    'Wāliṅ',
  ],
};
