export const NEW_ZEALAND_REGIONS_CITIES = {
  'Auckland Region': [
    'Auckland',
    'Mangere',
    'Manukau City',
    'Muriwai Beach',
    'Murrays Bay',
    'North Shore',
    'Pakuranga',
    'Papakura',
    'Parakai',
    'Pukekohe East',
    'Red Hill',
    'Rosebank',
    'Rothesay Bay',
    'Takanini',
    'Tamaki',
    'Titirangi',
    'Waitakere',
    'Waiuku',
    'Warkworth',
    'Wellsford',
    'Wiri',
  ],
  'Bay of Plenty Region': [
    'Edgecumbe',
    'Katikati',
    'Kawerau',
    'Maketu',
    'Murupara',
    'Opotiki',
    'Rotorua',
    'Tauranga',
    'Waihi Beach',
    'Whakatane',
  ],
  'Canterbury Region': [
    'Amberley',
    'Ashburton',
    'Ashburton District',
    'Burnham',
    'Christchurch',
    'Christchurch City',
    'Darfield',
    'Geraldine',
    'Kaiapoi',
    'Leeston',
    'Lincoln',
    'Mackenzie District',
    'Methven',
    'Oxford',
    'Pleasant Point',
    'Prebbleton',
    'Rakaia',
    'Rolleston',
    'Selwyn District',
    'Timaru',
    'Timaru District',
    'Tinwald',
    'Waimakariri District',
    'Woodend',
  ],
  'Chatham Islands': ['Waitangi'],
  'Gisborne District': ['Gisborne'],
  "Hawke's Bay Region": ['Hastings', 'Napier', 'Taradale', 'Wairoa'],
  'Manawatu-Wanganui Region': [
    'Bulls',
    'Foxton',
    'Horowhenua District',
    'Levin',
    'Manawatu District',
    'Palmerston North',
    'Waiouru',
    'Wanganui',
  ],
  'Marlborough Region': ['Blenheim', 'Picton'],
  'Nelson Region': ['Nelson'],
  'Northland Region': [
    'Ahipara',
    'Dargaville',
    'Far North District',
    'Kaipara District',
    'Kaitaia',
    'Kawakawa',
    'Kerikeri',
    'Maungatapere',
    'Moerewa',
    'Ngunguru',
    'Paihia',
    'Ruakaka',
    'Taipa',
    'Waimate North',
    'Whangarei',
  ],
  'Otago Region': [
    'Arrowtown',
    'Balclutha',
    'Clutha District',
    'Cromwell',
    'Dunedin',
    'Kingston',
    'Milton',
    'Oamaru',
    'Papatowai',
    'Portobello',
    'Queenstown',
    'Wanaka',
  ],
  'Southland Region': [
    'Bluff',
    'Gore',
    'Invercargill',
    'Riverton',
    'Southland District',
    'Te Anau',
    'Winton',
  ],
  'Taranaki Region': [
    'Eltham',
    'Hawera',
    'New Plymouth',
    'New Plymouth District',
    'Opunake',
    'Patea',
    'South Taranaki District',
    'Waitara',
  ],
  'Tasman District': [
    'Brightwater',
    'Mapua',
    'Motueka',
    'Richmond',
    'Takaka',
    'Wakefield',
  ],
  'Waikato Region': [
    'Cambridge',
    'Coromandel',
    'Hamilton',
    'Matamata',
    'Ngaruawahia',
    'Ngatea',
    'Otorohanga',
    'Paeroa',
    'Raglan',
    'South Waikato District',
    'Tairua',
    'Taupo',
    'Te Kauwhata',
    'Thames',
    'Tokoroa',
    'Turangi',
    'Waihi',
    'Whangamata',
    'Whitianga',
  ],
  'Wellington Region': [
    'Brooklyn',
    'Castlepoint',
    'Kapiti Coast District',
    'Kelburn',
    'Khandallah',
    'Lower Hutt',
    'Masterton',
    'Otaki',
    'Paraparaumu',
    'Petone',
    'Porirua',
    'South Wairarapa District',
    'Upper Hutt',
    'Waipawa',
    'Wellington',
    'Wellington City',
  ],
  'West Coast Region': ['Greymouth', 'Hokitika', 'Westport'],
};
