export const PERU_REGIONS_CITIES = {
  Amazonas: [
    'Bagua Grande',
    'Cajaruro',
    'Chachapoyas',
    'Condorcanqui',
    'La Peca',
    'Provincia de Bagua',
    'Provincia de Bongará',
    'Provincia de Chachapoyas',
    'Provincia de Luya',
    'Provincia de Rodríguez de Mendoza',
    'Utcubamba',
  ],
  Áncash: [
    'Asuncion',
    'Carás',
    'Carhuaz',
    'Carlos Fermin Fitzcarrald',
    'Chimbote',
    'Coishco',
    'Huaraz',
    'Huarmey',
    'Pomabamba',
    'Provincia de Aija',
    'Provincia de Antonio Raymondi',
    'Provincia de Bolognesi',
    'Provincia de Carhuaz',
    'Provincia de Casma',
    'Provincia de Corongo',
    'Provincia de Huaraz',
    'Provincia de Huari',
    'Provincia de Huarmey',
    'Provincia de Huaylas',
    'Provincia de Mariscal Luzuriaga',
    'Provincia de Pallasca',
    'Provincia de Pomabamba',
    'Provincia de Recuay',
    'Provincia de Santa',
    'Provincia de Sihuas',
    'Provincia de Yungay',
    'Puerto Santa',
    'Yauya',
    'Yungay',
  ],
  Apurímac: [
    'Abancay',
    'Andahuaylas',
    'Provincia de Abancay',
    'Provincia de Andahuaylas',
    'Provincia de Antabamba',
    'Provincia de Aymaraes',
    'Provincia de Cotabambas',
    'Provincia de Grau',
    'San Jerónimo',
    'Talavera',
  ],
  Arequipa: [
    'Acarí',
    'Arequipa',
    'Camaná',
    'Ccolo',
    'Chivay',
    'Cocachacra',
    'Cotahuasi',
    'Huarancante',
    'Huarichancara',
    'Jatun Orcochiri',
    'Jayune',
    'Llongasora',
    'Lluta',
    'Mollendo',
    'Orcopampa',
    'Provincia de Arequipa',
    'Provincia de Camaná',
    'Provincia de Caravelí',
    'Provincia de Castilla',
    'Provincia de Caylloma',
    'Provincia de Condesuyos',
    'Provincia de Islay',
    'Provincia de La Unión',
    'Pucara',
    'Punta de Bombón',
    'Vizcachane',
    'Yura',
  ],
  Ayacucho: [
    'Ayacucho',
    'Ayna',
    'Coracora',
    'Huanta',
    'Paucar Del Sara Sara',
    'Provincia de Cangallo',
    'Provincia de Huamanga',
    'Provincia de Huanca Sancos',
    'Provincia de Huanta',
    'Provincia de La Mar',
    'Provincia de Lucanas',
    'Provincia de Parinacochas',
    'Provincia de Sucre',
    'Provincia de Víctor Fajardo',
    'Provincia de Vilcas Huamán',
    'Puquio',
    'San Miguel',
    'Tambo',
  ],
  Cajamarca: [
    'Bambamarca',
    'Bellavista',
    'Cajabamba',
    'Cajamarca',
    'Celendín',
    'Chota',
    'Jaén',
    'Provincia de Cajabamba',
    'Provincia de Cajamarca',
    'Provincia de Celendín',
    'Provincia de Chota',
    'Provincia de Contumazá',
    'Provincia de Cutervo',
    'Provincia de Hualgayoc',
    'Provincia de Jaén',
    'Provincia de San Ignacio',
    'Provincia de San Miguel',
    'Provincia de Santa Cruz',
    'San Ignacio',
  ],
  Callao: ['Callao'],
  Cusco: [
    'Anta',
    'Cahuanuyo',
    'Calca',
    'Callanca',
    'Ccaquiracunca',
    'Ccuntuma',
    'Checacupe',
    'Checca',
    'Chignayhua',
    'Chinchero',
    'Combapata',
    'Conchopata',
    'Cullcuyre',
    'Cusco',
    'Huayna Alcalde',
    'Jayobamba',
    'Langui',
    'Layo',
    'Lima Pampa',
    'Maranganí',
    'Maras',
    'Mosoc Cancha',
    'Mosoc Llacta',
    'Ollantaytambo',
    'Oropesa',
    'Pampamarca',
    'Pangoa',
    'Paucartambo',
    'Pisac',
    'Provincia de Acomayo',
    'Provincia de Anta',
    'Provincia de Calca',
    'Provincia de Canas',
    'Provincia de Canchis',
    'Provincia de Chumbivilcas',
    'Provincia de Cusco',
    'Provincia de Espinar',
    'Provincia de La Convención',
    'Provincia de Paruro',
    'Provincia de Paucartambo',
    'Provincia de Quispicanchis',
    'Provincia de Urubamba',
    'Qquea',
    'Queromarca',
    'San Pablo',
    'Santa Ana',
    'Santo Tomas',
    'Sicuani',
    'Tinta',
    'Tungasuca',
    'Urcos',
    'Urubamba',
    'Yanaoca',
  ],
  Huancavelica: [
    'Huancavelica',
    'Huaytara',
    'Pampas',
    'Provincia de Acobamba',
    'Provincia de Angaraes',
    'Provincia de Castrovirreyna',
    'Provincia de Churcampa',
    'Provincia de Huancavelica',
    'Provincia de Tayacaja',
  ],
  Huanuco: [
    'Ambo',
    'Huacaybamba',
    'Huánuco',
    'La Unión',
    'Lauricocha',
    'Llata',
    'Provincia de Ambo',
    'Provincia de Dos de Mayo',
    'Provincia de Huamalíes',
    'Provincia de Huánuco',
    'Provincia de Leoncio Prado',
    'Provincia de Marañón',
    'Provincia de Pachitea',
    'Puerto Inca',
    'San Miguel de Cauri',
    'Tingo María',
    'Yanacancha',
    'Yarowilca',
  ],
  Ica: [
    'Chincha Alta',
    'Ica',
    'Los Aquijes',
    'Minas de Marcona',
    'Nazca',
    'Palpa',
    'Paracas',
    'Pisco',
    'Provincia de Chincha',
    'Provincia de Ica',
    'Provincia de Nazca',
    'Provincia de Palpa',
    'Provincia de Pisco',
    'Río Grande',
    'San Clemente',
    'San Juan Bautista',
    'Santiago',
    'Subtanjalla',
    'Villa Tupac Amaru',
  ],
  Junín: [
    'Acolla',
    'Carhuamayo',
    'Chanchamayo',
    'Chupaca',
    'Concepción',
    'Huancayo',
    'Huasahuasi',
    'Huayucachi',
    'Jauja',
    'Junín',
    'La Oroya',
    'Mazamari',
    'Morococha',
    'Orcotuna',
    'Perené',
    'Pilcomay',
    'Provincia de Chupaca',
    'Provincia de Concepción',
    'Provincia de Huancayo',
    'Provincia de Jauja',
    'Provincia de Junín',
    'Provincia de Satipo',
    'Provincia de Tarma',
    'Provincia de Yauli',
    'San Agustin',
    'San Jerónimo',
    'San Pedro de Cajas',
    'San Ramón',
    'Satipo',
    'Sicaya',
    'Tarma',
  ],
  'La Libertad': [
    'Ascope',
    'Cascas',
    'Chepen',
    'Chicama',
    'Chocope',
    'Gran Chimu',
    'Guadalupe',
    'Huamachuco',
    'Julcan',
    'Laredo',
    'Moche',
    'Otuzco',
    'Pacanga',
    'Pacasmayo',
    'Paiján',
    'Provincia de Bolívar',
    'Provincia de Otuzco',
    'Provincia de Pacasmayo',
    'Provincia de Pataz',
    'Provincia de Santiago de Chuco',
    'Provincia de Trujillo',
    'Pueblo Nuevo',
    'Quiruvilca',
    'Salaverry',
    'San Pedro de Lloc',
    'Sanchez Carrion',
    'Santiago de Cao',
    'Santiago de Chuco',
    'Trujillo',
    'Viru',
  ],
  Lambayeque: [
    'Chiclayo',
    'Chongoyape',
    'Eten',
    'Ferreñafe',
    'Jayanca',
    'Lambayeque',
    'Mochumí',
    'Monsefú',
    'Mórrope',
    'Motupe',
    'Olmos',
    'Oyotún',
    'Picsi',
    'Pimentel',
    'Provincia de Chiclayo',
    'Provincia de Ferreñafe',
    'Provincia de Lambayeque',
    'Pueblo Nuevo',
    'Reque',
    'San José',
    'Saña',
    'Santa Rosa',
    'Túcume',
  ],
  Lima: [
    'Asentamiento Humano Nicolas de Pierola',
    'Barranca',
    'Caleta de Carquín',
    'Chancay',
    'Chilca',
    'Chosica',
    'Huacho',
    'Hualmay',
    'Huaral',
    'Huaura',
    'Imperial',
    'Independencia',
    'Lima',
    'Mala',
    'Matucana',
    'Nuevo Imperial',
    'Oyon',
    'Paramonga',
    'Pativilca',
    'Provincia de Cajatambo',
    'Provincia de Cañete',
    'Provincia de Canta',
    'Provincia de Huaral',
    'Provincia de Huarochirí',
    'Provincia de Yauyos',
    'Puerto Supe',
    'Quilmaná',
    'Ricardo Palma',
    'San Bartolo',
    'San Isidro',
    'San Luis',
    'San Vicente de Cañete',
    'Santa María',
    'Santiago de Surco',
    'Sayán',
    'Supe',
    'Urb. Santo Domingo',
    'Végueta',
  ],
  Loreto: [
    'Andoas',
    'Borja',
    'Caballococha',
    'Cape Pantoja',
    'Indiana',
    'Iquitos',
    'Jeberos',
    'Jenaro Herrera',
    'Lagunas',
    'Nauta',
    'Punchana',
    'Requena',
    'San Antonio del Estrecho',
    'San Lorenzo',
    'San Pablo',
    'Tamshiyacu',
    'Yurimaguas',
  ],
  'Madre de Dios': [
    'Iberia',
    'Provincia de Manú',
    'Provincia de Tahuamanú',
    'Provincia de Tambopata',
    'Puerto Maldonado',
    'Salvación',
    'Tambopata',
  ],
  Moquegua: [
    'Ilo',
    'Moquegua',
    'Pacocha',
    'Provincia de General Sánchez Cerro',
    'Provincia de Ilo',
    'Provincia de Mariscal Nieto',
    'Torata',
  ],
  Pasco: [
    'Cerro de Pasco',
    'Chaupimarca',
    'Oxapampa',
    'Paucartambo',
    'Provincia de Daniel Carrión',
    'Provincia de Oxapampa',
    'Provincia de Pasco',
    'Tinyahuarco',
    'Villa Rica',
  ],
  Piura: [
    'Ayabaca',
    'Bernal',
    'Buenos Aires',
    'Catacaos',
    'Chulucanas',
    'El Alto',
    'Huancabamba',
    'La Breita',
    'La Huaca',
    'La Unión',
    'Las Lomas',
    'Máncora',
    'Marcavelica',
    'Morropon',
    'Paita',
    'Piura',
    'Provincia de Ayabaca',
    'Provincia de Huancabamba',
    'Provincia de Paita',
    'Provincia de Piura',
    'Provincia de Sullana',
    'Provincia de Talara',
    'Querecotillo',
    'Salinera Colán',
    'Salitral',
    'Sechura',
    'Sullana',
    'Talara',
    'Tambo Grande',
    'Vice',
  ],
  Puno: [
    'Atuncolla',
    'Ayaviri',
    'Azángaro',
    'Desaguadero',
    'El Collao',
    'Hacienda Huancane',
    'Ilave',
    'Juli',
    'Juliaca',
    'La Rinconada',
    'Lampa',
    'Macusani',
    'Ñuñoa',
    'Provincia de Azángaro',
    'Provincia de Carabaya',
    'Provincia de Chucuito',
    'Provincia de Huancané',
    'Provincia de Lampa',
    'Provincia de Melgar',
    'Provincia de Puno',
    'Provincia de Sandia',
    'Puno',
    'San Antonio De Putina',
    'San Roman',
    'Santa Lucía',
    'Taquile',
    'Yunguyo',
  ],
  'San Martín': [
    'Bellavista',
    'Chazuta',
    'El Dorado',
    'Huicungo',
    'Jepelacio',
    'Juanjuí',
    'Lamas',
    'Moyobamba',
    'Picota',
    'Provincia de Huallaga',
    'Provincia de Lamas',
    'Provincia de Mariscal Cáceres',
    'Provincia de Moyobamba',
    'Provincia de Rioja',
    'Provincia de San Martín',
    'Rioja',
    'Saposoa',
    'Sisa',
    'Soritor',
    'Tabalosos',
    'Tarapoto',
    'Tocache',
    'Uchiza',
  ],
  Tacna: [
    'Calana',
    'Candarave',
    'Chipispaya',
    'Chuquitira',
    'Ilabaya',
    'Jorge Basadre',
    'Provincia de Tacna',
    'Provincia de Tarata',
    'Pujocucho',
    'Quilahuani',
    'Tacna',
    'Tarata',
    'Totoral',
  ],
  Tumbes: [
    'Aguas Verdes',
    'Papayal',
    'Provincia de Contralmirante Villar',
    'Provincia de Tumbes',
    'Provincia de Zarumilla',
    'Tumbes',
    'Zarumilla',
    'Zorritos',
  ],
  Ucayali: [
    'Atalaya',
    'Campoverde',
    'Padre Abad',
    'Provincia de Coronel Portillo',
    'Pucallpa',
    'Purus',
  ],
};
