export const PAPUA_NEW_GUINEA_PROVINCES_CITIES = {
  Bougainville: [
    'Arawa',
    'Central Bougainville',
    'Kieta',
    'North Bougainville',
    'Panguna',
    'South Bougainville',
  ],
  'Central Province': ['Abau', 'Goilala', 'Kairuku-Hiri', 'Rigo'],
  'Chimbu Province': [
    'Chuave',
    'Gumine',
    'Karimui Nomane',
    'Kerowagi',
    'Kundiawa',
    'Sinasina Yonggamugl',
  ],
  'East New Britain': ['Gazelle', 'Kokopo', 'Pomio', 'Rabaul'],
  'Eastern Highlands Province': [
    'Daulo',
    'Goroka',
    'Henganofi',
    'Kainantu',
    'Lufa',
    'Obura Wonenara',
    'Okapa',
    'Unggai Bena',
  ],
  'Enga Province': [
    'Kandep',
    'Kompiam Ambum',
    'Lagaip Porgera',
    'Porgera',
    'Wabag',
    'Wapenamanda',
  ],
  Gulf: ['Kerema', 'Kikori'],
  Hela: ['Komo Margarima', 'Koroba-Lake Kopiago', 'Tari', 'Tari Pori'],
  'Jiwaka Province': ['Angalimp South Wahgi', 'Jimi', 'North Wahgi'],
  'Madang Province': [
    'Bogia',
    'Madang',
    'Middle Ramu',
    'Rai Coast',
    'Sumkar',
    'Usino Bundi',
  ],
  'Manus Province': ['Lorengau', 'Manus'],
  'Milne Bay Province': [
    'Alotau',
    'Esa’ala',
    'Kiriwina Goodenough',
    'Samarai',
    'Samarai Murua',
  ],
  'Morobe Province': [
    'Bulolo',
    'Finschhafen',
    'Huon Gulf',
    'Kabwum',
    'Lae',
    'Markham',
    'Menyamya',
    'Nawae',
    'Tewai Siassi',
    'Wau',
  ],
  'New Ireland Province': ['Kavieng', 'Namatanai'],
  'Oro Province': ['Ijivitari', 'Kokoda', 'Popondetta', 'Sohe'],
  'Port Moresby': ['National Capital District', 'Port Moresby'],
  'Sandaun Province': [
    'Aitape',
    'Aitape Lumi',
    'Nuku',
    'Telefomin',
    'Vanimo',
    'Vanimo Green',
  ],
  'Southern Highlands Province': [
    'Ialibu',
    'Ialibu Pangia',
    'Imbonggu',
    'Kagua Erave',
    'Mendi',
    'Nipa Kutubu',
  ],
  'West New Britain Province': [
    'Kandrian',
    'Kandrian Gloucester',
    'Kimbe',
    'Talasea',
  ],
  'Western Highlands Province': [
    'Baiyer Mul',
    'Dei',
    'Hagen',
    'Mount Hagen',
    'Tambul Nebilyer',
  ],
  'Western Province': [
    'Daru',
    'Kiunga',
    'Middle Fly',
    'Morehead',
    'North Fly',
    'South Fly',
  ],
};
