export const PUERTO_RICO_STATE_CITY = {
  Adjuntas: ['Adjuntas'],
  Aguada: ['Aguada'],
  Aguadilla: ['Aguadilla'],
  'Aguas Buenas': ['Aguas Buenas'],
  Aibonito: ['Aibonito'],
  Añasco: ['Añasco'],
  Arecibo: ['Arecibo'],
  Arroyo: ['Arroyo'],
  Barceloneta: ['Barceloneta'],
  Barranquitas: ['Barranquitas'],
  Bayamón: ['Bayamón'],
  'Cabo Rojo': ['Cabo Rojo'],
  Caguas: ['Caguas'],
  Camuy: ['Camuy'],
  Canóvanas: ['Canóvanas'],
  Carolina: ['Carolina'],
  Cataño: ['Cataño'],
  Cayey: ['Cayey'],
  Ceiba: ['Ceiba'],
  Ciales: ['Ciales'],
  Cidra: ['Cidra'],
  Coamo: ['Coamo'],
  Comerío: ['Comerío'],
  Corozal: ['Corozal'],
  Culebra: ['Culebra'],
  Dorado: ['Dorado'],
  Fajardo: ['Fajardo'],
  Florida: ['Florida'],
  Guánica: ['Guánica'],
  Guayama: ['Guayama'],
  Guayanilla: ['Guayanilla'],
  Guaynabo: ['Guaynabo'],
  Gurabo: ['Gurabo'],
  Hatillo: ['Hatillo'],
  Hormigueros: ['Hormigueros'],
  Humacao: ['Humacao'],
  Isabela: ['Isabela'],
  Jayuya: ['Jayuya'],
  'Juana Díaz': ['Juana Díaz'],
  Juncos: ['Juncos'],
  Lajas: ['Lajas'],
  Lares: ['Lares'],
  'Las Marías': ['Las Marías'],
  'Las Piedras': ['Las Piedras'],
  Loíza: ['Loíza'],
  Luquillo: ['Luquillo'],
  Manatí: ['Manatí'],
  Maricao: ['Maricao'],
  Maunabo: ['Maunabo'],
  Mayagüez: ['Mayagüez'],
  Moca: ['Moca'],
  Morovis: ['Morovis'],
  Naguabo: ['Naguabo'],
  Naranjito: ['Naranjito'],
  Orocovis: ['Orocovis'],
  Patillas: ['Patillas'],
  Peñuelas: ['Peñuelas'],
  Ponce: ['Ponce'],
  Quebradillas: ['Quebradillas'],
  Rincón: ['Rincón'],
  'Río Grande': ['Río Grande'],
  'Sabana Grande': ['Sabana Grande'],
  Salinas: ['Salinas'],
  'San Germán': ['San Germán'],
  'San Juan': ['San Juan'],
  'San Lorenzo': ['San Lorenzo'],
  'San Sebastián': ['San Sebastián'],
  'Santa Isabel': ['Santa Isabel'],
  'Toa Alta': ['Toa Alta'],
  'Toa Baja': ['Toa Baja'],
  'Trujillo Alto': ['Trujillo Alto'],
  Utuado: ['Utuado'],
  'Vega Alta': ['Vega Alta'],
  'Vega Baja': ['Vega Baja'],
  Vieques: ['Vieques'],
  Villalba: ['Villalba'],
  Yabucoa: ['Yabucoa'],
  Yauco: ['Yauco'],
};
