export const PARAGUAY_DEPARTMENTS_CITIES = {
  'Alto Paraguay Department': ['Capitán Pablo Lagerenza', 'Fuerte Olimpo'],
  'Alto Paraná Department': [
    'Cedrales',
    'Ciudad del Este',
    'Colonia Minga Porá',
    'Doctor Juan León Mallorquín',
    'Itakyry',
    'Naranjal',
    'Presidente Franco',
    'San Alberto',
    'Santa Rita',
    'Yguazú',
  ],
  'Amambay Department': ['Bella Vista', 'Capitán Bado', 'Pedro Juan Caballero'],
  'Boquerón Department': ['Colonia Menno', 'Colonia Neuland', 'Filadelfia'],
  Caaguazú: [
    'Caaguazú',
    'Carayaó',
    'Cecilio Baez',
    'Colonia General Alfredo Stroessner',
    'Coronel Oviedo',
    'Doctor Juan Manuel Frutos',
    'Mbutuý',
    'Repatriación',
    'San Joaquín',
    'San José',
    'Yhú',
  ],
  Caazapá: [
    'Abaí',
    'Buena Vista',
    'Caazapá',
    'General Higinio Morínigo',
    'San Juan Nepomuceno',
    'Yegros',
    'Yuty',
  ],
  Canindeyú: [
    'Colonia Catuete',
    'Corpus Christi',
    'La Paloma',
    'Nueva Esperanza',
    'Salto del Guairá',
    'San Isidro de Curuguaty',
    'Ygatimi',
  ],
  'Central Department': [
    'Areguá',
    'Capiatá',
    'Fernando de la Mora',
    'Guarambaré',
    'Itá',
    'Itauguá',
    'Lambaré',
    'Limpio',
    'Mariano Roque Alonso',
    'Nemby',
    'Nueva Italia',
    'San Antonio',
    'San Lorenzo',
    'Villa Elisa',
    'Ypacarai',
  ],
  'Concepción Department': ['Belén', 'Concepción', 'Horqueta'],
  'Cordillera Department': [
    'Altos',
    'Arroyos y Esteros',
    'Atyrá',
    'Caacupé',
    'Caraguatay',
    'Emboscada',
    'Eusebio Ayala',
    'Isla Pucú',
    'Itacurubí de la Cordillera',
    'Piribebuy',
    'San Bernardino',
    'Santa Elena',
    'Tobatí',
  ],
  'Guairá Department': [
    'Colonia Mauricio José Troche',
    'Coronel Martínez',
    'Independencia',
    'Itapé',
    'Iturbe',
    'Mbocayaty',
    'Natalicio Talavera',
    'Villarrica',
  ],
  Itapúa: [
    'Arquitecto Tomás Romero Pereira',
    'Bella Vista',
    'Capitán Miranda',
    'Carmen del Paraná',
    'Colonia Carlos Antonio López',
    'Colonia San Lorenzo',
    'Edelira',
    'Encarnación',
    'Fram',
    'General Artigas',
    'General Delgado',
    'Hohenau',
    'Jesús',
    'Natalio',
    'Obligado',
    'Pirapó',
    'Puerto Mayor Otaño',
    'San Cosme y Damián',
    'San Juan del Paraná',
    'San Pedro del Paraná',
    'Trinidad',
  ],
  'Misiones Department': [
    'Juan de Ayolas',
    'San Juan Bautista',
    'San Miguel',
    'San Patricio',
    'Santa María',
    'Santa Rosa Misiones',
    'Santiago',
    'Villa Florida',
  ],
  'Ñeembucú Department': ['Cerrito', 'General José Eduvigis Díaz', 'Pilar'],
  'Paraguarí Department': [
    'Acahay',
    'Caapucú',
    'Carapeguá',
    'La Colmena',
    'Mbuyapey',
    'Paraguarí',
    'Pirayú',
    'Quiindy',
    'Sapucaí',
    'Yaguarón',
    'Ybycuí',
  ],
  'Presidente Hayes Department': ['Benjamín Aceval', 'Nanawua', 'Villa Hayes'],
  'San Pedro Department': [
    'Antequera',
    'Capiíbary',
    'Colonia Nueva Germania',
    'General Elizardo Aquino',
    'Guayaybi',
    'Itacurubí del Rosario',
    'Lima',
    'Puerto Rosario',
    'San Pedro de Ycuamandiyú',
    'Tacuatí',
    'Unión',
    'Yataity del Norte',
  ],
};
