export const SUDAN_STATES_CITIES = {
  'Al Jazirah': [
    'Al Hasaheisa',
    'Al Hilāliyya',
    'Al Kiremit al ‘Arakiyyīn',
    'Al Manāqil',
    'Al Masallamiyya',
    'Wad Medani',
    'Wad Rāwah',
  ],
  'Al Qadarif': ['Al Ḩawātah', 'Al Qadarif', 'Doka'],
  'Blue Nile': ['Ad-Damazin', 'Ar Ruseris', 'Kurmuk'],
  'Central Darfur': ['Zalingei'],
  'East Darfur': ['El Daein'],
  Kassala: ['Aroma', 'Kassala', 'Wagar'],
  Khartoum: ['Khartoum', 'Omdurman'],
  'North Darfur': ['El Fasher', 'Kutum', 'Umm Kaddadah'],
  'North Kordofan': ['Ar Rahad', 'Bārah', 'El Obeid', 'Umm Ruwaba'],
  Northern: [
    'Ad Dabbah',
    'Argo',
    'Dongola',
    'Karmah an Nuzul',
    'Kuraymah',
    'Merowe',
  ],
  'Red Sea': ['Gebeit', 'Port Sudan', 'Sawākin', 'Tokār'],
  'River Nile': [
    'Atbara',
    'Berber',
    'Ed Damer',
    'El Bauga',
    'El Matama',
    'Shendi',
  ],
  Sennar: [
    'Ad Dindar',
    'As Sūkī',
    'Jalqani',
    'Kināna',
    'Maiurno',
    'Singa',
    'Sinnar',
  ],
  'South Darfur': ['Gereida', 'Nyala'],
  'South Kordofan': ['Abu Jibeha', 'Al Fūlah', 'Dilling', 'Kadugli', 'Talodi'],
  'West Darfur': ['Geneina'],
  'West Kordofan': ['Abū Zabad', 'Al Lagowa', 'Al Mijlad', 'An Nuhūd'],
  'White Nile': [
    'Ad Douiem',
    'Al Kawa',
    'Al Qiţena',
    'Kosti',
    'Marabba',
    'Rabak',
    'Tandaltī',
    'Um Jar Al Gharbiyya',
    'Wad az Zāki',
  ],
};
