export const SLOVENIA_REGIONS_CITIES = {
  'Ajdovščina Municipality': ['Ajdovščina', 'Cirkulane', 'Lokavec'],
  'Ankaran Municipality': ['Ankaran'],
  'Beltinci Municipality': ['Beltinci', 'Gančani', 'Lipovci', 'Zgornje Gorje'],
  'Benedikt Municipality': ['Benedikt'],
  'Bistrica ob Sotli Municipality': ['Bistrica ob Sotli'],
  'Bled Municipality': ['Bled', 'Kostanjevica na Krki', 'Zasip'],
  'Bloke Municipality': ['Nova Vas'],
  'Bohinj Municipality': [
    'Bohinjska Bistrica',
    'Dragomer',
    'Log pri Brezovici',
  ],
  'Borovnica Municipality': ['Borovnica', 'Makole'],
  'Bovec Municipality': ['Bovec', 'Mirna'],
  'Braslovče Municipality': ['Braslovče'],
  'Brda Municipality': ['Dobrovo', 'Mokronog'],
  'Brežice Municipality': ['Brežice', 'Poljčane'],
  'Brezovica Municipality': [
    'Brezovica pri Ljubljani',
    'Notranje Gorice',
    'Opština Ljubljana-Vič-Rudnik',
    'Rečica ob Savinji',
    'Vnanje Gorice',
  ],
  'Cankova Municipality': ['Cankova'],
  'Cerklje na Gorenjskem Municipality': ['Cerklje na Gorenjskem'],
  'Cerknica Municipality': ['Cerknica', 'Rakek'],
  'Cerkno Municipality': ['Cerkno'],
  'Cerkvenjak Municipality': ['Cerkvenjak'],
  'City Municipality of Celje': ['Celje', 'Ljubečna', 'Trnovlje pri Celju'],
  'City Municipality of Novo Mesto': ['Novo Mesto'],
  'Črenšovci Municipality': ['Črenšovci'],
  'Črna na Koroškem Municipality': ['Črna na Koroškem'],
  'Črnomelj Municipality': ['Črnomelj'],
  'Destrnik Municipality': ['Destrnik'],
  'Divača Municipality': ['Divača'],
  'Dobje Municipality': ['Dobje pri Planini'],
  'Dobrepolje Municipality': ['Videm'],
  'Dobrna Municipality': ['Dobrna'],
  'Dobrova–Polhov Gradec Municipality': ['Dobrova'],
  'Dobrovnik Municipality': ['Dobrovnik'],
  'Dol pri Ljubljani Municipality': ['Dol pri Ljubljani'],
  'Dolenjske Toplice Municipality': ['Dolenjske Toplice'],
  'Domžale Municipality': ['Dob', 'Domžale', 'Radomlje', 'Vir'],
  'Dornava Municipality': ['Dornava'],
  'Dravograd Municipality': ['Dravograd'],
  'Duplek Municipality': ['Spodnji Duplek', 'Zgornji Duplek'],
  'Gorenja Vas–Poljane Municipality': ['Gorenja Vas'],
  'Gorišnica Municipality': ['Gorišnica'],
  'Gornja Radgona Municipality': ['Gornja Radgona'],
  'Gornji Grad Municipality': ['Gornji Grad'],
  'Gornji Petrovci Municipality': ['Gornji Petrovci'],
  'Grad Municipality': ['Grad'],
  'Grosuplje Municipality': ['Grosuplje', 'Šmarje-Sap'],
  'Hajdina Municipality': ['Spodnja Hajdina'],
  'Hoče–Slivnica Municipality': [
    'Hotinja Vas',
    'Radizel',
    'Rogoza',
    'Spodnje Hoče',
  ],
  'Hodoš Municipality': ['Hodoš'],
  'Horjul Municipality': ['Horjul'],
  'Hrastnik Municipality': ['Dol pri Hrastniku', 'Hrastnik'],
  'Hrpelje–Kozina Municipality': ['Kozina'],
  'Idrija Municipality': ['Idrija', 'Spodnja Idrija'],
  'Ig Municipality': ['Ig'],
  'Ivančna Gorica Municipality': ['Ivančna Gorica', 'Šentvid pri Stični'],
  'Izola Municipality': ['Izola', 'Jagodje'],
  'Jesenice Municipality': [
    'Hrušica',
    'Jesenice',
    'Koroška Bela',
    'Slovenski Javornik',
  ],
  'Jezersko Municipality': ['Zgornje Jezersko'],
  'Juršinci Municipality': ['Juršinci'],
  'Kamnik Municipality': ['Kamnik', 'Mekinje', 'Šmarca'],
  'Kanal ob Soči Municipality': ['Deskle', 'Kanal'],
  'Kidričevo Municipality': ['Kidričevo'],
  'Kobarid Municipality': ['Kobarid'],
  'Kobilje Municipality': ['Kobilje'],
  'Kočevje Municipality': ['Kočevje'],
  'Komen Municipality': ['Komen'],
  'Komenda Municipality': ['Komenda', 'Moste'],
  'Koper City Municipality': [
    'Dekani',
    'Hrvatini',
    'Koper',
    'Pobegi',
    'Prade',
    'Spodnje Škofije',
    'Sv. Anton',
  ],
  'Kostel Municipality': ['Kostel'],
  'Kozje Municipality': ['Kozje'],
  'Kranj City Municipality': [
    'Britof',
    'Golnik',
    'Kokrica',
    'Kranj',
    'Mlaka pri Kranju',
    'Zgornje Bitnje',
  ],
  'Kranjska Gora Municipality': ['Kranjska Gora', 'Mojstrana'],
  'Križevci Municipality': ['Križevci pri Ljutomeru'],
  Kungota: ['Zgornja Kungota'],
  'Kuzma Municipality': ['Kuzma'],
  'Laško Municipality': ['Laško'],
  'Lenart Municipality': ['Lenart v Slov. Goricah'],
  'Lendava Municipality': ['Lendava'],
  'Litija Municipality': ['Litija'],
  'Ljubljana City Municipality': [
    'Dravlje District',
    'Jarše District',
    'Ljubljana',
    'Opčina Ljubljana-Bežigrad',
    'Opština Ljubljana-Center',
    'Opština Ljubljana-Moste-Polje',
    'Rožnik District',
    'Šentvid District',
    'Sostro District',
    'Trnovo District',
    'Vič District',
  ],
  'Ljubno Municipality': ['Ljubno ob Savinji'],
  'Ljutomer Municipality': ['Ljutomer'],
  'Logatec Municipality': ['Logatec'],
  'Loška Dolina Municipality': ['Leskova Dolina'],
  'Loški Potok Municipality': ['Hrib-Loški Potok'],
  'Lovrenc na Pohorju Municipality': ['Lovrenc na Pohorju'],
  'Luče Municipality': ['Luče'],
  'Lukovica Municipality': ['Lukovica pri Domžalah'],
  'Majšperk Municipality': ['Majšperk'],
  'Maribor City Municipality': [
    'Bresternica',
    'Kamnica',
    'Limbuš',
    'Maribor',
    'Pekre',
    'Razvanje',
  ],
  'Markovci Municipality': ['Markovci'],
  'Medvode Municipality': [
    'Medvode',
    'Opština [historical] Ljubljana-Šiška',
    'Zgornje Pirniče',
  ],
  'Mengeš Municipality': ['Mengeš', 'Preserje pri Radomljah'],
  'Metlika Municipality': ['Metlika'],
  'Mežica Municipality': ['Mežica'],
  'Miklavž na Dravskem Polju Municipality': ['Miklavž na Dravskem Polju'],
  'Miren–Kostanjevica Municipality': ['Bilje', 'Miren'],
  'Mirna Peč Municipality': ['Mirna Peč'],
  'Mislinja Municipality': ['Mislinja'],
  'Moravče Municipality': ['Moravče'],
  'Moravske Toplice Municipality': ['Moravske Toplice'],
  'Mozirje Municipality': ['Mozirje'],
  'Municipality of Apače': ['Apače'],
  'Municipality of Ilirska Bistrica': ['Ilirska Bistrica'],
  'Municipality of Krško': ['Krško', 'Leskovec pri Krškem', 'Senovo'],
  'Municipality of Škofljica': ['Lavrica', 'Škofljica'],
  'Murska Sobota City Municipality': [
    'Bakovci',
    'Černelavci',
    'Krog',
    'Murska Sobota',
    'Rakičan',
  ],
  'Muta Municipality': ['Muta'],
  'Naklo Municipality': ['Naklo'],
  'Nazarje Municipality': ['Nazarje'],
  'Nova Gorica City Municipality': [
    'Kromberk',
    'Nova Gorica',
    'Prvačina',
    'Šempas',
    'Solkan',
  ],
  'Odranci Municipality': ['Odranci'],
  Oplotnica: ['Oplotnica'],
  'Ormož Municipality': ['Ormož'],
  'Osilnica Municipality': ['Osilnica'],
  'Pesnica Municipality': ['Pesnica pri Mariboru'],
  'Piran Municipality': ['Lucija', 'Piran', 'Portorož', 'Seča'],
  'Pivka Municipality': ['Pivka'],
  'Podčetrtek Municipality': ['Podčetrtek'],
  'Podlehnik Municipality': ['Podlehnik'],
  'Podvelka Municipality': ['Podvelka'],
  'Polzela Municipality': ['Polzela'],
  'Postojna Municipality': ['Postojna'],
  'Prebold Municipality': ['Prebold'],
  'Preddvor Municipality': ['Preddvor'],
  'Prevalje Municipality': ['Prevalje'],
  'Ptuj City Municipality': ['Ptuj'],
  'Puconci Municipality': ['Puconci'],
  'Rače–Fram Municipality': ['Fram', 'Morje', 'Rače'],
  'Radeče Municipality': ['Radeče'],
  'Radenci Municipality': ['Radenci'],
  'Radlje ob Dravi Municipality': ['Radlje ob Dravi'],
  'Radovljica Municipality': ['Lesce', 'Radovljica'],
  'Ravne na Koroškem Municipality': ['Kotlje', 'Ravne na Koroškem'],
  'Razkrižje Municipality': ['Razkrižje'],
  'Renče–Vogrsko Municipality': ['Renče', 'Volčja Draga'],
  'Ribnica Municipality': ['Ribnica'],
  'Ribnica na Pohorju Municipality': ['Ribnica na Pohorju'],
  'Rogaška Slatina Municipality': ['Rogaška Slatina'],
  'Rogašovci Municipality': ['Rogašovci'],
  'Rogatec Municipality': ['Rogatec'],
  'Ruše Municipality': ['Bistrica ob Dravi', 'Ruše'],
  'Šalovci Municipality': ['Šalovci'],
  'Selnica ob Dravi Municipality': ['Selnica ob Dravi'],
  'Semič Municipality': ['Semič'],
  'Šempeter–Vrtojba Municipality': [
    'Rožna Dolina',
    'Šempeter pri Gorici',
    'Vrtojba',
  ],
  'Šenčur Municipality': ['Hrastje', 'Šenčur'],
  'Šentilj Municipality': ['Selnica ob Muri', 'Šentilj v Slov. Goricah'],
  'Šentjernej Municipality': ['Šentjernej'],
  'Šentjur Municipality': ['Šentjur'],
  'Šentrupert Municipality': ['Šentrupert'],
  'Sevnica Municipality': ['Sevnica'],
  'Sežana Municipality': ['Sežana'],
  'Škocjan Municipality': ['Škocjan'],
  'Škofja Loka Municipality': ['Škofja Loka', 'Sv. Duh'],
  'Slovenj Gradec City Municipality': [
    'Legen',
    'Pameče',
    'Slovenj Gradec',
    'Šmartno pri Slovenj Gradcu',
  ],
  'Slovenska Bistrica Municipality': [
    'Pragersko',
    'Slovenska Bistrica',
    'Zgornja Polskava',
  ],
  'Slovenske Konjice Municipality': ['Slovenske Konjice'],
  'Šmarje pri Jelšah Municipality': ['Šmarje pri Jelšah'],
  'Šmarješke Toplice Municipality': ['Šmarjeta'],
  'Šmartno ob Paki Municipality': ['Šmartno ob Paki'],
  'Šmartno pri Litiji Municipality': ['Šmartno pri Litiji'],
  'Sodražica Municipality': ['Sodražica'],
  'Solčava Municipality': ['Solčava'],
  'Šoštanj Municipality': ['Ravne', 'Šoštanj', 'Topolšica'],
  'Središče ob Dravi': ['Središče ob Dravi'],
  'Starše Municipality': ['Starše'],
  'Štore Municipality': ['Štore'],
  'Straža Municipality': ['Straža'],
  'Sveta Ana Municipality': ['Sv. Ana v Slov. Goricah'],
  'Sveta Trojica v Slovenskih Goricah Municipality': [
    'Sv. Trojica v Slov. Goricah',
  ],
  'Sveti Andraž v Slovenskih Goricah Municipality': ['Vitomarci'],
  'Sveti Jurij v Slovenskih Goricah Municipality': ['Sveti Jurij ob Ščavnici'],
  'Sveti Tomaž Municipality': ['Sveti Tomaž'],
  'Tabor Municipality': ['Tabor'],
  'Tišina Municipality': ['Tišina'],
  'Tolmin Municipality': ['Tolmin'],
  'Trbovlje Municipality': ['Trbovlje'],
  'Trebnje Municipality': ['Trebnje'],
  'Trnovska Vas Municipality': ['Trnovska Vas'],
  'Tržič Municipality': ['Bistrica pri Tržiču', 'Tržič'],
  'Trzin Municipality': ['Črnuče District', 'Trzin'],
  'Turnišče Municipality': ['Turnišče'],
  'Velika Polana Municipality': ['Velika Polana'],
  'Velike Lašče Municipality': ['Velike Lašče'],
  'Veržej Municipality': ['Veržej'],
  'Videm Municipality': ['Videm pri Ptuju'],
  'Vipava Municipality': ['Vipava'],
  'Vitanje Municipality': ['Vitanje'],
  'Vodice Municipality': ['Vodice'],
  'Vojnik Municipality': ['Vojnik'],
  'Vransko Municipality': ['Vransko'],
  'Vrhnika Municipality': ['Verd', 'Vrhnika'],
  'Vuzenica Municipality': ['Vuzenica'],
  'Zagorje ob Savi Municipality': ['Izlake', 'Kisovec', 'Zagorje ob Savi'],
  'Žalec Municipality': [
    'Gotovlje',
    'Šempeter v Savinj. Dolini',
    'Zabukovica',
    'Žalec',
  ],
  'Zavrč Municipality': ['Zavrč'],
  'Železniki Municipality': ['Železniki'],
  'Žetale Municipality': ['Žetale'],
  'Žiri Municipality': ['Žiri'],
  'Žirovnica Municipality': ['Žirovnica'],
  'Zreče Municipality': ['Zreče'],
  'Žužemberk Municipality': ['Žužemberk'],
};
