export const SOMALIA_REGIONS_CITIES = {
  Bakool: ['Tayeeglow', 'Waajid', 'Xuddur', 'Yeed'],
  Banaadir: ['Mogadishu'],
  Bari: [
    'Bandarbeyla',
    'Bargaal',
    'Bereeda',
    'Bosaso',
    'Caluula',
    'Iskushuban',
    'Qandala',
  ],
  Bay: ['Baidoa', 'Buurhakaba'],
  Galguduud: ['Ceelbuur', 'Ceeldheer', 'Dhuusamarreeb'],
  Gedo: ['Baardheere', 'Garbahaarrey', 'Luuq'],
  Hiran: ['Beledweyne', 'Buulobarde', 'Jalalaqsi'],
  'Lower Juba': ['Buur Gaabo', 'Jamaame', 'Kismayo'],
  'Lower Shebelle': ['Afgooye', 'Marka', 'Qoryooley', 'Wanlaweyn'],
  'Middle Juba': ['Dujuuma', 'Jilib', 'Saacow'],
  'Middle Shebelle': ['Cadale', 'Jawhar', 'Mahaddayweyne'],
  Mudug: ['Gaalkacyo', 'Hobyo', 'Xarardheere'],
  Nugal: ['Eyl', 'Garoowe'],
  'Sanaag Region': ['Ceerigaabo', 'Las Khorey'],
  'Togdheer Region': ['Burao', 'Ceek', 'Oodweyne'],
};
