export const EL_SALVADOR_REGIONS_CITIES = {
  'Ahuachapán Department': [
    'Ahuachapán',
    'Atiquizaya',
    'Concepción de Ataco',
    'Guaymango',
    'Jujutla',
    'San Francisco Menéndez',
    'Tacuba',
  ],
  'Cabañas Department': ['Sensuntepeque', 'Victoria'],
  'Chalatenango Department': ['Chalatenango', 'Nueva Concepción'],
  'Cuscatlán Department': [
    'Cojutepeque',
    'San Martín',
    'Suchitoto',
    'Tecoluca',
    'Tenancingo',
  ],
  'La Libertad Department': [
    'Antiguo Cuscatlán',
    'Ciudad Arce',
    'La Libertad',
    'Nuevo Cuscatlán',
    'Quezaltepeque',
    'San Juan Opico',
    'San Pablo Tacachico',
    'Santa Tecla',
    'Zaragoza',
  ],
  'La Paz Department': [
    'El Rosario',
    'Olocuilta',
    'San Pedro Masahuat',
    'Santiago Nonualco',
    'Zacatecoluca',
  ],
  'La Unión Department': [
    'Anamorós',
    'Conchagua',
    'Intipucá',
    'La Unión',
    'Nueva Esparta',
    'Pasaquina',
    'San Alejo',
    'Santa Rosa de Lima',
  ],
  'Morazán Department': [
    'Cacaopera',
    'Corinto',
    'Guatajiagua',
    'Jocoro',
    'San Francisco',
    'Sociedad',
  ],
  'San Miguel Department': [
    'Chapeltique',
    'Chinameca',
    'Chirilagua',
    'Ciudad Barrios',
    'El Tránsito',
    'Lolotique',
    'Moncagua',
    'Nueva Guadalupe',
    'San Miguel',
    'San Rafael Oriente',
    'Sesori',
  ],
  'San Salvador Department': [
    'Aguilares',
    'Apopa',
    'Ayutuxtepeque',
    'Cuscatancingo',
    'Delgado',
    'El Paisnal',
    'Guazapa',
    'Ilopango',
    'Mejicanos',
    'Panchimalco',
    'Rosario de Mora',
    'San Marcos',
    'San Salvador',
    'Santo Tomás',
    'Soyapango',
    'Tonacatepeque',
  ],
  'San Vicente Department': ['Apastepeque', 'San Sebastián', 'San Vicente'],
  'Santa Ana Department': [
    'Candelaria de La Frontera',
    'Chalchuapa',
    'Coatepeque',
    'El Congo',
    'Metapán',
    'Santa Ana',
    'Texistepeque',
  ],
  'Sonsonate Department': [
    'Acajutla',
    'Armenia',
    'Izalco',
    'Juayúa',
    'Nahuizalco',
    'San Antonio del Monte',
    'Sonsonate',
    'Sonzacate',
  ],
  'Usulután Department': [
    'Berlín',
    'Concepción Batres',
    'Jiquilisco',
    'Jucuapa',
    'Jucuarán',
    'Ozatlán',
    'Puerto El Triunfo',
    'San Agustín',
    'Santa Elena',
    'Santiago de María',
    'Usulután',
  ],
};
