export const SYRIA_GOVERNORATES_CITIES = {
  'Al-Hasakah': [
    'Ad Darbāsīyah',
    'Al Ḩasakah',
    'Al Mālikīyah',
    'Al Qāmishlī',
    'Al-Malikiyah District',
    'Amude',
  ],
  'Al-Raqqah': [
    'Al-Thawrah District',
    'Ar Raqqah',
    'Ar-Raqqah District',
    'Ath Thawrah',
    'Tall Abyaḑ',
    'Tell Abyad District',
  ],
  Aleppo: [
    '‘Afrīn',
    '‘Ayn al ‘Arab',
    'Afrin District',
    'Al Atārib',
    'Al Bāb',
    'Al-Bab District',
    'Aleppo',
    'As Safīrah',
    'Azaz District',
    'Dayr Ḩāfir',
    'I‘zāz',
    'Jarābulus',
    'Kafr Şaghīr',
    'Khanāşir',
    'Manbij',
    'Manbij District',
    'Mount Simeon District',
    'Nubl',
    'Şūrān',
    'Tādif',
    'Tall Rif‘at',
  ],
  'As-Suwayda': [
    'As-Suwayda',
    'As-Suwayda District',
    'Şalākhid',
    'Şalkhad',
    'Salkhad District',
    'Shahbā',
    'Shahba District',
  ],
  Damascus: ['Damascus'],
  Daraa: [
    'Al Ḩarāk',
    'Al Muzayrīb',
    'Al-Sanamayn District',
    'Aş Şanamayn',
    'Ash Shaykh Miskīn',
    'Buşrá ash Shām',
    'Dar‘ā',
    'Ghabāghib',
    'Inkhil',
    'Izra District',
    'Izra‘',
    'Jāsim',
    'Nawá',
    'Ţafas',
    'Tasīl',
  ],
  'Deir ez-Zor': [
    'Al Mayādīn',
    'Ālbū Kamāl',
    'Deir ez-Zor',
    'Hajīn',
    'Subaykhān',
  ],
  Hama: [
    'Al-Salamiyah District',
    'As Salamīyah',
    'As Suqaylibīyah',
    'Ḩalfāyā',
    'Hama District',
    'Ḩamāh',
    'Kafr Zaytā',
    'Maşyāf',
    'Masyaf District',
    'Mūrak',
    'Souran',
    'Tall Salḩab',
    'Ţayyibat al Imām',
    'Tremseh',
  ],
  Homs: [
    'Al Ghanţū',
    'Al Qaryatayn',
    'Al Quşayr',
    'Al-Rastan District',
    'Ar Rastan',
    'Hisya',
    'Homs',
    'Kafr Lāhā',
    'Mukharram al Fawqānī',
    'Şadad',
    'Tadmur',
    'Tadmur District',
    'Tallbīsah',
    'Tallkalakh',
  ],
  Idlib: [
    'Ad Dānā',
    'Arīḩā',
    'Armanāz',
    'Binnish',
    'Darkūsh',
    'Harem District',
    'Ḩārim',
    'Idlib',
    'Jisr al-Shughur District',
    'Jisr ash Shughūr',
    'Kafr Takhārīm',
    'Kafranbel',
    'Khān Shaykhūn',
    'Ma‘arratmişrīn',
    "Maarrat al-Nu'man District",
    'Salqīn',
    'Sarāqib',
    'Sarmīn',
    'Taftanāz',
  ],
  Latakia: [
    'Al-Haffah District',
    'Jablah',
    'Jableh District',
    'Kassab',
    'Latakia',
    'Latakia District',
    'Qardaha District',
    'Şlinfah',
  ],
  Quneitra: ['Al Qunayţirah'],
  'Rif Dimashq': [
    '‘Irbīn',
    'Al Kiswah',
    'Al Quţayfah',
    'Al-Zabadani District',
    'An Nabk',
    'At Tall',
    'Az Zabadānī',
    'Dārayyā',
    'Dayr al ‘Aşāfīr',
    'Douma',
    'Ḩarastā',
    'Jaramānā',
    'Jayrūd',
    'Ma‘lūlā',
    'Medaya',
    'Qārah',
    'Qaţanā',
    'Şaydnāyā',
    'Yabrūd',
  ],
  Tartus: [
    'Ad Duraykīsh',
    'Bāniyās',
    'Kaff al-Jaa',
    'Safita District',
    'Satita',
    'Tartouss',
  ],
};
