export const ESWATINI_REGIONS_CITIES = {
  'Hhohho District': [
    'Bulembu',
    'Hhukwini',
    'Lobamba',
    'Mbabane',
    'Nkhaba',
    'Piggs Peak',
  ],
  'Lubombo District': [
    'Big Bend',
    'Dvokodvweni Inkhundla',
    'Lomashasha',
    'Mhlume',
    'Nsoko',
    'Siteki',
    'Tshaneni',
    'Vuvulane',
  ],
  'Manzini District': [
    'Bhunya',
    'Ekukhanyeni',
    'Kwaluseni',
    'Malkerns',
    'Manzini',
    'Manzini South',
    'Mhlambanyatsi',
    'Ngwempisi',
    'Ntondozi',
    'Sidvokodvo',
  ],
  'Shiselweni District': [
    'Hlatikulu',
    'Hluti',
    'Kubuta',
    'Lavumisa',
    'Matsanjeni',
    'Ngudzeni',
    'Nhlangano',
    'Nkwene',
    'Sigwe Inkhundla',
    'Zombodze Ikhundla',
  ],
};
