export const THAILAND_PROVINCES_CITIES = {
  'Amnat Charoen': [
    'Amnat Charoen',
    'Amphoe Chanuman',
    'Amphoe Hua Taphan',
    'Amphoe Lue Amnat',
    'Amphoe Mueang Amnat Charoen',
    'Amphoe Pathum Ratchawongsa',
    'Amphoe Phana',
    'Amphoe Senangkhanikhom',
  ],
  'Ang Thong': [
    'Amphoe Chaiyo',
    'Amphoe Mueang Ang Thong',
    'Amphoe Pa Mok',
    'Amphoe Pho Thong',
    'Amphoe Sawaeng Ha',
    'Amphoe Wiset Chai Chan',
    'Ang Thong',
    'Ban Thai Tan',
    'Chaiyo',
    'Pho Thong',
    'Wiset Chaichan',
  ],
  Bangkok: [
    'Bang Bon',
    'Bang Kapi',
    'Bang Khae',
    'Bang Khen',
    'Bang Kho laen',
    'Bang Khun thain',
    'Bang Na',
    'Bang Phlat',
    'Bang Rak',
    'Bang Sue',
    'Bangkok',
    'Bangkok Noi',
    'Bangkok Yai',
    'Bueng Kum',
    'Chatu Chak',
    'Chom Thong',
    'Din Daeng',
    'Don Mueang',
    'Dusit',
    'Huai Khwang',
    'Khan Na Yao',
    'Khlong Sam Wa',
    'Khlong San',
    'Khlong Toei',
    'Lak Si',
    'Lat Krabang',
    'Lat Phrao',
    'Min Buri',
    'Nong Chok',
    'Nong Khaem',
    'Parthum Wan',
    'Phasi Charoen',
    'Phaya Thai',
    'Phra Khanong',
    'Phra Nakhon',
    'Pom Prap Sattru Phai',
    'Pra Wet',
    'Rat Burana',
    'Ratchathewi',
    'Sai Mai',
    'Samphanthawong',
    'Saphan Sung',
    'Sathon',
    'Suanluang',
    'Taling Chan',
    'Thawi Watthana',
    'Thon buri',
    'Thung khru',
    'Vadhana',
    'Wang Thong Lang',
    'Yan na wa',
  ],
  'Bueng Kan': [
    'Amphoe Bueng Khong Long',
    'Amphoe Bung Khla',
    'Amphoe Mueang Bueng Kan',
    'Amphoe Pak Khat',
    'Amphoe Phon Charoen',
    'Amphoe Seka',
    'Amphoe Si Wilai',
    'Amphoe So Phisai',
    'Bueng Kan',
    'Seka',
  ],
  'Buri Ram': [
    'Amphoe Ban Dan',
    'Amphoe Ban Kruat',
    'Amphoe Ban Mai Chaiyaphot',
    'Amphoe Chaloem Phra Kiat',
    'Amphoe Chamni',
    'Amphoe Huai Rat',
    'Amphoe Khaen Dong',
    'Amphoe Khu Mueang',
    'Amphoe Krasang',
    'Amphoe Lahan Sai',
    'Amphoe Lam Plai Mat',
    'Amphoe Mueang Buriram',
    'Amphoe Na Pho',
    'Amphoe Nang Rong',
    'Amphoe Non Din Daeng',
    'Amphoe Non Suwan',
    'Amphoe Nong Hong',
    'Amphoe Nong Ki',
    'Amphoe Pa Kham',
    'Amphoe Phlapphla Chai',
    'Amphoe Phutthaisong',
    'Amphoe Prakhon Chai',
    'Amphoe Satuek',
    'Buri Ram',
    'Nang Rong',
    'Nong Ki',
    'Prakhon Chai',
    'Satuek',
  ],
  Chachoengsao: [
    'Amphoe Ban Pho',
    'Amphoe Bang Khla',
    'Amphoe Bang Nam Priao',
    'Amphoe Bang Pakong',
    'Amphoe Khlong Khuean',
    'Amphoe Mueang Chachoengsao',
    'Amphoe Phanom Sarakham',
    'Amphoe Plaeng Yao',
    'Amphoe Ratchasan',
    'Amphoe Sanam Chai Khet',
    'Amphoe Tha Takiap',
    'Bang Khla',
    'Bang Nam Priao',
    'Bang Pakong',
    'Chachoengsao',
    'Khlong Khuean',
    'Phanom Sarakham',
  ],
  'Chai Nat': [
    'Amphoe Hankha',
    'Amphoe Manorom',
    'Amphoe Mueang Chainat',
    'Amphoe Noen Kham',
    'Amphoe Nong Mamong',
    'Amphoe Sankhaburi',
    'Amphoe Sapphaya',
    'Amphoe Wat Sing',
    'Chai Nat',
  ],
  Chaiyaphum: [
    'Bamnet Narong',
    'Chaiyaphum',
    'Kaeng Khro',
    'Kaset Sombun',
    'Nakhon Nayok',
    'Phu Khiao',
  ],
  Chanthaburi: [
    'Amphoe Kaeng Hang Maeo',
    'Amphoe Khao Khitchakut',
    'Amphoe Khlung',
    'Amphoe Laem Sing',
    'Amphoe Makham',
    'Amphoe Mueang Chanthaburi',
    'Amphoe Na Yai Am',
    'Amphoe Pong Nam Ron',
    'Amphoe Soi Dao',
    'Amphoe Tha Mai',
    'Chanthaburi',
    'Khlung',
    'Laem Sing',
    'Pong Nam Ron',
    'Tha Mai',
  ],
  'Chiang Mai': [
    'Amphoe Chai Prakan',
    'Amphoe Chiang Dao',
    'Amphoe Chom Thong',
    'Amphoe Doi Lo',
    'Amphoe Doi Saket',
    'Amphoe Doi Tao',
    'Amphoe Fang',
    'Amphoe Galyani Vadhana',
    'Amphoe Hang Dong',
    'Amphoe Hot',
    'Amphoe Mae Ai',
    'Amphoe Mae Chaem',
    'Amphoe Mae On',
    'Amphoe Mae Rim',
    'Amphoe Mae Taeng',
    'Amphoe Mae Wang',
    'Amphoe Mueang Chiang Mai',
    'Amphoe Om Koi',
    'Amphoe Phrao',
    'Amphoe Samoeng',
    'Amphoe San Kamphaeng',
    'Amphoe San Pa Tong',
    'Amphoe San Sai',
    'Amphoe Saraphi',
    'Amphoe Wiang Haeng',
    'Chai Prakan',
    'Chiang Mai',
    'Chom Thong',
    'Fang',
    'Hang Dong',
    'Pai',
    'San Kamphaeng',
    'San Pa Tong',
  ],
  'Chiang Rai': [
    'Amphoe Chiang Khong',
    'Amphoe Chiang Saen',
    'Amphoe Doi Luang',
    'Amphoe Khun Tan',
    'Amphoe Mae Chan',
    'Amphoe Mae Fa Luang',
    'Amphoe Mae Lao',
    'Amphoe Mae Sai',
    'Amphoe Mae Suai',
    'Amphoe Mueang Chiang Rai',
    'Amphoe Pa Daet',
    'Amphoe Phan',
    'Amphoe Phaya Mengrai',
    'Amphoe Thoeng',
    'Amphoe Wiang Chai',
    'Amphoe Wiang Chiang Rung',
    'Amphoe Wiang Kaen',
    'Amphoe Wiang Pa Pao',
    'Chiang Khong',
    'Chiang Rai',
    'Chiang Saen',
    'Mae Chan',
    'Mae Sai',
    'Pa Daet',
  ],
  'Chon Buri': [
    'Amphoe Ban Bueng',
    'Amphoe Bo Thong',
    'Amphoe Ko Chan',
    'Amphoe Ko Si Chang',
    'Amphoe Nong Yai',
    'Amphoe Phan Thong',
    'Amphoe Phanat Nikhom',
    'Amphoe Sattahip',
    'Amphoe Si Racha',
    'Ban Bueng',
    'Ban Ko Lan',
    'Ban Talat Bueng',
    'Bang Lamung',
    'Bang Lamung District',
    'Chon Buri',
    'Ko Si Chang',
    'Mueang Chonburi District',
    'Pattaya',
    'Phan Thong',
    'Phanat Nikhom',
    'Sattahip',
    'Si Racha',
  ],
  Chumphon: [
    'Amphoe Lamae',
    'Amphoe Lang Suan',
    'Amphoe Mueang Chumphon',
    'Amphoe Pathio',
    'Amphoe Phato',
    'Amphoe Sawi',
    'Amphoe Tha Sae',
    'Amphoe Thung Tako',
    'Ban Nam Yuen',
    'Chumphon',
    'Lang Suan',
  ],
  Kalasin: [
    'Amphoe Don Chan',
    'Amphoe Huai Mek',
    'Amphoe Huai Phueng',
    'Amphoe Kamalasai',
    'Amphoe Kham Muang',
    'Amphoe Khao Wong',
    'Amphoe Khong Chai',
    'Amphoe Kuchinarai',
    'Amphoe Mueang Kalasin',
    'Amphoe Na Khu',
    'Amphoe Na Mon',
    'Amphoe Nong Kung Si',
    'Amphoe Rong Kham',
    'Amphoe Sahatsakhan',
    'Amphoe Sam Chai',
    'Amphoe Somdet',
    'Amphoe Tha Khantho',
    'Amphoe Yang Talat',
    'Huai Mek',
    'Kalasin',
    'Kamalasai',
    'Khao Wong',
    'Kuchinarai',
    'Nong Kung Si',
    'Yang Talat',
  ],
  'Kamphaeng Phet': [
    'Amphoe Bueng Samakkhi',
    'Amphoe Khanu Woralaksaburi',
    'Amphoe Khlong Khlung',
    'Amphoe Khlong Lan',
    'Amphoe Kosamphi Nakhon',
    'Amphoe Lan Krabue',
    'Amphoe Mueang Kamphaeng Phet',
    'Amphoe Pang Sila Thong',
    'Amphoe Phran Kratai',
    'Amphoe Sai Ngam',
    'Amphoe Sai Thong Watthana',
    'Kamphaeng Phet',
    'Khanu Woralaksaburi',
    'Lan Krabue',
  ],
  Kanchanaburi: [
    'Amphoe Bo Phloi',
    'Amphoe Dan Makham Tia',
    'Amphoe Huai Krachao',
    'Amphoe Lao Khwan',
    'Amphoe Mueang Kanchanaburi',
    'Amphoe Nong Prue',
    'Amphoe Phanom Thuan',
    'Amphoe Sai Yok',
    'Amphoe Sangkhla Buri',
    'Amphoe Si Sawat',
    'Amphoe Tha Maka',
    'Amphoe Tha Muang',
    'Amphoe Thong Pha Phum',
    'Bo Phloi',
    'Kanchanaburi',
    'Phanom Thuan',
    'Sangkhla Buri',
    'Tha Maka',
    'Tha Muang',
  ],
  'Khon Kaen': [
    'Amphoe Ban Fang',
    'Amphoe Ban Haet',
    'Amphoe Ban Phai',
    'Amphoe Chonnabot',
    'Amphoe Chum Phae',
    'Amphoe Khao Suan Kwang',
    'Amphoe Khok Pho Chai',
    'Amphoe Kranuan',
    'Amphoe Mancha Khiri',
    'Amphoe Mueang Khon Kaen',
    'Amphoe Nam Phong',
    'Amphoe Non Sila',
    'Amphoe Nong Na Kham',
    'Amphoe Nong Ruea',
    'Amphoe Nong Song Hong',
    'Amphoe Phon',
    'Amphoe Phra Yuen',
    'Amphoe Phu Pha Man',
    'Amphoe Phu Wiang',
    'Amphoe Pueai Noi',
    'Amphoe Sam Sung',
    'Amphoe Si Chom Phu',
    'Amphoe Ubolratana',
    'Amphoe Waeng Noi',
    'Amphoe Waeng Yai',
    'Amphoe Wiang Kao',
    'Ban Phai',
    'Chum Phae',
    'Khon Kaen',
    'Kranuan',
    'Phon',
    'Pueai Noi',
  ],
  Krabi: [
    'Amphoe Ao Luek',
    'Amphoe Khao Phanom',
    'Amphoe Khlong Thom',
    'Amphoe Ko Lanta',
    'Amphoe Lam Thap',
    'Amphoe Mueang Krabi',
    'Amphoe Nuea Khlong',
    'Amphoe Plai Phraya',
    'Ao Luek',
    'Ko Lanta',
    'Krabi',
    'Nuea Khlong',
    'Saladan',
  ],
  Lampang: [
    'Amphoe Chae Hom',
    'Amphoe Hang Chat',
    'Amphoe Ko Kha',
    'Amphoe Mae Mo',
    'Amphoe Mae Phrik',
    'Amphoe Mae Tha',
    'Amphoe Mueang Lampang',
    'Amphoe Mueang Pan',
    'Amphoe Ngao',
    'Amphoe Soem Ngam',
    'Amphoe Sop Prap',
    'Amphoe Thoen',
    'Amphoe Wang Nuea',
    'Lampang',
    'Thoen',
    'Wang Nuea',
  ],
  Lamphun: [
    'Amphoe Ban Hong',
    'Amphoe Ban Thi',
    'Amphoe Li',
    'Amphoe Mae Tha',
    'Amphoe Mueang Lamphun',
    'Amphoe Pa Sang',
    'Amphoe Thung Hua Chang',
    'Amphoe Wiang Nong Long',
    'Lamphun',
    'Mae Tha',
    'Pa Sang',
  ],
  Loei: [
    'Amphoe Chiang Khan',
    'Amphoe Dan Sai',
    'Amphoe Erawan',
    'Amphoe Mueang Loei',
    'Amphoe Na Duang',
    'Amphoe Na Haeo',
    'Amphoe Nong Hin',
    'Amphoe Pak Chom',
    'Amphoe Pha Khao',
    'Amphoe Phu Kradueng',
    'Amphoe Phu Luang',
    'Amphoe Phu Ruea',
    'Amphoe Tha Li',
    'Amphoe Wang Saphung',
    'Loei',
    'Phu Kradueng',
    'Wang Saphung',
  ],
  'Lop Buri': [
    'Amphoe Ban Mi',
    'Amphoe Chai Badan',
    'Amphoe Khok Charoen',
    'Amphoe Khok Samrong',
    'Amphoe Lam Sonthi',
    'Amphoe Nong Muang',
    'Amphoe Phatthana Nikhom',
    'Amphoe Sa Bot',
    'Amphoe Tha Luang',
    'Amphoe Tha Wung',
    'Chai Badan',
    'Lop Buri',
    'Muang Lop Buri District',
  ],
  'Mae Hong Son': [
    'Amphoe Khun Yuam',
    'Amphoe Mae La Noi',
    'Amphoe Mae Sariang',
    'Amphoe Mueang Mae Hong Son',
    'Amphoe Pai',
    'Amphoe Pang Mapha',
    'Amphoe Sop Moei',
    'Mae Hong Son',
  ],
  'Maha Sarakham': [
    'Amphoe Borabue',
    'Amphoe Chiang Yuen',
    'Amphoe Chuen Chom',
    'Amphoe Kae Dam',
    'Amphoe Kantharawichai',
    'Amphoe Kosum Phisai',
    'Amphoe Kut Rang',
    'Amphoe Mueang Maha Sarakham',
    'Amphoe Na Chueak',
    'Amphoe Na Dun',
    'Amphoe Phayakkhaphum Phisai',
    'Amphoe Wapi Pathum',
    'Amphoe Yang Si Surat',
    'Kosum Phisai',
    'Maha Sarakham',
    'Phayakkhaphum Phisai',
    'Wapi Pathum',
  ],
  Mukdahan: [
    'Amphoe Don Tan',
    'Amphoe Dong Luang',
    'Amphoe Khamcha-i',
    'Amphoe Mueang Mukdahan',
    'Amphoe Nikhom Kham Soi',
    'Amphoe Nong Sung',
    'Amphoe Wan Yai',
    'Mukdahan',
  ],
  'Nakhon Nayok': [
    'Amphoe Ban Na',
    'Amphoe Mueang Nakhon Nayok',
    'Amphoe Ongkharak',
    'Amphoe Pak Phli',
    'Nakhon Nayok',
  ],
  'Nakhon Pathom': [
    'Amphoe Bang Len',
    'Amphoe Don Tum',
    'Amphoe Mueang Nakhon Pathom',
    'Amphoe Nakhon Chai Si',
    'Amphoe Phutthamonthon',
    'Amphoe Sam Phran',
    'Bang Len',
    'Kamphaeng Saen District',
    'Nakhon Pathom',
    'Sam Phran',
  ],
  'Nakhon Phanom': [
    'Amphoe Ban Phaeng',
    'Amphoe Mueang Nakhon Phanom',
    'Amphoe Na Kae',
    'Amphoe Na Thom',
    'Amphoe Na Wa',
    'Amphoe Phon Sawan',
    'Amphoe Pla Pak',
    'Amphoe Renu Nakhon',
    'Amphoe Si Songkhram',
    'Amphoe Tha Uthen',
    'Amphoe That Phanom',
    'Amphoe Wangyang',
    'Na Wa',
    'Nakhon Phanom',
    'That Phanom',
  ],
  'Nakhon Ratchasima': [
    'Amphoe Ban Lueam',
    'Amphoe Bua Lai',
    'Amphoe Bua Yai',
    'Amphoe Chakkarat',
    'Amphoe Chaloem Phra Kiat',
    'Amphoe Chok Chai',
    'Amphoe Chum Phuang',
    'Amphoe Dan Khun Thot',
    'Amphoe Huai Thalaeng',
    'Amphoe Kaeng Sanam Nang',
    'Amphoe Kham Sakae Saeng',
    'Amphoe Kham Thale So',
    'Amphoe Khon Buri',
    'Amphoe Khong',
    'Amphoe Lam Thamen Chai',
    'Amphoe Mueang Nakhon Ratchasima',
    'Amphoe Mueang Yang',
    'Amphoe Non Daeng',
    'Amphoe Non Sung',
    'Amphoe Non Thai',
    'Amphoe Nong Bun Mak',
    'Amphoe Pak Chong',
    'Amphoe Pak Thong Chai',
    'Amphoe Phimai',
    'Amphoe Phra Thong Kham',
    'Amphoe Prathai',
    'Amphoe Sida',
    'Amphoe Sikhio',
    'Amphoe Sikhiu',
    'Amphoe Soeng Sang',
    'Amphoe Sung Noen',
    'Amphoe Thepharak',
    'Amphoe Wang Nam Khiao',
    'Ban Huai Thalaeng',
    'Bua Yai',
    'Chok Chai',
    'Dan Khun Thot',
    'Kham Sakae Saeng',
    'Khon Buri',
    'Nakhon Ratchasima',
    'Non Sung',
    'Non Thai',
    'Pak Chong',
    'Pak Thong Chai',
    'Phimai',
    'Soeng Sang',
    'Sung Noen',
  ],
  'Nakhon Sawan': [
    'Amphoe Banphot Phisai',
    'Amphoe Chum Ta Bong',
    'Amphoe Chumsaeng',
    'Amphoe Kao Liao',
    'Amphoe Krok Phra',
    'Amphoe Lat Yao',
    'Amphoe Mae Poen',
    'Amphoe Mae Wong',
    'Amphoe Mueang Nakhon Sawan',
    'Amphoe Nong Bua',
    'Amphoe Phai Sali',
    'Amphoe Phayuha Khiri',
    'Amphoe Tak Fa',
    'Amphoe Takhli',
    'Amphoe Tha Tako',
    'Kao Liao',
    'Lat Yao',
    'Nakhon Sawan',
    'Nong Bua',
    'Phai Sali',
    'Phayuha Khiri',
    'Takhli',
  ],
  'Nakhon Si Thammarat': [
    'Amphoe Bang Khan',
    'Amphoe Cha-uat',
    'Amphoe Chaloem Phra Kiat',
    'Amphoe Chang Klang',
    'Amphoe Chawang',
    'Amphoe Chian Yai',
    'Amphoe Chulabhorn',
    'Amphoe Hua Sai',
    'Amphoe Khanom',
    'Amphoe Lan Saka',
    'Amphoe Mueang Nakhon Si Thammarat',
    'Amphoe Na Bon',
    'Amphoe Nopphitam',
    'Amphoe Pak Phanang',
    'Amphoe Phipun',
    'Amphoe Phra Phrom',
    'Amphoe Phrom Khiri',
    'Amphoe Ron Phibun',
    'Amphoe Sichon',
    'Amphoe Tha Sala',
    'Amphoe Tham Phannara',
    'Amphoe Thung Song',
    'Amphoe Thung Yai',
    'Chawang',
    'Nakhon Si Thammarat',
    'Pak Phanang',
    'Ron Phibun',
    'Tham Phannara',
    'Thung Song',
  ],
  Nan: [
    'Amphoe Ban Luang',
    'Amphoe Bo Kluea',
    'Amphoe Chaloem Phra Kiat',
    'Amphoe Chiang Klang',
    'Amphoe Mae Charim',
    'Amphoe Mueang Nan',
    'Amphoe Na Muen',
    'Amphoe Na Noi',
    'Amphoe Phu Phiang',
    'Amphoe Pua',
    'Amphoe Santi Suk',
    'Amphoe Song Khwae',
    'Amphoe Tha Wang Pha',
    'Amphoe Thung Chang',
    'Amphoe Wiang Sa',
    'Chiang Klang',
    'Nan',
  ],
  Narathiwat: [
    'Amphoe Ba Cho',
    'Amphoe Chanae',
    'Amphoe Cho-airong',
    'Amphoe Mueang Narathiwat',
    'Amphoe Ra-ngae',
    'Amphoe Rueso',
    'Amphoe Si Sakhon',
    'Amphoe Su-ngai Kolok',
    'Amphoe Su-ngai Padi',
    'Amphoe Sukhirin',
    'Amphoe Tak Bai',
    'Amphoe Waeng',
    'Amphoe Yi-ngo',
    'Ban Su-ngai Pa Di',
    'Narathiwat',
    'Ra-ngae',
    'Su-ngai Kolok',
    'Tak Bai',
  ],
  'Nong Bua Lam Phu': [
    'Amphoe Mueang Nong Bua Lamphu',
    'Amphoe Na Klang',
    'Amphoe Na Wang',
    'Amphoe Non Sang',
    'Amphoe Si Bun Rueang',
    'Amphoe Suwannakhuha',
    'Na Klang',
    'Non Sang',
    'Nong Bua Lamphu',
    'Si Bun Rueang',
  ],
  'Nong Khai': [
    'Amphoe Fao Rai',
    'Amphoe Mueang Nong Khai',
    'Amphoe Pho Tak',
    'Amphoe Phonphisai',
    'Amphoe Rattanawapi',
    'Amphoe Sa Khrai',
    'Amphoe Sangkhom',
    'Amphoe Si Chiang Mai',
    'Amphoe Tha Bo',
    'Nong Khai',
    'Phon Charoen',
    'Sangkhom',
    'Si Chiang Mai',
    'Tha Bo',
  ],
  Nonthaburi: [
    'Amphoe Bang Bua Thong',
    'Amphoe Bang Kruai',
    'Amphoe Bang Yai',
    'Amphoe Mueang Nonthaburi',
    'Amphoe Pak Kret',
    'Amphoe Sai Noi',
    'Bang Bua Thong',
    'Bang Kruai',
    'Bang Yai',
    'Mueang Nonthaburi',
    'Pak Kret',
  ],
  'Pathum Thani': [
    'Amphoe Khlong Luang',
    'Amphoe Lam Luk Ka',
    'Amphoe Lat Lum Kaeo',
    'Amphoe Mueang Pathum Thani',
    'Amphoe Nong Suea',
    'Amphoe Thanyaburi',
    'Ban Lam Luk Ka',
    'Khlong Luang',
    'Pathum Thani',
  ],
  Pattani: [
    'Amphoe Kapho',
    'Amphoe Khok Pho',
    'Amphoe Mae Lan',
    'Amphoe Mai Kaen',
    'Amphoe Mayo',
    'Amphoe Mueang Pattani',
    'Amphoe Nong Chik',
    'Amphoe Panare',
    'Amphoe Sai Buri',
    'Amphoe Thung Yang Daeng',
    'Amphoe Yarang',
    'Amphoe Yaring',
    'Nong Chik',
    'Pattani',
    'Sai Buri',
    'Yaring',
  ],
  Phangnga: [
    'Amphoe Kapong',
    'Amphoe Khura Buri',
    'Amphoe Ko Yao',
    'Amphoe Mueang Phangnga',
    'Amphoe Takua Pa',
    'Amphoe Takua Thung',
    'Amphoe Thai Mueang',
    'Amphoe Thap Put',
    'Ban Ao Nang',
    'Ban Khao Lak',
    'Ban Phru Nai',
    'Phang Nga',
  ],
  Phatthalung: [
    'Amphoe Bang Kaeo',
    'Amphoe Khao Chaison',
    'Amphoe Khuan Khanun',
    'Amphoe Kong Ra',
    'Amphoe Mueang Phatthalung',
    'Amphoe Pa Bon',
    'Amphoe Pa Phayom',
    'Amphoe Pak Phayun',
    'Amphoe Si Banphot',
    'Amphoe Srinagarindra',
    'Amphoe Tamot',
    'Phatthalung',
  ],
  Phayao: [
    'Amphoe Chiang Kham',
    'Amphoe Chiang Muan',
    'Amphoe Chun',
    'Amphoe Dok Kham Tai',
    'Amphoe Mae Chai',
    'Amphoe Mueang Phayao',
    'Amphoe Phu Kam Yao',
    'Amphoe Phu Sang',
    'Amphoe Pong',
    'Chiang Kham',
    'Dok Kham Tai',
    'Mae Chai',
    'Phayao',
    'Pong',
  ],
  Phetchabun: [
    'Amphoe Bueng Sam Phan',
    'Amphoe Chon Daen',
    'Amphoe Khao Kho',
    'Amphoe Lom Kao',
    'Amphoe Lom Sak',
    'Amphoe Mueang Phetchabun',
    'Amphoe Nam Nao',
    'Amphoe Nong Phai',
    'Amphoe Si Thep',
    'Amphoe Wang Pong',
    'Amphoe Wichian Buri',
    'Chon Daen',
    'Lom Sak',
    'Nong Phai',
    'Phetchabun',
    'Wichian Buri',
  ],
  Phetchaburi: [
    'Amphoe Ban Laem',
    'Amphoe Ban Lat',
    'Amphoe Cha-am',
    'Amphoe Kaeng Krachan',
    'Amphoe Khao Yoi',
    'Amphoe Mueang Phetchaburi',
    'Amphoe Nong Ya Plong',
    'Amphoe Tha Yang',
    'Cha-am',
    'Khao Yoi',
    'Phetchaburi',
    'Tha Yang',
  ],
  Phichit: [
    'Amphoe Bang Mun Nak',
    'Amphoe Bueng Na Rang',
    'Amphoe Dong Charoen',
    'Amphoe Mueang Phichit',
    'Amphoe Pho Prathap Chang',
    'Amphoe Pho Thale',
    'Amphoe Sak Lek',
    'Amphoe Taphan Hin',
    'Amphoe Thap Khlo',
    'Amphoe Wachira Barami',
    'Amphoe Wang Sai Phun',
    'Bang Mun Nak',
    'Bueng Na Rang',
    'Phichit',
    'Taphan Hin',
    'Thap Khlo',
    'Wang Sai Phun',
  ],
  Phitsanulok: [
    'Amphoe Bang Krathum',
    'Amphoe Bang Rakam',
    'Amphoe Chat Trakan',
    'Amphoe Mueang Phitsanulok',
    'Amphoe Nakhon Thai',
    'Amphoe Noen Maprang',
    'Amphoe Phrom Phiram',
    'Amphoe Wang Thong',
    'Amphoe Wat Bot',
    'Bang Krathum',
    'Bang Rakam',
    'Chat Trakan',
    'Nakhon Thai',
    'Phitsanulok',
  ],
  'Phra Nakhon Si Ayutthaya': [
    'Amphoe Ban Phraek',
    'Amphoe Bang Ban',
    'Amphoe Bang Pa-in',
    'Amphoe Bang Pahan',
    'Amphoe Bang Sai',
    'Amphoe Lat Bua Luang',
    'Amphoe Maha Rat',
    'Amphoe Nakhon Luang',
    'Amphoe Phachi',
    'Amphoe Phak Hai',
    'Amphoe Phra Nakhon Si Ayutthaya',
    'Amphoe Sena',
    'Amphoe Tha Ruea',
    'Amphoe Uthai',
    'Amphoe Wang Noi',
    'Ban Bang Kadi Pathum Thani',
    'Bang Ban',
    'Bang Pa-in',
    'Nakhon Luang',
    'Phak Hai',
    'Phra Nakhon Si Ayutthaya',
    'Tha Ruea',
    'Wang Noi',
  ],
  Phrae: [
    'Amphoe Den Chai',
    'Amphoe Long',
    'Amphoe Mueang Phrae',
    'Amphoe Nong Muang Khai',
    'Amphoe Rong Kwang',
    'Amphoe Song',
    'Amphoe Sung Men',
    'Amphoe Wang Chin',
    'Den Chai',
    'Long',
    'Phrae',
    'Rong Kwang',
  ],
  Phuket: [
    'Amphoe Kathu',
    'Amphoe Mueang Phuket',
    'Amphoe Thalang',
    'Ban Chalong',
    'Ban Karon',
    'Ban Kata',
    'Ban Ko Kaeo',
    'Ban Mai Khao',
    'Ban Ratsada',
    'Ban Talat Nua',
    'Ban Talat Yai',
    'Kathu',
    'Nai Harn',
    'Patong',
    'Phuket',
    'Rawai',
    'Wichit',
  ],
  'Prachin Buri': [
    'Amphoe Ban Sang',
    'Amphoe Kabin Buri',
    'Amphoe Mueang Prachin Buri',
    'Amphoe Na Di',
    'Amphoe Prachantakham',
    'Amphoe Si Maha Phot',
    'Amphoe Si Mahosot',
    'Kabin Buri',
    'Prachin Buri',
  ],
  'Prachuap Khiri Khan': [
    'Amphoe Bang Saphan',
    'Amphoe Bang Saphan Noi',
    'Amphoe Hua Hin',
    'Amphoe Kui Buri',
    'Amphoe Mueang Prachuap Khiri Khan',
    'Amphoe Pran Buri',
    'Amphoe Sam Roi Yot',
    'Amphoe Thap Sakae',
    'Bang Saphan',
    'Hua Hin',
    'Kui Buri',
    'Prachuap Khiri Khan',
    'Pran Buri',
    'Sam Roi Yot',
  ],
  Ranong: [
    'Amphoe Kapoe',
    'Amphoe Kra Buri',
    'Amphoe La-un',
    'Amphoe Mueang Ranong',
    'Amphoe Suk Samran',
    'Ranong',
  ],
  Ratchaburi: [
    'Amphoe Ban Kha',
    'Amphoe Ban Pong',
    'Amphoe Bang Phae',
    'Amphoe Chom Bueng',
    'Amphoe Damnoen Saduak',
    'Amphoe Mueang Ratchaburi',
    'Amphoe Pak Tho',
    'Amphoe Photharam',
    'Amphoe Suan Phueng',
    'Amphoe Wat Phleng',
    'Ban Pong',
    'Bang Phae',
    'Chom Bueng',
    'Damnoen Saduak',
    'Photharam',
    'Ratchaburi',
  ],
  Rayong: [
    'Amphoe Ban Chang',
    'Amphoe Ban Khai',
    'Amphoe Khao Chamao',
    'Amphoe Klaeng',
    'Amphoe Mueang Rayong',
    'Amphoe Nikhom Phattana',
    'Amphoe Pluak Daeng',
    'Amphoe Wang Chan',
    'Ban Chang',
    'Ban Phe',
    'Klaeng',
    'Rayong',
  ],
  'Roi Et': [
    'Amphoe At Samat',
    'Amphoe Changhan',
    'Amphoe Chaturaphak Phiman',
    'Amphoe Chiang Khwan',
    'Amphoe Kaset Wisai',
    'Amphoe Moeiwadi',
    'Amphoe Mueang Roi Et',
    'Amphoe Mueang Suang',
    'Amphoe Nong Hi',
    'Amphoe Nong Phok',
    'Amphoe Pathum Rat',
    'Amphoe Phanom Phrai',
    'Amphoe Pho Chai',
    'Amphoe Phon Sai',
    'Amphoe Phon Thong',
    'Amphoe Selaphum',
    'Amphoe Si Somdet',
    'Amphoe Suwannaphum',
    'Amphoe Thawatchaburi',
    'Amphoe Thung Khao Luang',
    'Ban Selaphum',
    'Kaset Wisai',
    'Moeiwadi',
    'Pho Chai',
    'Roi Et',
    'Suwannaphum',
    'Waeng',
  ],
  'Sa Kaeo': [
    'Amphoe Aranyaprathet',
    'Amphoe Khao Chakan',
    'Amphoe Khlong Hat',
    'Amphoe Khok Sung',
    'Amphoe Mueang Sa Kaeo',
    'Amphoe Ta Phraya',
    'Amphoe Wang Nam Yen',
    'Amphoe Wang Sombun',
    'Amphoe Watthana Nakhon',
    'Aranyaprathet',
    'Sa Kaeo',
    'Wang Nam Yen',
  ],
  'Sakon Nakhon': [
    'Amphoe Akat Amnuai',
    'Amphoe Ban Muang',
    'Amphoe Charoen Sin',
    'Amphoe Kham Ta Kla',
    'Amphoe Khok Si Suphan',
    'Amphoe Kusuman',
    'Amphoe Kut Bak',
    'Amphoe Mueang Sakon Nakhon',
    'Amphoe Nikhom Nam Un',
    'Amphoe Phang Khon',
    'Amphoe Phanna Nikhom',
    'Amphoe Phon Na Kaeo',
    'Amphoe Phu Phan',
    'Amphoe Sawang Daen Din',
    'Amphoe Song Dao',
    'Amphoe Tao Ngoi',
    'Amphoe Wanon Niwat',
    'Amphoe Waritchaphum',
    'Sakon Nakhon',
    'Sawang Daen Din',
  ],
  'Samut Prakan': [
    'Amphoe Bang Bo',
    'Amphoe Bang Phli',
    'Amphoe Bang Sao Thong',
    'Amphoe Mueang Samut Prakan',
    'Amphoe Phra Pradaeng',
    'Amphoe Phra Samut Chedi',
    'Ban Khlong Bang Sao Thong',
    'Bang Bo District',
    'Phra Pradaeng',
    'Samut Prakan',
  ],
  'Samut Sakhon': [
    'Amphoe Ban Phaeo',
    'Amphoe Krathum Baen',
    'Amphoe Mueang Samut Sakhon',
    'Ban Phaeo',
    'Krathum Baen',
    'Samut Sakhon',
  ],
  'Samut Songkhram': [
    'Amphoe Amphawa',
    'Amphoe Bang Khonthi',
    'Amphoe Mueang Samut Songkhram',
    'Samut Songkhram',
  ],
  Saraburi: [
    'Amphoe Ban Mo',
    'Amphoe Chaloem Phra Kiat',
    'Amphoe Don Phut',
    'Amphoe Kaeng Khoi',
    'Amphoe Muak Lek',
    'Amphoe Mueang Sara Buri',
    'Amphoe Nong Don',
    'Amphoe Nong Khae',
    'Amphoe Nong Saeng',
    'Amphoe Phra Phutthabat',
    'Amphoe Sao Hai',
    'Amphoe Wang Muang',
    'Amphoe Wihan Daeng',
    'Ban Mo',
    'Kaeng Khoi',
    'Nong Khae',
    'Phra Phutthabat',
    'Saraburi',
  ],
  Satun: [
    'Amphoe Khuan Don',
    'Amphoe Khuan Kalong',
    'Amphoe La-Ngu',
    'Amphoe Manang',
    'Amphoe Mueang Satun',
    'Amphoe Tha Phae',
    'Amphoe Thung Wa',
    'Satun',
  ],
  'Si Sa Ket': [
    'Amphoe Benchalak',
    'Amphoe Bueng Bun',
    'Amphoe Huai Thap Than',
    'Amphoe Kantharalak',
    'Amphoe Kanthararom',
    'Amphoe Khukhan',
    'Amphoe Khun Han',
    'Amphoe Mueang Chan',
    'Amphoe Mueang Sisaket',
    'Amphoe Nam Kliang',
    'Amphoe Non Khun',
    'Amphoe Phayu',
    'Amphoe Pho Si Suwan',
    'Amphoe Phrai Bueng',
    'Amphoe Phu Sing',
    'Amphoe Prang Ku',
    'Amphoe Rasi Salai',
    'Amphoe Si Rattana',
    'Amphoe Sila Lat',
    'Amphoe Uthumphon Phisai',
    'Amphoe Wang Hin',
    'Amphoe Yang Chum Noi',
    'Kantharalak',
    'Phrai Bueng',
    'Si Sa Ket',
  ],
  'Sing Buri': [
    'Amphoe Bang Rachan',
    'Amphoe In Buri',
    'Amphoe Khai Bang Rachan',
    'Amphoe Mueang Sing Buri',
    'Amphoe Phrom Buri',
    'Amphoe Tha Chang',
    'Bang Racham',
    'In Buri',
    'Sing Buri',
  ],
  Songkhla: [
    'Amphoe Bang Klam',
    'Amphoe Chana',
    'Amphoe Hat Yai',
    'Amphoe Khlong Hoi Khong',
    'Amphoe Khuan Niang',
    'Amphoe Krasae Sin',
    'Amphoe Mueang Songkhla',
    'Amphoe Na Mom',
    'Amphoe Na Thawi',
    'Amphoe Ranot',
    'Amphoe Rattaphum',
    'Amphoe Saba Yoi',
    'Amphoe Sadao',
    'Amphoe Sathing Phra',
    'Amphoe Singhanakhon',
    'Amphoe Thepha',
    'Ban Mai',
    'Hat Yai',
    'Na Mom',
    'Ranot',
    'Sadao',
    'Songkhla',
  ],
  Sukhothai: [
    'Amphoe Ban Dan Lan Hoi',
    'Amphoe Khiri Mat',
    'Amphoe Kong Krailat',
    'Amphoe Mueang Sukhothai',
    'Amphoe Sawankhalok',
    'Amphoe Si Nakhon',
    'Amphoe Si Samrong',
    'Amphoe Si Satchanalai',
    'Amphoe Thung Saliam',
    'Ban Dan Lan Hoi',
    'Ban Na',
    'Khiri Mat',
    'Sawankhalok',
    'Si Satchanalai',
    'Sukhothai',
  ],
  'Suphan Buri': [
    'Amphoe Bang Pla Ma',
    'Amphoe Dan Chang',
    'Amphoe Doembang Nangbuat',
    'Amphoe Don Chedi',
    'Amphoe Mueang Suphan Buri',
    'Amphoe Nong Yasai',
    'Amphoe Si Prachan',
    'Amphoe Song Phi Nong',
    'Amphoe U Thong',
    'Ban Sam Chuk',
    'Doembang Nangbuat',
    'Suphan Buri',
  ],
  'Surat Thani': [
    'Amphoe Ban Na Doem',
    'Amphoe Ban Na San',
    'Amphoe Ban Takhun',
    'Amphoe Chai Buri',
    'Amphoe Chaiya',
    'Amphoe Don Sak',
    'Amphoe Kanchanadit',
    'Amphoe Khian Sa',
    'Amphoe Khiri Rat Nikhom',
    'Amphoe Ko Pha-ngan',
    'Amphoe Ko Samui',
    'Amphoe Mueang Surat Thani',
    'Amphoe Phanom',
    'Amphoe Phrasaeng',
    'Amphoe Phunphin',
    'Amphoe Tha Chana',
    'Amphoe Tha Chang',
    'Amphoe Wiang Sa',
    'Amphoe Wiphawadi',
    'Ban Na San',
    'Chai Buri',
    'Chaiya',
    'Don Sak',
    'Kanchanadit',
    'Ko Pha Ngan',
    'Ko Samui',
    'Koh Tao',
    'Surat Thani',
    'Tha Kham',
    'Tha Khanon',
    'Wiang Sa',
  ],
  Surin: [
    'Amphoe Bua Chet',
    'Amphoe Chom Phra',
    'Amphoe Chumphon Buri',
    'Amphoe Kap Choeng',
    'Amphoe Khwao Sinarin',
    'Amphoe Lamduan',
    'Amphoe Mueang Surin',
    'Amphoe Non Narai',
    'Amphoe Phanom Dong Rak',
    'Amphoe Prasat',
    'Amphoe Rattanaburi',
    'Amphoe Samrong Thap',
    'Amphoe Sangkha',
    'Amphoe Sanom',
    'Amphoe Si Khoraphum',
    'Amphoe Si Narong',
    'Amphoe Tha Tum',
    'Surin',
  ],
  Tak: [
    'Amphoe Ban Tak',
    'Amphoe Mae Ramat',
    'Amphoe Mae Sot',
    'Amphoe Mueang Tak',
    'Amphoe Phop Phra',
    'Amphoe Tha Song Yang',
    'Amphoe Umphang',
    'Amphoe Wang Chao',
    'Ban Tak',
    'Mae Ramat',
    'Mae Sot',
    'Tak',
  ],
  Trang: [
    'Amphoe Hat Samran',
    'Amphoe Huai Yot',
    'Amphoe Kantang',
    'Amphoe Mueang Trang',
    'Amphoe Na Yong',
    'Amphoe Palian',
    'Amphoe Ratsada',
    'Amphoe Sikao',
    'Amphoe Wang Wiset',
    'Amphoe Yan Ta Khao',
    'Huai Yot',
    'Kantang',
    'Trang',
  ],
  Trat: [
    'Amphoe Bo Rai',
    'Amphoe Khao Saming',
    'Amphoe Khlong Yai',
    'Amphoe Ko Chang',
    'Amphoe Ko Kut',
    'Amphoe Laem Ngop',
    'Amphoe Mueang Trat',
    'Bo Rai',
    'Khlong Yai',
    'Ko Chang Tai',
    'Trat',
  ],
  'Ubon Ratchathani': [
    'Amphoe Buntharik',
    'Amphoe Det Udom',
    'Amphoe Don Mot Daeng',
    'Amphoe Khemmarat',
    'Amphoe Khong Chiam',
    'Amphoe Khueang Nai',
    'Amphoe Kut Khaopun',
    'Amphoe Lao Suea Kok',
    'Amphoe Muang Sam Sip',
    'Amphoe Mueang Ubon Ratchathani',
    'Amphoe Na Chaluai',
    'Amphoe Na Tan',
    'Amphoe Na Yia',
    'Amphoe Nam Khun',
    'Amphoe Nam Yuen',
    'Amphoe Phibun Mangsahan',
    'Amphoe Pho Sai',
    'Amphoe Samrong',
    'Amphoe Sawang Wirawong',
    'Amphoe Si Mueang Mai',
    'Amphoe Sirindhorn',
    'Amphoe Tan Sum',
    'Amphoe Thung Si Udom',
    'Amphoe Trakan Phuet Phon',
    'Amphoe Warin Chamrap',
    'Det Udom',
    'Phibun Mangsahan',
    'Sawang Wirawong',
    'Ubon Ratchathani',
    'Warin Chamrap',
  ],
  'Udon Thani': [
    'Amphoe Ban Dung',
    'Amphoe Ban Phue',
    'Amphoe Chai Wan',
    'Amphoe Ku Kaeo',
    'Amphoe Kumphawapi',
    'Amphoe Kut Chap',
    'Amphoe Mueang Udon Thani',
    'Amphoe Na Yung',
    'Amphoe Nam Som',
    'Amphoe Non Sa-at',
    'Amphoe Nong Han',
    'Amphoe Nong Saeng',
    'Amphoe Nong Wua So',
    'Amphoe Phen',
    'Amphoe Phibun Rak',
    'Amphoe Prachak Sinlapakhom',
    'Amphoe Sang Khom',
    'Amphoe Si That',
    'Amphoe Thung Fon',
    'Amphoe Wang Sam Mo',
    'Ban Dung',
    'Ban Nong Wua So',
    'Ban Phan Don',
    'Kumphawapi',
    'Kut Chap',
    'Nam Som',
    'Nong Wua So',
    'Udon Thani',
  ],
  'Uthai Thani': [
    'Amphoe Ban Rai',
    'Amphoe Huai Khot',
    'Amphoe Lan Sak',
    'Amphoe Mueang Uthai Thani',
    'Amphoe Nong Chang',
    'Amphoe Nong Khayang',
    'Amphoe Sawang Arom',
    'Amphoe Thap Than',
    'Huai Khot',
    'Lan Sak',
    'Thap Than',
    'Uthai Thani',
  ],
  Uttaradit: [
    'Amphoe Ban Khok',
    'Amphoe Fak Tha',
    'Amphoe Lap Lae',
    'Amphoe Mueang Uttaradit',
    'Amphoe Nam Pat',
    'Amphoe Phichai',
    'Amphoe Tha Pla',
    'Amphoe Thong Saen Khan',
    'Amphoe Tron',
    'Uttaradit',
  ],
  Yala: [
    'Amphoe Bannang Sata',
    'Amphoe Betong',
    'Amphoe Kabang',
    'Amphoe Krong Pinang',
    'Amphoe Mueang Yala',
    'Amphoe Raman',
    'Amphoe Than To',
    'Amphoe Yaha',
    'Betong',
    'Yala',
  ],
  Yasothon: [
    'Amphoe Kham Khuan Kaeo',
    'Amphoe Kho Wang',
    'Amphoe Kut Chum',
    'Amphoe Loeng Nok Tha',
    'Amphoe Maha Chana Chai',
    'Amphoe Mueang Yasothon',
    'Amphoe Pa Tio',
    'Amphoe Sai Mun',
    'Amphoe Thai Charoen',
    'Yasothon',
  ],
};
