export const TAJIKISTAN_PROVINCES_CITIES = {
  'districts of Republican Subordination': [
    'Darband',
    'Hisor',
    'Karakenja',
    'Khodzha-Maston',
    'Novobod',
    'Obigarm',
    'Rasht',
    'Roghun',
    'Shahrinav',
    'Tagob',
    'Tursunzoda',
    'Vahdat',
    'Vahdat District',
    'Varzob',
    'Varzob District',
  ],
  'Gorno-Badakhshan Autonomous Province': [
    'Ishqoshim',
    'Khorugh',
    'Murghob',
    'Nohiyai Shughnon',
  ],
  'Khatlon Province': [
    'Abdurahmoni Jomí',
    'Boshchorbogh',
    'Bŭstonqal’a',
    'Chubek',
    'Danghara',
    'Dŭstí',
    'Farkhor',
    'Gharavŭtí',
    'Jilikŭl',
    'Kirov',
    'Kolkhozobod',
    'Kŭlob',
    'Moskovskiy',
    'Mŭ’minobod',
    'Nohiyai Kolkhozobod',
    'Nohiyai Panj',
    'Nohiyai Vakhsh',
    'Norak',
    'Orzu',
    'Panj',
    'Qŭrghonteppa',
    'Shahritus',
    'Sovet',
    'Tartiki',
    'Vakhsh',
    'Vose’',
    'Yovon',
  ],
  'Sughd Province': [
    'Adrasmon',
    'Ayní',
    'Bŭston',
    'Chkalov',
    'Ghafurov',
    'Isfara',
    'Istaravshan',
    'Khŭjand',
    'Kim',
    'Konibodom',
    'Konsoy',
    'Neftobod',
    'Nohiyai Konibodom',
    'Nov',
    'Oltintopkan',
    'Pakhtakoron',
    'Palos',
    'Panjakent',
    'Proletar',
    'Quruqsoy',
    'Shaydon',
    'Shŭrob',
    'Taboshar',
    'Vorukh',
  ],
};
