export const EAST_TIMOR_DISTRICS_TOWNS = {
  'Aileu municipality': ['Aileu', 'Lequidoe', 'Remexio'],
  'Ainaro Municipality': ['Ainaro', 'Hato-Udo'],
  'Baucau Municipality': [
    'Baguia',
    'Baucau',
    'Baukau',
    'Laga',
    'Quelicai',
    'Vemasse',
    'Venilale',
  ],
  'Bobonaro Municipality': ['Maliana'],
  'Cova Lima Municipality': [
    'Fatumean',
    'Fohorem',
    'Maucatar',
    'Suai',
    'Tilomar',
  ],
  'Dili municipality': ['Atauro Island', 'Cristo Rei', 'Dili', 'Metinaro'],
  'Ermera District': [
    'Ermera Villa',
    'Gleno',
    'Hatulia',
    'Letefoho',
    'Railaco',
  ],
  'Lautém Municipality': ['Iliomar', 'Lautem', 'Lospalos', 'Luro', 'Tutuala'],
  'Liquiçá Municipality': ['Bazartete', 'Likisá', 'Maubara'],
  'Manatuto District': [
    'Barique',
    'Laclo',
    'Laclubar',
    'Manatuto',
    'Manatutu',
    'Soibada',
  ],
  'Manufahi Municipality': ['Alas', 'Fatuberliu', 'Same', 'Turiscai'],
  'Viqueque Municipality': [
    'Lacluta',
    'Ossu',
    'Uatocarabau',
    'Uatolari',
    'Viqueque',
  ],
};
