export const TUNISIA_GOVERNORATES_CITIES = {
  Ariana: [
    'Ariana',
    'Ettadhamen-Mnihla',
    'Kalaat el-Andalous',
    'La Soukra',
    'Mnihla',
    'Raoued',
    'Sidi Thabet',
  ],
  Béja: [
    'Amdoun',
    'Béja',
    'Goubellat',
    'Medjez el Bab',
    'Nefza',
    'Tabursuq',
    'Téboursouk',
    'Testour',
    'Thibar',
  ],
  'Ben Arous': ['Ben Arous', 'Hammam Lif', 'Mornag', 'Mornaguia', 'Radès'],
  Bizerte: [
    'Al Matlīn',
    'Bizerte',
    'Bizerte Sud',
    'Douar Tindja',
    'El Alia',
    'Mateur',
    'Menzel Abderhaman',
    'Menzel Bourguiba',
    'Menzel Jemil',
    'Rafrāf',
    'Rhar el Melah',
    'Sejenane',
    'Zahānah',
  ],
  Gabès: ['Bou Attouche', 'El Hamma', 'Gabès', 'Matmata'],
  Gafsa: [
    'Ar Rudayyif',
    'As Sanad',
    'Gafsa',
    'Metlaoui',
    'Mu‘tamadīyat ar Rudayyif',
  ],
  Jendouba: ['Fernana', 'Jendouba', 'Oued Meliz', 'Tabarka'],
  Kairouan: ['Haffouz', 'Kairouan', 'Sbikha'],
  Kasserine: ['Kasserine', 'Rohia', 'Sbiba', 'Thala'],
  Kebili: ['Douz', 'El Golaa', 'Jemna', 'Kebili'],
  Kef: [
    'As Sars',
    'El Kef',
    'El Ksour',
    'Menzel Salem',
    'Nibbar',
    'Sakiet Sidi Youssef',
    'Tajerouine',
  ],
  Mahdia: [
    'Chebba',
    'Chorbane',
    'El Jem',
    'Ksour Essaf',
    'Mahdia',
    'Melloulèche',
    'Salakta',
    'Sidi Alouane',
    'Zouila',
  ],
  Manouba: ['El Battan', 'Manouba', 'Mu‘tamadīyat Manūbah', 'Oued Lill'],
  Medenine: [
    'Ben Gardane',
    'Beni Kheddache',
    'Erriadh',
    'Houmt El Souk',
    'Jerba Midoun',
    'Medenine',
    'Midoun',
    'Zarzis',
  ],
  Monastir: [
    'Banbalah',
    'Bekalta',
    'Beni Hassane',
    'Djemmal',
    'Ksar Hellal',
    'Ksibet el Mediouni',
    'Lemta',
    'Menzel Kamel',
    'Mesdour',
    'Monastir',
    'Ouardenine',
    'Sahline',
    'Seïada',
    'Sidi Ben Nour',
    'Skanes',
    'Touza',
  ],
  Nabeul: [
    'Azmour',
    'Beni Khalled',
    'Béni Khiar',
    'Bou Argoub',
    'Dar Chaabane',
    'El Haouaria',
    'El Maâmoura',
    'El Mida',
    'El Mrezga',
    'Grombalia',
    'Hammamet',
    'Kelibia',
    'Korba',
    'Korbous',
    'Menzel Bouzelfa',
    'Menzel Horr',
    'Menzel Temime',
    'Nabeul',
    'Soliman',
    'Takelsa',
    'Tazerka',
    'Zaouiet Djedidi',
    'Zriba',
  ],
  Sfax: [
    'Agareb',
    'Bir Ali Ben Khalifa',
    'Djebeniana',
    'Gremda',
    'Sfax',
    'Skhira',
  ],
  'Sidi Bouzid': [
    'Bir el Hafey',
    'Er Regueb',
    'Jilma',
    'Mezzouna',
    'Sidi Bouzid',
  ],
  Siliana: ['Bou Arada', 'Gafour', 'Kesra', 'Le Krib', 'Maktar', 'Siliana'],
  Sousse: [
    'Akouda',
    'Hammam Sousse',
    'Harqalah',
    'Msaken',
    'Port el Kantaoui',
    'Sidi Bou Ali',
    'Sidi el Hani',
    'Sousse',
  ],
  Tataouine: ['Remada', 'Tataouine'],
  Tozeur: ['Chebika', 'Degache', 'Nefta', 'Tamaghzah', 'Tozeur'],
  Tunis: [
    'Al Marsá',
    'Carthage',
    'La Goulette',
    'La Mohammedia',
    'Sidi Bou Saïd',
    'Tunis',
  ],
  Zaghouan: ['El Fahs', 'Zaghouan'],
};
