export const TRINIDAD_TOBAGO_REGIONS_CITIES = {
  Arima: ['Arima'],
  Chaguanas: ['Chaguanas', 'Ward of Chaguanas'],
  'Couva-Tabaquite-Talparo Regional Corporation': ['Couva', 'Tabaquite'],
  'Diego Martin Regional Corporation': ['Petit Valley', 'Ward of Diego Martin'],
  'Eastern Tobago': ['Scarborough'],
  'Penal-Debe Regional Corporation': ['Debe', 'Peñal'],
  'Point Fortin': ['Point Fortin'],
  'Port of Spain': ['Mucurapo', 'Port of Spain'],
  'Princes Town Regional Corporation': ['Princes Town'],
  'San Fernando': ['Marabella', 'Mon Repos', 'San Fernando'],
  'San Juan-Laventille Regional Corporation': ['Laventille'],
  'Sangre Grande Regional Corporation': ['Sangre Grande'],
  'Siparia Regional Corporation': ['Siparia', 'Ward of Siparia'],
  'Tunapuna-Piarco Regional Corporation': ['Arouca', 'Paradise', 'Tunapuna'],
  'Western Tobago': ['Rio Claro'],
};
