export const TAIWAN_COUNTIES_CITIES = {
  Changhua: ['Changhua', 'Yuanlin'],
  Chiayi: ['Chiayi County'],
  Hsinchu: ['Hsinchu County'],
  Hualien: ['Hualien', 'Hualien City'],
  Kaohsiung: ['Kaohsiung'],
  Kinmen: ['Jincheng', 'Kinmen County'],
  Lienchiang: ['Lienchiang', 'Nangan'],
  Miaoli: ['Miaoli'],
  Nantou: ['Lugu', 'Nantou', 'Puli', 'Zhongxing New Village'],
  Penghu: ['Magong', 'Penghu County'],
  Pingtung: ['Donggang', 'Hengchun', 'Pingtung'],
  Taichung: ['Taichung', 'Taichung City'],
  Tainan: ['Tainan', 'Yujing'],
  Taipei: ['Banqiao', 'Jiufen', 'Taipei', 'Taipei City'],
  Taitung: ['Taitung', 'Taitung City'],
  Taoyuan: ['Daxi', 'Taoyuan', 'Taoyuan City'],
  Yilan: ['Yilan'],
  Yunlin: ['Douliu', 'Yunlin'],
};
