export const TANZANIA_REGIONS_CITIES = {
  Arusha: [
    'Arusha',
    'Kingori',
    'Kiratu',
    'Longido',
    'Mbuguni',
    'Merelani',
    'Meru',
    'Monduli',
    'Mto wa Mbu',
    'Namanga',
    'Ngorongoro',
    'Nkoaranga',
    'Poli',
    'Usa River',
  ],
  'Dar es Salaam': ['Dar es Salaam', 'Magomeni'],
  Dodoma: [
    'Dodoma',
    'Kibakwe',
    'Kisasa',
    'Kondoa',
    'Kongwa',
    'Mpwapwa',
    'Msanga',
  ],
  Geita: [
    'Buseresere',
    'Chato',
    'Geita',
    'Kasamwa',
    'Katoro',
    'Masumbwe',
    'Ushirombo',
    'Uyovu',
  ],
  Iringa: ['Ilula', 'Iringa', 'Izazi', 'Mafinga', 'Makungu', 'Malangali'],
  Kagera: [
    'Biharamulo',
    'Bugarama',
    'Bugene',
    'Bukoba',
    'Kabanga',
    'Kamachumu',
    'Katerero',
    'Katoro',
    'Kyaka',
    'Ngara',
    'Nshamba',
    'Nsunga',
    'Nyakahanga',
    'Rulenge',
  ],
  Katavi: ['Inyonga', 'Karema', 'Mpanda', 'Usevia'],
  Kigoma: [
    'Kakonko',
    'Kasulu',
    'Kibondo',
    'Kigoma',
    'Mabamba',
    'Mwandiga',
    'Nguruka',
    'Uvinza',
  ],
  Kilimanjaro: ['Hedaru', 'Machame', 'Marangu', 'Moshi', 'Same'],
  Lindi: [
    'Lindi',
    'Mbekenyera',
    'Mingoyo',
    'Mtama',
    'Nachingwea',
    'Nyangao',
    'Ruangwa',
  ],
  Manyara: [
    'Babati',
    'Bashanet',
    'Basotu',
    'Dareda',
    'Dongobesh',
    'Endasak',
    'Galappo',
    'Katesh',
    'Kibaya',
    'Kirya',
    'Magugu',
    'Mbulu',
    'Naberera',
    'Nangwa',
  ],
  Mara: [
    'Bukonyo',
    'Butiama',
    'Issenye',
    'Kibara',
    'Mugango',
    'Mugumu',
    'Muriti',
    'Musoma',
    'Nakatunguru',
    'Nansio',
    'Nyamuswa',
    'Sirari',
  ],
  Mbeya: [
    'Chimala',
    'Hedaru',
    'Ibaba',
    'Ikama',
    'Ikinga',
    'Ikolo',
    'Ikuti',
    'Ilembo',
    'Ipinda',
    'Kabula',
    'Kahe Tanzania',
    'Kandete',
    'Katumba',
    'Kihurio',
    'Kisiwani',
    'Kiwira',
    'Kwakoa',
    'Lembeni',
    'Lupata',
    'Lusungo',
    'Machame',
    'Makanya',
    'Marangu',
    'Masukulu',
    'Mbeya',
    'Mlowo',
    'Moshi',
    'Mpuguso',
    'Mwansanga',
    'Mwaya',
    'Mwembe',
    'Same',
    'Tukuyu',
    'Tunduma',
    'Ugweno',
    'Ulanga',
  ],
  Morogoro: [
    'Geiro',
    'Ifakara',
    'Kidatu',
    'Kidodi',
    'Kilosa',
    'Kimamba',
    'Kisanga',
    'Lupiro',
    'Magole',
    'Mahenge',
    'Malinyi',
    'Mikumi',
    'Mlimba',
    'Morogoro',
    'Msowero',
    'Mtimbira',
    'Mvomero District',
    'Ngerengere',
  ],
  Mtwara: [
    'Chiungutwa',
    'Kitama',
    'Kitangari',
    'Luchingu',
    'Lukuledi',
    'Lulindi',
    'Madimba',
    'Mahuta',
    'Masasi',
    'Masuguru',
    'Mtwara',
    'Namalenga',
    'Namikupa',
    'Nanganga',
    'Nangomba',
    'Nanhyanga',
    'Nanyamba',
    'Newala Kisimani',
    'Tandahimba',
  ],
  Mwanza: [
    'Ilemela District',
    'Kihangara',
    'Malya',
    'Misasi',
    'Misungwi',
    'Mwanza',
    'Ngudu',
    'Nyanguge',
    'Usagara',
  ],
  Njombe: [
    'Ilembula',
    'Makumbako',
    'Manda',
    'Matamba',
    'Mlangali',
    'Mtwango',
    'Njombe',
  ],
  'Pemba North': ['Konde', 'Micheweni', 'Wete'],
  'Pemba South': ['Chake Chake', 'Mtambile', 'Uwelini'],
  Pwani: [
    'Bagamoyo',
    'Bungu',
    'Chalinze',
    'Ikwiriri',
    'Kibaha',
    'Kibiti',
    'Kilindoni',
    'Kisarawe',
    'Lugoba',
    'Maneromango',
    'Mbumi',
    'Mkuranga',
    'Mlandizi',
    'Mvomero',
    'Utete',
    'Vikindu',
  ],
  Rukwa: [
    'Chala',
    'Kirando',
    'Laela',
    'Matai',
    'Namanyere',
    'Nkove',
    'Sumbawanga',
  ],
  Ruvuma: [
    'Kigonsera',
    'Liuli',
    'Mahanje',
    'Maposeni',
    'Matiri',
    'Mbamba Bay',
    'Mbinga',
    'Songea',
    'Tingi',
  ],
  Shinyanga: [
    'Isaka',
    'Kahama',
    'Kishapu',
    'Mhango',
    'Mwadui',
    'Old Shinyanga',
    'Shinyanga',
    'Songwa',
    'Tinde',
  ],
  Simiyu: [
    'Bariadi',
    'Kisesa',
    'Lalago',
    'Malampaka',
    'Maswa',
    'Matonga',
    'Nyakabindi',
    'Nyalikungu',
    'Somanda',
  ],
  Singida: [
    'Igugunu',
    'Ikungi',
    'Ilongero',
    'Itigi',
    'Kilimatinde',
    'Kintinku',
    'Kiomboi',
    'Mgandu',
    'Mtinko',
    'Mungaa',
    'Ndago',
    'Puma',
    'Sepuka',
    'Shelui',
    'Singida',
  ],
  Tabora: [
    'Bukene',
    'Igurubi',
    'Kaliua',
    'Mabama',
    'Sikonge',
    'Tabora',
    'Tumbi',
    'Usoke',
  ],
  Tanga: [
    'Chanika',
    'Lushoto',
    'Magomeni',
    'Majengo',
    'Makuyuni',
    'Maramba',
    'Matui',
    'Mazinde',
    'Mlalo',
    'Muheza',
    'Mwanga',
    'Pangani',
    'Soni',
    'Tanga',
  ],
  'Zanzibar North': ['Gamba', 'Kijini', 'Kiwengwa', 'Mkokotoni', 'Nungwi'],
  'Zanzibar South': ['Koani', 'Koani Ndogo', 'Mahonda', 'Nganane', 'Sokoni'],
  'Zanzibar West': ['Zanzibar'],
};
