export const UGANDA_REGIONS_CITIES = {
  'Central Region': [
    'Bukomansimbi District',
    'Buvuma District',
    'Bweyogerere',
    'Byakabanda',
    'Entebbe',
    'Gomba District',
    'Kajansi',
    'Kampala',
    'Kampala District',
    'Kanoni',
    'Kayunga',
    'Kiboga',
    'Kireka',
    'Kyotera',
    'Lugazi',
    'Luwero',
    'Lyantonde',
    'Masaka',
    'Mityana',
    'Mpigi',
    'Mubende',
    'Mubende District',
    'Mukono',
    'Nakasongola',
    'Namasuba',
    'Njeru',
    'Sembabule',
    'Wakiso',
    'Wakiso District',
    'Wobulenzi',
  ],
  'Eastern Region': [
    'Bugembe',
    'Bugiri',
    'Bukwa District',
    'Bulambuli District',
    'Busembatia',
    'Busia',
    'Buwenge',
    'Iganga',
    'Jinja',
    'Kamuli',
    'Kapchorwa',
    'Kibuku District',
    'Kumi',
    'Mayuge',
    'Mbale',
    'Pallisa',
    'Sironko',
    'Soroti',
    'Tororo',
  ],
  'Northern Region': [
    'Adjumani',
    'Amudat',
    'Apac',
    'Arua',
    'Gulu',
    'Kitgum',
    'Kotido',
    'Lira',
    'Moroto',
    'Moyo',
    'Nebbi',
    'Otuke District',
    'Oyam District',
    'Pader',
    'Pader Palwo',
    'Paidha',
    'Yumbe',
  ],
  'Western Region': [
    'Bundibugyo',
    'Bwizibwera',
    'Fort Portal',
    'Hoima',
    'Ibanda',
    'Ibanda District',
    'Kabale',
    'Kagadi',
    'Kamwenge',
    'Kanungu',
    'Kasese',
    'Kibale',
    'Kigorobya',
    'Kilembe',
    'Kiruhura',
    'Kisoro',
    'Kyenjojo',
    'Margherita',
    'Masindi',
    'Masindi Port',
    'Mbarara',
    'Muhororo',
    'Ntungamo',
    'Nyachera',
    'Rukungiri',
  ],
};
