export const UZBEKISTAN_PROVINCES_CITIES = {
  'Andijan Region': [
    'Andijon',
    'Andijon Tumani',
    'Asaka',
    'Asaka Tumani',
    'Baliqchi Tumani',
    'Bo‘z Tumani',
    'Buloqboshi Tumani',
    'Izboskan Tumani',
    'Jalolkuduk Tumani',
    'Khŭjaobod Tumani',
    'Marhamat',
    'Marhamat Tumani',
    'Oltinkŭl Tumani',
    'Pakhtaobod Tumani',
    'Paxtaobod',
    'Qo‘rg‘ontepa',
    'Qŭrghontepa Tumani',
    'Shahrikhon Tumani',
    'Shahrixon',
    'Ulug‘nor Tumani',
    'Xo‘jaobod',
  ],
  'Bukhara Region': [
    'Bukhara',
    'Galaosiyo',
    'Gazli',
    'Ghijduwon',
    'Karakul’',
    'Kogon',
    'Olot',
    'Peshku Tumani',
    'Qorako’l',
    'Qorovulbozor',
    'Romiton',
    'Shofirkon',
    'Wobkent',
    'Wobkent Tumani',
  ],
  'Fergana Region': [
    'Beshariq',
    'Fergana',
    'Hamza',
    'Kirguli',
    'Marg‘ilon',
    'Oltiariq',
    'Qo‘qon',
    'Quva',
    'Quvasoy',
    'Rishton',
    'Shohimardon',
    'So‘x Tumani',
    'Toshloq',
    'Yangi Marg‘ilon',
    'Yaypan',
  ],
  'Jizzakh Region': [
    'Dashtobod',
    'Dŭstlik',
    'Gagarin',
    'Jizzax',
    'Paxtakor',
    'Zomin',
  ],
  Karakalpakstan: [
    'Beruniy',
    'Kegeyli Shahar',
    'Khŭjayli',
    'Manghit',
    'Mŭynoq',
    'Novyy Turtkul’',
    'Nukus',
    'Oltinko‘l',
  ],
  'Namangan Region': [
    'Chortoq',
    'Chust',
    'Haqqulobod',
    'Kosonsoy',
    'Namangan',
    'Pop',
    'To‘rqao‘rg‘on',
    'Toshbuloq',
    'Uchqŭrghon Shahri',
    'Uychi',
    'Yangiqo‘rg‘on',
  ],
  'Navoiy Region': ['Navoiy', 'Nurota', 'Qiziltepa', 'Yangirabot'],
  'Qashqadaryo Region': [
    'Beshkent',
    'Chiroqchi',
    'G‘uzor',
    'Kitob',
    'Koson',
    'Muborak',
    'Nishon Tumani',
    'Qarshi',
    'Shahrisabz',
  ],
  'Samarqand Region': [
    'Bulung’ur',
    'Charxin',
    'Chelak',
    'Daxbet',
    'Ishtixon',
    'Jomboy',
    'Juma',
    'Kattaqo‘rg‘on',
    'Oqtosh',
    'Payshanba',
    'Samarkand',
    'Urgut',
  ],
  'Sirdaryo Region': ['Guliston', 'Sirdaryo', 'Yangiyer'],
  'Surxondaryo Region': ['Boysun', 'Denov', 'Sho‘rchi', 'Tirmiz'],
  Tashkent: ['Bektemir', 'Tashkent'],
  'Tashkent Region': [
    'Angren',
    'Bekobod',
    'Bo‘ka',
    'Chinoz',
    'Chirchiq',
    'G‘azalkent',
    'Iskandar',
    'Kyzyldzhar',
    'Ohangaron',
    'Olmaliq',
    'Parkent',
    'Piskent',
    'Qibray',
    'Salor',
    'Tŭytepa',
    'Ŭrtaowul',
    'Yangiobod',
    'Yangiyŭl',
    'Zafar',
  ],
  'Xorazm Region': [
    'Boghot Tumani',
    'Gurlan',
    'Hazorasp',
    'Khiwa',
    'Qŭshkŭpir',
    'Showot',
    'Urganch',
  ],
};
