export const VENEZUELA_STATES_CITIES = {
  Amazonas: [
    'Maroa',
    'Municipio Autónomo Alto Orinoco',
    'Puerto Ayacucho',
    'San Carlos de Río Negro',
    'San Fernando de Atabapo',
    'San Juan de Manapiare',
  ],
  Anzoátegui: [
    'Anaco',
    'Aragua de Barcelona',
    'Barcelona',
    'Cantaura',
    'El Tigre',
    'Municipio José Gregorio Monagas',
    'Onoto',
    'Puerto La Cruz',
    'Puerto Píritu',
    'San José de Guanipa',
  ],
  Apure: ['San Fernando de Apure'],
  Aragua: [
    'Cagua',
    'El Limón',
    'La Victoria',
    'Las Tejerías',
    'Maracay',
    'Palo Negro',
    'San Mateo',
    'Santa Rita',
    'Turmero',
    'Villa de Cura',
  ],
  Barinas: ['Alto Barinas', 'Barinas', 'Barinitas', 'Municipio Barinas'],
  Bolívar: [
    'Ciudad Bolívar',
    'Ciudad Guayana',
    'Municipio Padre Pedro Chien',
    'Santa Elena de Uairén',
    'Upata',
  ],
  Carabobo: [
    'Guacara',
    'Güigüe',
    'Los Guayos',
    'Mariara',
    'Morón',
    'Puerto Cabello',
    'San Joaquín',
    'Tacarigua',
    'Tocuyito',
    'Valencia',
  ],
  Cojedes: ['San Carlos', 'Tinaquillo'],
  'Delta Amacuro': ['Tucupita'],
  'Distrito Capital': ['Caracas'],
  Falcón: [
    'Chichiriviche',
    'Coro',
    'Municipio Los Taques',
    'Municipio Miranda',
    'Punta Cardón',
    'Punto Fijo',
    'Tucacas',
  ],
  Guárico: [
    'Altagracia de Orituco',
    'Calabozo',
    'San Juan de los Morros',
    'Valle de La Pascua',
    'Zaraza',
  ],
  'La Guaira': ['Caraballeda', 'Catia La Mar', 'La Guaira', 'Maiquetía'],
  Lara: [
    'Barquisimeto',
    'Cabudare',
    'Carora',
    'El Tocuyo',
    'Los Rastrojos',
    'Quíbor',
  ],
  Mérida: ['Ejido', 'El Vigía', 'Mérida', 'Mucumpiz', 'Municipio Libertador'],
  Miranda: [
    'Baruta',
    'Carrizal',
    'Caucaguita',
    'Caucagüito',
    'Chacao',
    'Charallave',
    'Cúa',
    'El Cafetal',
    'El Hatillo',
    'Guarenas',
    'Guatire',
    'La Dolorita',
    'Los Dos Caminos',
    'Los Teques',
    'Ocumare del Tuy',
    'Petare',
    'San Antonio de Los Altos',
    'Santa Teresa del Tuy',
  ],
  Monagas: ['Caripito', 'Maturín', 'Municipio Maturín', 'Municipio Uracoa'],
  'Nueva Esparta': ['Juan Griego', 'La Asunción', 'Porlamar'],
  Portuguesa: ['Acarigua', 'Araure', 'Guanare', 'Villa Bruzual'],
  Sucre: ['Carúpano', 'Cumaná', 'Güiria', 'Municipio Valdez'],
  Táchira: [
    'Colón',
    'La Fría',
    'La Grita',
    'Municipio José María Vargas',
    'Rubio',
    'San Antonio del Táchira',
    'San Cristóbal',
    'Táriba',
  ],
  Trujillo: [
    'Boconó',
    'Municipio Pampanito',
    'Municipio San Rafael de Carvajal',
    'Trujillo',
    'Valera',
  ],
  Yaracuy: [
    'Chivacoa',
    'Municipio Independencia',
    'Nirgua',
    'San Felipe',
    'Yaritagua',
  ],
  Zulia: [
    'Cabimas',
    'Ciudad Ojeda',
    'La Villa del Rosario',
    'Lagunillas',
    'Machiques',
    'Maracaibo',
    'San Carlos del Zulia',
    'Santa Rita',
  ],
};
