export const VIETNAM_PROVINCES_CITIES = {
  'An Giang': [
    'Cho Dok',
    'Huyện An Phú',
    'Huyện Châu Phú',
    'Huyện Chợ Mới',
    'Huyện Phú Tân',
    'Huyện Tri Tôn',
    'Long Xuyên',
    'Long Xuyên City',
  ],
  'Bà Rịa-Vũng Tàu': [
    'Côn Sơn',
    'Huyện Châu Đức',
    'Huyện Đất Đỏ',
    'Huyện Tân Thành',
    'Huyện Xuyên Mộc',
    'Thành Phố Vũng Tàu',
    'Thị Xã Phú Mỹ',
    'Vũng Tàu',
  ],
  'Bắc Giang': [
    'Bắc Giang',
    'Huyện Lục Nam',
    'Huyện Lục Ngạn',
    'Huyện Yên Thế',
  ],
  'Bắc Kạn': [
    'Bắc Kạn',
    'Huyện Ba Bể',
    'Huyện Bạch Thông',
    'Huyện Chợ Đồn',
    'Huyện Na Rì',
    'Huyện Ngân Sơn',
    'Thị Xã Bắc Kạn',
  ],
  'Bạc Liêu': ['Bạc Liêu', 'Huyện Giá Rai', 'Huyện Hồng Dân'],
  'Bắc Ninh': [
    'Bắc Ninh',
    'Cung Kiệm',
    'Huyện Gia Bình',
    'Huyện Thuận Thành',
    'Huyện Tiên Du',
    'Huyện Yên Phong',
  ],
  'Bến Tre': [
    'Ấp Tân Ngãi',
    'Bến Tre',
    'Huyện Ba Tri',
    'Huyện Bình Đại',
    'Huyện Châu Thành',
    'Huyện Chợ Lách',
    'Huyện Giồng Trôm',
    'Huyện Thạnh Phú',
  ],
  'Bình Dương': ['Dĩ An', 'Thủ Dầu Một'],
  'Bình Định': [
    'Huyện An Lão',
    'Huyện Hoài Nhơn',
    'Huyện Phù Mỹ',
    'Huyện Tây Sơn',
    'Huyện Tuy Phước',
    'Huyện Vĩnh Thạnh',
    'Qui Nhon',
  ],
  'Bình Phước': [
    'Bình Long',
    'Don Luan',
    'Huyện Bù Đốp',
    'Huyện Chơn Thành',
    'Huyện Đồng Phú',
    'Huyện Hớn Quản',
    'Thị Xã Phước Long',
  ],
  'Bình Thuận': [
    'Huyện Bắc Bình',
    'Huyện Hàm Tân',
    'Huyện Hàm Thuận Bắc',
    'Huyện Hàm Thuận Nam',
    'Huyện Tánh Linh',
    'Huyện Tuy Phong',
    'La Gi',
    'Phan Thiết',
    'Thành Phố Phan Thiết',
  ],
  'Cà Mau': [
    'Cà Mau',
    'Huyện Cái Nước',
    'Huyện Đầm Dơi',
    'Huyen Nam Can',
    'Huyện Thới Bình',
  ],
  'Cần Thơ': ['Cần Thơ', 'Cờ Đỏ', 'Thới Lai', 'Vĩnh Thạnh'],
  'Cao Bằng': [
    'Cao Bằng',
    'Huyện Bảo Lac',
    'Huyện Bảo Lâm',
    'Huyện Hạ Lang',
    'Huyện Hà Quảng',
    'Huyện Nguyên Bình',
    'Huyen Phuc Hoa',
    'Huyện Thạch An',
    'Huyện Thông Nông',
    'Huyện Trà Lĩnh',
    'Huyện Trùng Khánh',
  ],
  'Đà Nẵng': ['Da Nang'],
  'Đắk Lắk': [
    'Buôn Ma Thuột',
    'Huyện Buôn Đôn',
    "Huyện Ea H'Leo",
    'Huyện Ea Súp',
  ],
  'Đắk Nông': ['Huyện Cư Jút', 'Huyện Đắk R’Lấp', 'Huyện Krông Nô'],
  'Điện Biên': [
    'Dien Bien Phu',
    'Huyện Điện Biên Đông',
    'Huyện Mường Nhé',
    'Huyện Tủa Chùa',
    'Huyện Tuần Giáo',
    'Thị Xã Mưòng Lay',
  ],
  'Đồng Nai': [
    'Biên Hòa',
    'Huyện Định Quán',
    'Huyện Long Thành',
    'Huyện Tân Phú',
    'Huyện Thống Nhất',
    'Huyện Trảng Bom',
    'Huyện Vĩnh Cửu',
  ],
  'Đồng Tháp': [
    'Cao Lãnh',
    'Huyện Châu Thành',
    'Huyện Lai Vung',
    'Huyện Lấp Vò',
    'Huyện Tam Nông',
    'Huyện Tân Hồng',
    'Huyện Thanh Bình',
    'Huyện Tháp Mười',
    'Sa Dec',
    'Sa Dec city',
    'Thị Trấn Tân Thành',
  ],
  'Gia Lai': [
    'Huyện Chư Păh',
    'Huyện Chư Prông',
    'Huyện Chư Sê',
    'Huyện Đức Cơ',
    'Huyện Ia Grai',
    'Huyện KBang',
    'Huyện Kông Chro',
    'Huyện Krông Pa',
    'Huyện Mang Yang',
    'Pleiku',
  ],
  'Hà Giang': [
    'Hà Giang',
    'Huyện Bắc Mê',
    'Huyện Bắc Quang',
    'Huyện Đồng Văn',
    'Huyện Quang Bình',
    'Huyện Vị Xuyên',
    'Huyện Xín Mần',
    'Huyện Yên Minh',
  ],
  'Hà Nam': [
    'Huyện Bình Lục',
    'Huyện Duy Tiên',
    'Huyện Kim Bảng',
    'Huyện Lý Nhân',
    'Huyện Thanh Liêm',
    'Phủ Lý',
  ],
  'Hà Nội': [
    'Hà Đông',
    'Hanoi',
    'Huyện Quốc Oai',
    'Quận Ba Đình',
    'Quận Hà Đông',
    'Sơn Tây',
  ],
  'Hà Tĩnh': [
    'Hà Tĩnh',
    'Huyện Cẩm Xuyên',
    'Huyện Can Lộc',
    'Huyện Ðức Thọ',
    'Huyện Kỳ Anh',
    'Huyện Nghi Xuân',
    'Huyện Thạch Hà',
  ],
  'Hải Dương': [
    'Hải Dương',
    'Huyện Bình Giang',
    'Huyện Cẩm Giàng',
    'Huyện Gia Lộc',
    'Huyện Kinh Môn',
    'Huyện Nam Sách',
    'Huyện Thanh Miện',
    'Thị Xã Chí Linh',
  ],
  'Hải Phòng': ['Cát Bà', 'Haiphong'],
  'Hậu Giang': ['Huyện Châu Thành A', 'Vị Thanh'],
  'Hồ Chí Minh': ['Cần Giờ', 'Củ Chi', 'Ho Chi Minh City'],
  'Hòa Bình': [
    'Hòa Bình',
    'Huyện Cao Phong',
    'Huyện Kỳ Sơn',
    'Huyện Lạc Thủy',
    'Huyện Lương Sơn',
    'Huyện Tân Lạc',
  ],
  'Hưng Yên': [
    'Hưng Yên',
    'Huyện Ân Thi',
    'Huyện Khoái Châu',
    'Huyện Kim Động',
    'Huyện Mỹ Hào',
    'Huyện Phù Cừ',
    'Huyện Tiên Lữ',
  ],
  'Khánh Hòa': [
    'Cam Ranh',
    'Huyện Diên Khánh',
    'Huyện Khánh Sơn',
    'Huyện Khánh Vĩnh',
    'Huyện Vạn Ninh',
    'Nha Trang',
    'Thành Phố Cam Ranh',
    'Thành Phố Nha Trang',
    'Thị Xã Ninh Hòa',
  ],
  'Kiên Giang': [
    'Dương Đông',
    'Hà Tiên',
    'Huyện An Biên',
    'Huyện An Minh',
    'Huyện Châu Thành',
    'Huyện Giồng Riềng',
    'Huyện Gò Quao',
    'Huyện Hòn Đất',
    'Huyện Kiên Hải',
    'Huyện Phú Quốc',
    'Huyện Tân Hiệp',
    'Huyện Vĩnh Thuận',
    'Kien Luong Town',
    'Rạch Giá',
  ],
  'Kon Tum': [
    'Huyện Đắk Glei',
    'Huyện Đắk Hà',
    'Huyện Đắk Tô',
    "Huyện Ia H'Drai",
    'Huyện Kon Plông',
    'Huyện Ngọc Hồi',
    'Huyện Sa Thầy',
    'Kon Tum',
  ],
  'Lai Châu': ['Huyện Mưòng Tè', 'Huyện Tam Đường', 'Huyện Than Uyên'],
  'Lâm Đồng': [
    'Bảo Lộc',
    'Đam Rong',
    'Đinh Văn',
    'Đưc Trọng',
    'Ðà Lạt',
    'Huyện Bảo Lâm',
    'Huyện Đạ Huoai',
    'Huyện Đạ Tẻh',
    'Huyện Đơn Dương',
    'Huyện Đức Trọng',
    'Huyện Lâm Hà',
  ],
  'Lạng Sơn': [
    'Huyện Bắc Sơn',
    'Huyện Bình Gia',
    'Huyện Cao Lộc',
    'Huyện Chi Lăng',
    'Huyện Đình Lập',
    'Huyện Hũu Lũng',
    'Huyện Vặn Quan',
    'Lạng Sơn',
  ],
  'Lào Cai': [
    'Huyện Bắc Hà',
    'Huyện Bảo Yên',
    'Huyện Bát Xát',
    'Huyện Mường Khương',
    'Huyện Sa Pa',
    'Huyện Si Ma Cai',
    'Huyện Văn Bàn',
    'Lào Cai',
    'Lao Chải',
    'Sa Pa',
  ],
  'Long An': [
    'Cần Giuộc',
    'Huyện Bến Lức',
    'Huyện Cần Đước',
    'Huyện Cần Giuộc',
    'Huyện Châu Thành',
    'Huyện Đức Hòa',
    'Huyện Đức Huệ',
    'Huyện Mộc Hóa',
    'Huyện Tân Hưng',
    'Huyện Tân Thạnh',
    'Huyện Tân Trụ',
    'Huyện Thạnh Hóa',
    'Huyện Thủ Thừa',
    'Huyện Vĩnh Hưng',
    'Tân An',
  ],
  'Nam Định': [
    'Huyện Giao Thủy',
    'Huyện Hải Hậu',
    'Huyện Mỹ Lộc',
    'Huyện Nam Trực',
    'Huyện Nghĩa Hưng',
    'Huyện Trực Ninh',
    'Huyện Vụ Bản',
    'Huyện Ý Yên',
    'Nam Định',
  ],
  'Nghệ An': [
    'Huyện Anh Sơn',
    'Huyện Con Cuông',
    'Huyện Diễn Châu',
    'Huyện Đô Lương',
    'Huyện Hưng Nguyên',
    'Huyện Kỳ Sơn',
    'Huyện Nam Đàn',
    'Huyện Nghi Lộc',
    'Huyện Nghĩa Đàn',
    'Huyện Quế Phong',
    'Huyện Quỳ Châu',
    'Huyện Quỳ Hợp',
    'Huyện Quỳnh Lưu',
    'Huyện Thanh Chương',
    'Huyện Tương Dương',
    'Huyện Yên Thành',
    'Vinh',
    'Yên Vinh',
  ],
  'Ninh Bình': [
    'Huyện Hoa Lư',
    'Huyện Kim Sơn',
    'Huyện Nho Quan',
    'Huyện Yên Khánh',
    'Huyện Yên Mô',
    'Ninh Bình',
  ],
  'Ninh Thuận': ['Phan Rang-Tháp Chàm'],
  'Phú Thọ': [
    'Huyện Cẩm Khê',
    'Huyện Đoan Hùng',
    'Huyện Hạ Hòa',
    'Huyen Lam Thao',
    'Huyện Thanh Ba',
    'Huyện Yên Lập',
    'Thành Phố Việt Trì',
    'Thị xã Phú Thọ',
    'Việt Trì',
  ],
  'Phú Yên': ['Huyện Sơn Hòa', 'Huyện Sông Hinh', 'Sông Cầu', 'Tuy Hòa'],
  'Quảng Bình': [
    'Huyện Lệ Thủy',
    'Huyện Quảng Ninh',
    'Huyện Quảng Trạch',
    'Huyện Tuyên Hóa',
    'Kwang Binh',
  ],
  'Quảng Nam': [
    'Hội An',
    'Huyện Duy Xuyên',
    'Huyện Đại Lộc',
    'Huyện Điện Bàn',
    'Huyện Hiệp Đức',
    'Huyện Nam Giang',
    'Huyện Núi Thành',
    'Huyện Phước Sơn',
    'Huyện Tiên Phước',
    'Huyện Trà My',
    'Tam Kỳ',
  ],
  'Quảng Ngãi': [
    'Huyện Ba Tơ',
    'Huyện Bình Sơn',
    'Huyện Đức Phổ',
    'Huyện Lý Sơn',
    'Huyện Minh Long',
    'Huyện Mộ Đức',
    'Huyện Nghĩa Hành',
    'Huyện Sơn Hà',
    'Huyện Sơn Tây',
    'Huyện Sơn Tịnh',
    'Huyện Trà Bồng',
    'Huyện Tư Nghĩa',
    'Quảng Ngãi',
  ],
  'Quảng Ninh': [
    'Cẩm Phả',
    'Cẩm Phả Mines',
    'Hạ Long',
    'Huyện Ba Chẽ',
    'Huyện Bình Liêu',
    'Huyện Cô Tô',
    'Huyện Đầm Hà',
    'Huyện Đông Triều',
    'Huyện Hải Hà',
    'Huyện Hoành Bồ',
    'Huyện Tiên Yên',
    'Huyện Vân Đồn',
    'Móng Cái',
    'Thành Phố Uông Bí',
  ],
  'Quảng Trị': [
    'Ðông Hà',
    'Huyện Cam Lộ',
    'Huyện Đa Krông',
    'Huyện Gio Linh',
    'Huyện Hải Lăng',
    'Huyện Hướng Hóa',
    'Huyện Triệu Phong',
    'Huyện Vĩnh Linh',
  ],
  'Sóc Trăng': [
    'Huyện Kế Sách',
    'Huyện Long Phú',
    'Huyện Mỹ Tú',
    'Huyện Mỹ Xuyên',
    'Huyen Nga Nam',
    'Huyện Thạnh Trị',
    'Sóc Trăng',
  ],
  'Sơn La': [
    'Huyện Bắc Yên',
    'Huyện Mai Sơn',
    'Huyện Mộc Châu',
    'Huyện Mường La',
    'Huyện Phù Yên',
    'Huyện Quỳnh Nhai',
    'Huyện Sông Mã',
    'Huyện Thuận Châu',
    'Huyện Yên Châu',
    'Sơn La',
  ],
  'Tây Ninh': [
    'Huyện Bến Cầu',
    'Huyện Dương Minh Châu',
    'Huyện Gò Dầu',
    'Huyện Hòa Thành',
    'Huyện Tân Châu',
    'Huyện Trảng Bàng',
    'Phú Khương',
    'Tây Ninh',
  ],
  'Thái Bình': [
    'Huyện Ðông Hưng',
    'Huyện Hưng Hà',
    'Huyện Kiến Xương',
    'Huyện Quỳnh Phụ',
    'Huyện Thái Thụy',
    'Huyện Tiền Hải',
    'Huyện Vũ Thư',
    'Thái Bình',
  ],
  'Thái Nguyên': ['Thái Nguyên'],
  'Thanh Hóa': [
    'Bỉm Sơn',
    'Huyện Bá Thước',
    'Huyện Cẩm Thủy',
    'Huyện Đông Sơn',
    'Huyện Hà Trung',
    'Huyện Hậu Lộc',
    'Huyện Lang Chánh',
    'Huyện Mường Lát',
    'Huyện Nga Sơn',
    'Huyện Ngọc Lặc',
    'Huyện Như Thanh',
    'Huyện Như Xuân',
    'Huyện Nông Cống',
    'Huyện Quan Hóa',
    'Huyện Quan Sơn',
    'Huyện Quảng Xương',
    'Huyện Thiệu Hóa',
    'Huyện Thọ Xuân',
    'Huyện Thường Xuân',
    'Huyện Triệu Sơn',
    'Huyện Vĩnh Lộc',
    'Huyện Yên Định',
    'Thanh Hóa',
  ],
  'Thừa Thiên-Huế': [
    'Huế',
    'Huyện A Lưới',
    'Huyện Nam Đông',
    'Huyện Phong Điền',
    'Huyện Phú Lộc',
    'Huyện Phú Vang',
    'Huyện Quảng Ðiền',
  ],
  'Tiền Giang': [
    'Huyện Cái Bè',
    'Huyện Cai Lậy',
    'Huyện Châu Thành',
    'Huyện Chợ Gạo',
    'Huyện Gò Công Đông',
    'Huyện Gò Công Tây',
    'Huyện Tân Phước',
    'Mỹ Tho',
    'Thành Phố Mỹ Tho',
    'Thị Xã Gò Công',
  ],
  'Trà Vinh': [
    'Huyện Càng Long',
    'Huyện Cầu Kè',
    'Huyện Cầu Ngang',
    'Huyện Tiểu Cần',
    'Huyện Trà Cú',
    'Trà Vinh',
  ],
  'Tuyên Quang': [
    'Huyện Chiêm Hóa',
    'Huyện Hàm Yên',
    'Huyện Lâm Bình',
    'Huyện Na Hang',
    'Huyện Sơn Dương',
    'Huyện Yên Sơn',
    'Tuyên Quang',
  ],
  'Vĩnh Long': [
    'Huyện Long Hồ',
    'Huyện Mang Thít',
    'Huyện Tam Bình',
    'Huyện Trà Ôn',
    'Huyện Vũng Liêm',
    'Vĩnh Long',
  ],
  'Vĩnh Phúc': [
    'Huyện Bình Xuyên',
    'Huyện Tam Dương',
    'Huyện Tam Đảo',
    'Huyện Yên Lạc',
    'Vĩnh Yên',
  ],
  'Yên Bái': [
    'Huyện Lục Yên',
    'Huyện Mù Cang Chải',
    'Huyện Trạm Tấu',
    'Huyện Trấn Yên',
    'Huyện Văn Chấn',
    'Huyện Văn Yên',
    'Yên Bái',
  ],
};
