export const SOUTH_AFRICA_PROVINCES = {
  'Eastern Cape': [
    'East London',
    'Port Elizabeth',
    'Bhisho',
    'Umtata',
    'Queenstown',
    'Uitenhage',
    'Grahamstown',
    'Aliwal North',
    'Cradock',
    'Jeffrey’s Bay',
    'Summerstrand',
    'Lorraine',
    'Breidbach',
    'Kenton on Sea',
    'Bluewater Bay',
  ],
  'Free State': [
    'Welkom',
    'Bloemfontein',
    'Sasolburg',
    'Kroonstad',
    'Odendaalsrus',
    'Frankfort',
  ],
  Gauteng: [
    'Johannesburg',
    'Soweto',
    'Vereeniging',
    'Pretoria',
    'Katlehong',
    'Randburg',
    'Roodepoort',
    'Boksburg',
    'Germiston',
    'Centurion',
    'Springs',
    'Sandton',
    'Benoni',
    'Krugersdorp',
    'Alberton',
    'Edenvale',
    'Bronkhorstspruit',
    'Primrose',
    'Bedfordview',
    'Elsburg',
  ],
  'KwaZulu-Natal': [
    'Pietermaritzburg',
    'Durban',
    'Newcastle',
    'Vryheid',
    'Westville',
    'Ulundi',
    'New Hanover',
  ],
  Limpopo: ['Polokwane', 'Thohoyandou', 'Ga-Kgapane'],
  Mpumalanga: [
    'Middelburg',
    'Witbank',
    'Bethal',
    'Lydenburg',
    'Breyten',
    'Chrissiesmeer',
    'Nelspruit',
  ],
  'North West': [
    'Middelburg',
    'Witbank',
    'Bethal',
    'Lydenburg',
    'Breyten',
    'Chrissiesmeer',
    'Nelspruit',
  ],
  'Northern Cape': [
    'Kimberley',
    'Upington',
    'Prieska',
    'Kuruman',
    'Carnarvon',
    'Cape Town',
    'Khayelitsha',
    'Mitchells Plain',
    'George',
    'Paarl',
    'Worcester',
    'Saldanha',
    'Oudtshoorn',
    'Mossel Bay',
    'Kuilsrivier',
    'Beaufort West',
    'Vredenburg',
    'Malmesbury',
    'Stellenbosch',
    'Montagu',
    'Bredasdorp',
    'Velddrif',
    'Saron',
    'Citrusdal',
    'Vanrhynsdorp',
    'Genadendal',
    'Rawsonville',
  ],
};
