export const ZAMBIA_PROVINCES_CITIES = {
  'Central Province': [
    'Chibombo',
    'Chibombo District',
    'Kabwe',
    'Kapiri Mposhi',
    'Mkushi',
    'Mumbwa',
    'Serenje',
  ],
  'Copperbelt Province': [
    'Chambishi',
    'Chililabombwe',
    'Chingola',
    'Chingola District',
    'Kalulushi',
    'Kataba',
    'Kitwe',
    'Luanshya',
    'Mpongwe',
    'Mufulira',
    'Ndola',
  ],
  'Eastern Province': ['Chadiza', 'Chipata', 'Lundazi', 'Nyimba', 'Petauke'],
  'Luapula Province': ['Kawambwa', 'Mansa', 'Mwense', 'Nchelenge', 'Samfya'],
  'Lusaka Province': ['Chongwe', 'Kafue', 'Luangwa', 'Lusaka'],
  'Muchinga Province': ['Chama', 'Chinsali', 'Isoka', 'Mpika', 'Nakonde'],
  'Northern Province': [
    'Kaputa',
    'Kasama',
    'Luwingu',
    'Mbala',
    'Mporokoso',
    'Mpulungu',
    'Mungwi',
  ],
  'Northwestern Province': [
    'Kabompo',
    'Kalengwa',
    'Kansanshi',
    'Kasempa',
    'Mufumbwe',
    'Mwinilunga',
    'Solwezi',
    'Zambezi',
  ],
  'Southern Province': [
    'Choma',
    'Gwembe',
    'Itezhi-Tezhi District',
    'Livingstone',
    'Maamba',
    'Mazabuka',
    'Monze',
    'Nakambala',
    'Namwala',
    'Siavonga',
    'Siavonga District',
    'Sinazongwe',
  ],
  'Western Province': [
    'Kalabo',
    'Kaoma',
    'Limulunga',
    'Lukulu',
    'Mongu',
    'Senanga',
    'Sesheke',
  ],
};
