export const ZIMBABWE_PROVINCES_CITIES = {
  'Bulawayo Province': ['Bulawayo'],
  'Harare Province': ['Chitungwiza', 'Epworth', 'Harare'],
  Manicaland: [
    'Buhera District',
    'Chimanimani',
    'Chimanimani District',
    'Chipinge',
    'Chipinge District',
    'Dorowa Mining Lease',
    'Headlands',
    'Makoni District',
    'Mutare',
    'Mutare District',
    'Mutasa District',
    'Nyanga',
    'Nyanga District',
    'Nyazura',
    'Odzi',
    'Penhalonga',
    'Rusape',
  ],
  'Mashonaland Central Province': [
    'Bindura',
    'Bindura District',
    'Centenary',
    'Centenary District',
    'Concession',
    'Glendale',
    'Guruve District',
    'Mazowe',
    'Mazowe District',
    'Mount Darwin',
    'Mvurwi',
    'Rushinga District',
    'Shamva',
    'Shamva District',
  ],
  'Mashonaland East Province': [
    'Beatrice',
    'Chivhu',
    'Goromonzi District',
    'Macheke',
    'Marondera',
    'Marondera District',
    'Mudzi District',
    'Murehwa',
    'Murehwa District',
    'Mutoko',
    'Ruwa',
  ],
  'Mashonaland West Province': [
    'Banket',
    'Chakari',
    'Chegutu',
    'Chegutu District',
    'Chinhoyi',
    'Chirundu',
    'Hurungwe District',
    'Kadoma',
    'Kadoma District',
    'Kariba',
    'Kariba District',
    'Karoi',
    'Makonde District',
    'Mhangura',
    'Norton',
    'Raffingora',
  ],
  'Masvingo Province': [
    'Bikita District',
    'Chiredzi',
    'Chiredzi District',
    'Chivi District',
    'Gutu District',
    'Mashava',
    'Masvingo',
    'Masvingo District',
    'Mwenezi District',
    'Zvishavane',
  ],
  'Matabeleland North Province': [
    'Binga',
    'Binga District',
    'Bubi District',
    'Dete',
    'Hwange',
    'Hwange District',
    'Inyati',
    'Kamativi Mine',
    'Lupane',
    'Lupane District',
    'Nkayi District',
    'Victoria Falls',
  ],
  'Matabeleland South Province': [
    'Beitbridge',
    'Beitbridge District',
    'Esigodini',
    'Filabusi',
    'Gwanda',
    'Gwanda District',
    'Insiza',
    'Insiza District',
    'Mangwe District',
    'Matobo',
    'Plumtree',
    'Umzingwane District',
  ],
  'Midlands Province': [
    'Gokwe',
    'Gweru',
    'Gweru District',
    'Kwekwe',
    'Kwekwe District',
    'Lalapanzi',
    'Mberengwa District',
    'Mvuma',
    'Redcliff',
    'Shangani',
    'Shurugwi',
    'Shurugwi District',
    'Zvishavane District',
  ],
};
